### PR TITLE
Fixes out of bound wildcard (#1275)

### LINKED ISSUE #1275: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype
Put the following code into Lib.java and compile it with normal javac (or with the Nullness Checker, behavior doesn't change):

```
abstract class Super {
  abstract SuperInner<?> a();

  abstract static class SuperInner<T extends SuperInner<T>> {
    abstract T b();
    abstract Super c();
  }
}

abstract class Sub extends Super {
  // It is significant that this method specializes the
  // return type. If this returns SuperInner, no crash happens.
  @Override
  abstract SubInner<?> a();

  abstract static class SubInner<S extends SubInner<S>> extends Super.SuperInner<S> {
    // Crashes with this overridden method and passes without it.
    @Override
    abstract Super c();
  }
}
```

Put the following code in Crash.java:

```
class Crash {
  void crash(Sub o) {
    o.a().b().b().c();
  }
}
```

When running the Nullness Checker on Crash.java we get:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: SuperInner<T extends SuperInner<T>>
  superType: SubInner<S extends SubInner<S extends SubInner<S>>>
  Compilation unit: Crash.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:723)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
 org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
...
error: AsSuperVisitor: type is not an erased subtype of supertype.
type: @Initialized @NonNull SuperInner<T extends @Initialized @NonNull SuperInner<T>>
  superType: @Initialized @NonNull SubInner<S extends @Initialized @NonNull SubInner<S extends @Initialized @NonNull SubInner<S>>>
  Compilation unit: Crash.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:723)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
 org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
```

This bug was hard to reproduce independently. See some notes in Lib.java about small variations that pass.
Thanks to @cushon for help with reproducing this issue.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1275

### CODE REVIEW

File: checker/jtreg/nullness/issue1275/Main.java [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/*
+ * @test
+ * @summary Test case for Issue 1275.
+ * https://github.com/typetools/checker-framework/issues/1275
+ *
+ * @compile -XDrawDiagnostics -processor org.checkerframework.checker.nullness.NullnessChecker#NullnessChecker -AprintErrorStack -Anomsgtext Lib.java
```
Comment (wmdietl) [inline checker/jtreg/nullness/issue1275/Main.java]: Remove the '#NullnessChecker' here and in the next line. That's at least one reason for the jtreg failure.

File: framework/src/org/checkerframework/framework/type/SupertypeFinder.java [hunk 2]
```diff
@@ -189,6 +196,51 @@
...
+         * Number from capture of ? extends Object}.
+         *
+         * <p>Because the Checker Framework does not implement capture conversion, the wildcard's
+         * upper bound may not be within the type parameter. This method fixes that.
+         *
+         * @param element type parameter to which {@code wildcard} is an argument
+         * @param wildcard wildcard type whose upper bound may be modified.
+         * @return
+         */
+        private void fixWildcardBound(
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: I find it strange that the fix is here, in SupertypeFinder.
Did you try putting similar code into AnnotatedWildcardType#fixupBoundAnnotations or some similar place there?
That way, we would fix this problem once and for all and don't have similar issues elsewhere in the code.

Comment (smillst) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: We avoided that elsewhere in the code because the error messages would then contain types that aren't in the source code, which could be confusing to users.  We could implement something where when wildcards are printed, they also contain the original wildcard type.  This would be similar to what Java does:
 `CAP#1 extends Number from capture of ? extends Object`

File: checker/jtreg/nullness/issue1275/Main.java (hunk 1 above)
Comment (smillst) [inline checker/jtreg/nullness/issue1275/Main.java]: Thanks for pointing this out.  Oddly, this test passed on my machine...

File: framework/src/org/checkerframework/framework/type/SupertypeFinder.java (hunk 2 above)
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: We could additionally store "original" super/extends bounds with the AnnotatedWildcardType and use that in error messages.
I think it would be better to do this "widenToUpperbound" once in the AWT and make sure we never run into this same issue again.

File: checker/jtreg/nullness/issue1275/Main.java [hunk 3]
```diff
@@ -0,0 +1,10 @@
+/*
```
Comment (wmdietl) [inline checker/jtreg/nullness/issue1275/Main.java]: You can simply add this jtreg header on top of Crash.java and not add this class.

File: framework/src/org/checkerframework/framework/type/SupertypeFinder.java [hunk 4]
```diff
@@ -189,6 +196,50 @@
...
+                TypeParameterElement element, AnnotatedWildcardType wildcard) {
+            if (TypesUtils.isErasedSubtype(types, wildcard.getUnderlyingType(), element.asType())) {
+                return;
+            }
+            AnnotatedTypeMirror bound = wildcard.getExtendsBound();
+            AnnotatedTypeVariable atv = (AnnotatedTypeVariable) atypeFactory.fromElement(element);
+            wildcard.setExtendsBound(atv.getUpperBound());
+            wildcard.getExtendsBound().replaceAnnotations(bound.getAnnotations());
+
+            // If the upper bound of the type parameter refers to itself, then can those
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: I'm not sure what the `can those` part means.

**Comment by wmdietlGC** [comment]
I pulled in this change and checked the real code that I used for reproducing #1275.
This change fixes the exception on that project (or the source for that project changed...).

Unfortunately, I still get the exception on other code; full stack trace:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: ...
  supertype: ...
  Compilation unit: ...
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
 org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
 org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
 org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_NotTypevarNorWildcard(AsSuperVisitor.java:586)
  org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:593)
  org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:632)
 org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
 org.checkerframework.framework.util.QualifierPolymorphism$PolyCollector.visitTypeVariable(QualifierPolymorphism.java:600)
 org.checkerframework.framework.util.QualifierPolymorphism$PolyCollector.visitTypeVariable(QualifierPolymorphism.java:342)
 org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable.accept(AnnotatedTypeMirror.java:1502)
 org.checkerframework.framework.type.visitor.SimpleAnnotatedTypeVisitor.visit(SimpleAnnotatedTypeVisitor.java:64)
  org.checkerframework.framework.util.QualifierPolymorphism.annotate(QualifierPolymorphism.java:213)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1369)
 org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:171)
 org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:45)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
 org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1191)
 org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:965)
 org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:202)
 org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:885)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:49)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:24)
 org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:404)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:225)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1095)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1052)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:982)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1313)
 org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:223)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:281)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:960)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:487)
 org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
 com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

I'll see what is different about this other project and will try producing another minimal test.
So I think there is no hurry in merging this PR.

**Comment by wmdietlGC** [comment]
Reproduced the new bug in #1308.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 5]
```diff
@@ -3239,6 +3239,10 @@ public AnnotatedWildcardType getUninferredWildcardType(AnnotatedTypeVariable typ
      * @param wildcard AnnotatedWildcardType whose upper bound is used to widen
      * @return {@code annotatedTypeMirror} widen to the upper bound of {@code wildcard}
      */
+    // TODO: BoundsInitializer#initializeExtendsBound(AnnotatedWildcardType) and
+    // SupertypeFinder#fixWildcardBound} have simalar logic for handling unbounded wildcards.
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: The closing curly here should be `()` or removed? Same for the other two copies.

**Comment by smillst** [comment]
>Do you want to see whether #1308 can be fixed as a simple change to this PR? Or do you prefer merging this and then starting a new fix?

I looked at #1308.  It seems to be a problem with type argument inference rather than out-of-bounds wildcards (https://github.com/typetools/checker-framework/issues/1308#issuecomment-305640086).  So, let's just merge this fix.

**Comment by wmdietl** [comment]
Sounds good.
