### PR TITLE
Correct handling of qualifier only constraints

### LINKED ISSUE #6382: False positive NonNull requirement for generic input
Thanks for submitting an issue.
As explained in the instructions for submitting an issue at https://checkerframework.org/manual/#reporting-bugs, please include four pieces of information:
 * commands (that can be cut-and-pasted into a command shell),
 * inputs,
 * outputs, and
 * expectation.

Hi there. I have some code that makes a map, where the type of the Map is determined by the input map <K, V> entries.
Here is my mapmaker code:
```
public class MapMaker {
    @SafeVarargs
    @SuppressWarnings("varargs")
    public static <K, V> Map<K, V> makeMap(Map.Entry<K, V>... entries) {
        Map<K, V> map = new HashMap<>();
        for (Map.Entry<K, V> entry : entries) {
            map.put(entry.getKey(), entry.getValue());
        }
        return map;
    }

    @Covariant({0, 1})
    public static class SimpleEntry<K, V> implements Map.Entry<K, V> {
        private final K key;
        private V value;

        public SimpleEntry(K key, V value) {
            this.key   = key;
            this.value = value;
        }

        public K getKey() {
            return key;
        }

        @Override
        public V getValue() {
            return value;
        }

        @Override
        public V setValue(V value) throws UnsupportedOperationException {
            throw new UnsupportedOperationException();
        }

    }
}
```
And here is my code that uses it:
```
            MapMaker.makeMap(
                new MapMaker.SimpleEntry<>(
                    "foo",
                    "quux"
                ),
                new MapMaker.SimpleEntry<>(
                    "baz",
                    null
                )
            )
```
When running type checker it complains:
```
java: [argument] incompatible argument for parameter value of SimpleEntry.
  found   : null (NullType)
  required: @Initialized @NonNull String
```
But the docs for type checker state that:
```
 <T>
    Any type argument may be supplied for T.

    It is equivalent to <T extends @Nullable Object>, because @Nullable Object is the top type in the type hierarchy.
```
So null should be allowed here.
Conservative type checking should make
 "foo", "qux" ->  `Entry<String, @NonNull String>` -> convert to `Entry<String, @Nullable String>` because the value is covariant in the SimpleEntry
 "baz", null ->  `Entry<String, @Nullable Object>` -> convert to `Entry<String, @Nullable String>`

Is this an actual bug or is one of my steps above wrong?

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6382

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java [hunk 1]
```diff
@@ -287,6 +287,28 @@ public void addConstraintsFromComplementaryBounds(BoundKind kind, AbstractType s
         }
       }
     }
+    if (s.isUseOfVariable()) {
+      UseOfVariable otherVar = (UseOfVariable) s;
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java:291]: Eiher `s` or `otherVar` is an unexpected name.  Can you choose names that are more similar to one another and convey the meaning?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java [hunk 2]
```diff
@@ -287,6 +287,28 @@ public void addConstraintsFromComplementaryBounds(BoundKind kind, AbstractType s
...
+          break;
+        case LOWER:
+          otherVar.addQualifierBound(BoundKind.UPPER, qualifierBounds.get(BoundKind.EQUAL));
+          break;
+        case UPPER:
+          otherVar.addQualifierBound(BoundKind.LOWER, qualifierBounds.get(BoundKind.EQUAL));
+          break;
+      }
+
+      if (kind == BoundKind.EQUAL || kind == BoundKind.UPPER) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java:304]: I think this logic would be a bit easier to read if you inlined it into the switch.  (That will lead to a touch of code duplication, but I think it's OK and it may even be fewer lines of code than presently.)

**Review by mernst — CHANGES_REQUESTED** [review]

**Review by mernst — APPROVED** [review]
