### PR TITLE
Fix problems with superbounded wildcards

### LINKED ISSUE #1006: Exception during nullness checking of stream items
Here's a minimal version of the problematic code:

```
import java.util.function.Function;
import java.util.stream.*;
import java.util.*;

public class StreamProblem
{
    public static Map<String, Long> getFreq(String src)
    {
        return Stream.of(src).collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
    }	
}
```

Compiling with the nullness processor (version 2.1.7) gives an exception in the checker:
```
javac -cp checker-2.1.7.jar -processor org.checkerframework.checker.nullness.NullnessChecker -AprintErrorStack StreamProblem.java
error: AsSuperVisitor: Unexpected combination: type: NULL superType: NULL.
  type:  null
  superType:  null
  Compilation unit: StreamProblem.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:721)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:44)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitNull_Null(AbstractAtmComboVisitor.java:377)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:514)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:50)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.AtmLubVisitor.lubWithNull(AtmLubVisitor.java:70)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:53)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:638)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:619)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.handleNullTypeArguments(DefaultTypeArgumentInference.java:169)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:119)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:586)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1816)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1800)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1291)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:179)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:47)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1185)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:959)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:202)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:881)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:49)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:24)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:382)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:203)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1022)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:979)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:909)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1240)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:215)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:278)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:164)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:947)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:443)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:437)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
error: AsSuperVisitor: Unexpected combination: type: NULL superType: NULL.
  type: null
  superType: null
  Compilation unit: StreamProblem.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:721)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:44)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitNull_Null(AbstractAtmComboVisitor.java:377)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:514)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:50)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.AtmLubVisitor.lubWithNull(AtmLubVisitor.java:70)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:53)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:638)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:619)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.handleNullTypeArguments(DefaultTypeArgumentInference.java:169)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:119)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:586)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1816)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1800)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1291)
  org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.methodFromUse(NullnessAnnotatedTypeFactory.java:300)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:179)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:47)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1185)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:959)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:202)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:881)
  org.checkerframework.checker.initialization.InitializationTransfer.visitMethodInvocation(InitializationTransfer.java:196)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:210)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:51)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:382)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:203)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1022)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:979)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:909)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1240)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:215)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:274)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:57)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:947)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:443)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
2 errors
1 warning
```

Explicitly typing the identity and counting functions seems to avoid the problem, but thought I'd report it.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1006

### CODE REVIEW

File: checker/tests/nullness/java8inference/Issue402.java [hunk 1]
```diff
@@ -3,13 +3,14 @@
...
-// @skip-test
-
 import java.util.Comparator;
 import javax.annotation.CheckForNull;
 import javax.annotation.Nullable;
 
+@SuppressWarnings({
+    "nullness",
+    "keyfor"
+}) // Type argument inference does not infer the correct types.
```
Comment (wmdietlGC) [inline checker/tests/nullness/java8inference/Issue402.java]: I would add the explanation before the SuppressWarning.
Can we add an issue number for when we expect this to be fixed. Is it #979?

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 2]
```diff
@@ -1051,6 +1051,12 @@ protected boolean visitWildcardSubtype(
         final Types types = subtype.atypeFactory.getProcessingEnv().getTypeUtils();
         final Elements elements = subtype.atypeFactory.getProcessingEnv().getElementUtils();
 
+        if (subtype.getKind() == TypeKind.NULL) {
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Is this actually the correct thing to do or just a hack to work around the crash?
Can you add some indication either way?

File: checker/tests/nullness/java8inference/Issue402.java (hunk 1 above)
Comment (mernst) [inline checker/tests/nullness/java8inference/Issue402.java]: The suggestion about issue number is a good one.

Our standard is to put the `@SuppressWarnings` explanation on the same line with the `@SuppressWarnings` annotation; in this case, google-code-format has broken the lines, but I wouldn't move the annotations to accommodate the formatting tool.

Comment (wmdietlGC) [inline checker/tests/nullness/java8inference/Issue402.java]: The point of that standard is to make searching for `SuppressWarnings` and reasons convenient.
The explanation should be on line 10 after the `@SuppressWarnings({` to make it easy to find.

Comment (mernst) [inline checker/tests/nullness/java8inference/Issue402.java]: True.  Personall, I search for the key rather than the string `"@SuppressWarnings"`.  Maybe you do searches for `@SuppressWarnings`, so for you putting the warning on its line would be better.  There isn't a great solution here, unfortunately -- none of the three locations will accommodate all our needs.

Comment (wmdietlGC) [inline checker/tests/nullness/java8inference/Issue402.java]: Ok, but the current location satisfies neither having the explanation with the `@SuppressWarnings` nor with the key.
You had stated 'Our standard is to put the @SuppressWarnings explanation on the same line with the @SuppressWarnings annotation'.
Anyways, you seem to insist on this location so let's keep it.

Comment (mernst) [inline checker/tests/nullness/java8inference/Issue402.java]: On the same line as the end of the annotation.
This would be greppable by running a local version of google-java-format that uses longer lines.w

Can you explain how you process these automatically?  Then we could find a solution that could work for you.  I've just been guessing so far because I don't know the grep pattern you use.  Thanks!

Comment (smillst) [inline checker/tests/nullness/java8inference/Issue402.java]: Note, that this test case is in the directory for Issue 979 and that it is marked at the top of the file as a test case for Issue 979.  I referenced this issue number after the `@SuppressWarnings` and moved the longer explanation to above the annotation so that the annotation remains on one line.

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java (hunk 2 above)
Comment (smillst) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: It's the correct thing.  I added a comment.

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 3]
```diff
@@ -1051,6 +1051,15 @@ protected boolean visitWildcardSubtype(
...
+            // Make a copy of the supertype so that if supertype is a composite type, the
+            // returned type will be fully annotated.  (For example, if sub is @C null and super is
+            // @A List<@B String>, then the returned type is @C List<@B String>.
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Wouldn't it be `@A @C List...` because deepCopy keeps the original annotation `@A`?
Should the `copy.addAnnotations` be `copy.replaceAnnotations`?

Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Below, AtmLubVisitor.java on new line 85 uses replaceAnnotations.

Comment (smillst) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Yes, it should be replace.  Good catch.
