### PR TITLE
Fix soundness issue when checking that an @MustCallAlias parameter is correctly assigned to an owning field

### LINKED ISSUE #5777: Resource Leak Checker: unsoundness in verifying `@MustCallAlias` with non-final `@Owning` field
Test case:

```java
  static class Wrapper implements Closeable {
    @Owning Socket socket;

    @MustCallAlias
    Wrapper(@MustCallAlias Socket s)throws IOException {
      if (this.socket != null) { this.socket.close(); }
      this.socket = s;
      this.socket = null;
    }
  }
```

Kind of a weird one, but I think we should get some kind of error, since at the end of the constructor the `Wrapper` object is no longer a resource alias with the passed-in `Socket`.

### PR DESCRIPTION
**Pull request by kelloggm**
fixes #5777 

This implementation does introduce some false positives (see the test cases), but I think they'll only occur in very unusual code. I'm open to suggestions on how to prevent them; long-term, I think the solution is to decouple `@MustCallAlias` checking from `@PolyMustCall`.

### CODE REVIEW

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -413,7 +413,9 @@ public Void visitIdentifier(IdentifierTree tree, AnnotatedTypeMirror type) {
       Element elt = TreeUtils.elementFromUse(tree);
       if (elt.getKind() == ElementKind.PARAMETER
           && (noLightweightOwnership || getDeclAnnotation(elt, Owning.class) == null)) {
-        type.replaceAnnotation(BOTTOM);
+        if (!type.hasAnnotation(POLY)) {
```
Comment (msridhar) [inline checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java:416]: Could we add a comment explaining this new logic?

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java [hunk 2]
```diff
@@ -73,6 +75,35 @@ public Void visitReturn(ReturnTree tree, Void p) {
     return super.visitReturn(tree, p);
   }
 
+  @Override
+  public Void visitAssignment(AssignmentTree tree, Void p) {
+    // The following code implements the following rule:
+    //  * It is always safe to assign a MustCallAlias parameter of a constructor
+    //    to an owning field of the containing class.
+    // It is necessary to special case this because MustCallAlias is translated
+    // into @PolyMustCall.
```
Comment (msridhar) [inline checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java:84]: I don't fully understand this comment, though perhaps it's because I'm unfamiliar with how `@PolyMustCall` is implemented

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java [hunk 3]
```diff
@@ -73,6 +75,35 @@ public Void visitReturn(ReturnTree tree, Void p) {
...
+    ExpressionTree lhs = tree.getVariable();
+    ExpressionTree rhs = tree.getExpression();
+    Element lhsElt = TreeUtils.elementFromTree(lhs);
+    Element rhsElt = TreeUtils.elementFromTree(rhs);
+    if (lhsElt != null && rhsElt != null) {
+      boolean lhsIsOwningField =
+          lhs.getKind() == Tree.Kind.MEMBER_SELECT
+              && atypeFactory.getDeclAnnotation(lhsElt, Owning.class) != null;
```
Comment (msridhar) [inline checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java:92]: Does it matter what the base expression is here?  What if it is not `this`?

**Review by msridhar — CHANGES_REQUESTED** [review]
Thanks for the fix and for the test cases!  I have to admit I don't fully understand the fix strategy here.  Could you possibly explain it a bit more?

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java (hunk 1 above)
Comment (kelloggm) [reply checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java:416]: I've added a comment explaining it.

For more context, though, this change makes this code (which treats non-owning parameters inside a method body as bottom) analogous to the similar code at call sites (which treats all non-owning parameter types as top). That code already had an exceptional for polymorphic types, so this change just makes the treatment inside method bodies the same.

Comment (kelloggm) [reply checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java:416]: (The similar code I mentioned is implemented by `MustCallAnnotatedTypeFactory#changeNonOwningParameterTypesToTop`, if you'd like to look at it.)

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java (hunk 3 above)
Comment (kelloggm) [reply checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java:92]: (The new test case is `checker/tests/resourceleak/MustCallAliasNotThis.java`)

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java (hunk 1 above)
Comment (msridhar) [reply checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java:416]: Makes sense thanks!

File: checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java (hunk 3 above)
Comment (msridhar) [reply checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java:103]: I think this is fine, and thanks for the comment.  I'm hoping we can do a deeper re-think of `@CreatesMustCallFor` and support for non-final `@Owning` fields at some point.  For now I think some confusion at corner cases is inevitable.

**Review by msridhar — APPROVED** [review]
This change now LGTM.  The extra error messages are not ideal but worth it to make the checker sound.  We can try to address with a deeper change in the future.
