### PR TITLE
Fix bug in isSubtype for wildcards

### LINKED ISSUE #1111: AsSuperVisitor: type is not an erased subtype of supertype with wildcards
Take:

```
import java.util.List;

class WildcardCrash {
  void foo(Box<? super Integer> box, List<Integer> list) {
    bar(box, list);
  }

  <T extends Number> void bar(
      Box<T> box, Iterable<? extends T> list) {}

  class Box<T extends Number> {}
}
```

and run any checker (tested with regex and nullness) and you'll get:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: Number
  superType: Integer
  Compilation unit: WildcardCrash.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:725)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1063)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:493)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:257)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitWildcardSupertype(DefaultTypeHierarchy.java:998)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Wildcard(DefaultTypeHierarchy.java:622)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Wildcard(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:346)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:257)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitWildcardSubtype(DefaultTypeHierarchy.java:1037)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitWildcard_Wildcard(DefaultTypeHierarchy.java:946)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitWildcard_Wildcard(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:716)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:257)
  org.checkerframework.framework.type.DefaultTypeHierarchy.checkAndSubtype(DefaultTypeHierarchy.java:349)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedBy(DefaultTypeHierarchy.java:432)
  org.checkerframework.framework.type.DefaultTypeHierarchy.compareTypeArgs(DefaultTypeHierarchy.java:569)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:541)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:505)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:257)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:192)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:170)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1667)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1634)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2080)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:819)
  org.checkerframework.checker.regex.RegexVisitor.visitMethodInvocation(RegexVisitor.java:110)
  org.checkerframework.checker.regex.RegexVisitor.visitMethodInvocation(RegexVisitor.java:36)
```

### PR DESCRIPTION
**Pull request by smillst**
(Fixes #1111)

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 1]
```diff
@@ -1031,6 +1031,10 @@ protected boolean visitWildcardSubtype(
                 // TODO: wildcard capture conversion
                 // Two unannotated uses of reference-equal wildcard types are the same type
                 return true;
+            } else {
+                AnnotatedWildcardType superWildcard = (AnnotatedWildcardType) supertype;
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Some comment about the logic for this branch would be great. Once the TODO on line 1031 about wildcard captures is addressed, is this case still necessary?
Why is the second condition the way it is and not `isSubtype(supertype.getSuperBound(), subWildcard.getSuperBound())`, which would ensure that the subtype range is smaller than the supertype range?

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 2]
```diff
@@ -1031,6 +1031,10 @@ protected boolean visitWildcardSubtype(
                 // TODO: wildcard capture conversion
                 // Two unannotated uses of reference-equal wildcard types are the same type
                 return true;
+            } else {
+                // Otherwise just check that the upper bounds are in the correct relationship
+                AnnotatedWildcardType superWildcard = (AnnotatedWildcardType) supertype;
+                return isSubtype(subtype.getExtendsBound(), superWildcard.getExtendsBound());
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Why is this the correct relationship? I would have expected `isSubtype(subtype.getExtendsBound(), superWildcard.getSuperBound())`, which would ensure that all possible subtype instantiations are below the lower bound of the supertype. Like this, the subtype could be instantiated with something that is a supertype of the superWildcard, which would seem unsound.
