### PR TITLE
Fix problem with dataflow inside lambdas

### LINKED ISSUE #6629: Problem with dataflow inside a lambda during type argument inference
Trying to bump our Checkerframework version to from 3.42.0 to 3.43.0 and am seeing the following issue which is not clear to me:

NotNull is applied in the `package-info.java`:
```
@DefaultQualifier(value = NotNull.class,
    locations = {TypeUseLocation.FIELD, TypeUseLocation.PARAMETER, TypeUseLocation.RETURN})
```

The following code has started producing the following error:

```
    public List<DatasetModel> convert(List<VolumeDataset> volumeDatasets) {
        return volumeDatasets.stream().map(dcollectDatasetEntry -> {
            List<DatasetVolserModel> datasetVolserModels = convertVolumeDataset(dcollectDatasetEntry);
            DatasetTypeModel entryTypeModel = convertDcollectEntryType(dcollectDatasetEntry.getType());
            return new DatasetModel(
                dcollectDatasetEntry.getName(),
                entryTypeModel,
                datasetVolserModels,
                dcollectDatasetEntry.getCreationDate(),
                dcollectDatasetEntry.getLastReferenceDate());
        }).collect(Collectors.toList());
    }
```

```
error: [type.arguments.not.inferred] Could not infer type arguments for Stream.collect
        }).collect(Collectors.toList());
                  ^
  unsatisfiable constraint: @UnknownInitialization(io.xxx.cdp.api.models.dataset.DatasetModel.class) @NonNull DatasetModel <: @Initialized @Nullable Object @UnknownInitialization(io.xxx.cdp.api.models.dataset.DatasetModel.class) @NonNull DatasetModel <: @Initialized @Nullable Object
```

Is this expected? 
What has changed since 3.42.0 which is causing this issue?

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6629

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -1524,6 +1521,121 @@ protected void performFlowAnalysis(ClassTree classTree) {
...
+    Map<LambdaExpressionTree, ControlFlowGraph> lambdaToCFG = new HashMap<>();
+    ControlFlowGraph methodCFG = null;
+
+    boolean isConstructor = TreeUtils.isConstructor(method.getMethod());
+
+    // Analyze `method` and all lambdas contained in `method` until the type of the lambda result
+    // expressions do not change.
+    while (true) {
+      Queue<IPair<ClassTree, Store>> classQueueInMethod = new ArrayDeque<>();
+      Queue<IPair<LambdaExpressionTree, @Nullable Store>> lambdaQueueForMethod = new ArrayDeque<>();
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: Inconsistent naming 'InMethod` vs `ForMethod`.

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 2]
```diff
@@ -1524,6 +1521,121 @@ protected void performFlowAnalysis(ClassTree classTree) {
...
+        if (prevReturnedExpressionTypes != null) {
+          for (int i = 0; i < prevReturnedExpressionTypes.size(); i++) {
+            if (!prevReturnedExpressionTypes.get(i).equals(returnedExpressionTypes.get(i))) {
+              anyLambdaResultChanged = true;
+              break;
+            }
+          }
+        } else {
+          anyLambdaResultChanged = true;
+        }
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: Can you just use `returnedExpressionTypes.equals(prevReturnedExpressionTypes`?

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 3]
```diff
@@ -1524,6 +1521,121 @@ protected void performFlowAnalysis(ClassTree classTree) {
...
+          fromTypeTreeCache.clear();
+        }
+      }
+    }
+    postAnalyze(methodCFG);
+    lambdaToCFG.values().forEach(this::postAnalyze);
+  }
+
+  /**
+   * Returns true if the method containing all lambdas in {@code lambdas} must be reanalyzed.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: I think "must be reanalyzed" describes what a client uses this for, but does not describe the method itself.  I think this method returns true if any lambda has a non-void return type.

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 4]
```diff
@@ -1524,6 +1521,112 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
   }
 
+  /**
+   * A helper method for {@link #performFlowAnalysisForClass(ClassTree)} that analyzes {@code
+   * method} and all lambdas contained within it.
+   *
+   * @param classTree class tree containing {@code method}
+   * @param method method to analyze
+   * @param classQueue classes found within {@code method} are added to this queue
+   * @param fieldValues values of fields to be used
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: To be used where?  At entry to the method?  At entry to each lambda?

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 5]
```diff
@@ -1524,6 +1521,112 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
+   * @param capturedStore the input Store to use for captured variables, e.g. in a lambda
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: Is this the input store to the method?  I think so.  The wording makes it seem possible that this is intraprocedural and is used as an input to lambdas.

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 6]
```diff
@@ -1524,6 +1521,112 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
+              isConstructor,
+              /* updateInitializationStore= */ false,
+              /* isStatic= */ false,
+              capturedStore);
+
+      boolean anyLambdaResultChanged = false;
+      while (!lambdaQueueInMethod.isEmpty()) {
+        IPair<LambdaExpressionTree, @Nullable Store> lambdaPair = lambdaQueueInMethod.remove();
+        LambdaExpressionTree lambda = lambdaPair.first;
+        MethodTree mt =
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: What is the relationship between this and formal parameter `method`?  Can it be cached rather than recomputed on each iteration of the `while` loop?

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 7]
```diff
@@ -1524,6 +1521,112 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
+                tree -> getAnnotatedType(tree).getPrimaryAnnotations(),
+                TreeUtils.getReturnedExpressions(lambda));
+        List<AnnotationMirrorSet> prevReturnedExpressionAnnos = lambdaResultTypeMap.get(lambda);
+        if (prevReturnedExpressionAnnos == null
+            || !prevReturnedExpressionAnnos.equals(returnedExpressionAnnos)) {
+          anyLambdaResultChanged = true;
+        }
+        lambdaResultTypeMap.put(lambda, returnedExpressionAnnos);
+      }
+
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java:1593]: I think that after this point, the keyset of `lambdaToCFG` (and `lambdaToResultTypes`) never changes.  Is that true?  If true, does `containsAllVoidLambas` on the next line need to be repeatedly computed?

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 8]
```diff
@@ -1524,6 +1521,112 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
+      if (containsAllVoidLambdas(lambdaToCFG.keySet()) || !anyLambdaResultChanged) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: Swap the order, because the second one is very cheap and may short-cut the (currently) first one.
However, why is the call to `containsAllVoidLambdas` needed at all?  I would think that anytime it is true, `anyLambdaResultChanged` is false.

File: framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 9]
```diff
@@ -1524,6 +1521,113 @@ protected void performFlowAnalysisForClass(ClassTree classTree) {
...
+    lambdaToCFG.values().forEach(this::postAnalyze);
+  }
+
+  /**
+   * Returns true if every lambda in {@code lambdas} has a void return type; otherwise false.
+   *
+   * @param lambdas lambdas that are all contained within the same method
+   * @return true if no lambda has a non-void return type
+   */
+  private boolean containsAllVoidLambdas(Set<LambdaExpressionTree> lambdas) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java:1618]: Nit: I would have abstracted out "isVoidLambda", and I would have made the argument a Collection rather than a Set.  But this can be merged.  Thanks!
