### PR TITLE
Check erased types in AnnotatedTypeFactory#widenToUpperBound

### LINKED ISSUE #2446: AsSuperVisitor: type is not an erased subtype of supertype 21
```java
class Test {
  static class One<T, V> {}

  static class Two<V, B extends Two<V, B>> extends One<V, B> {}

  static class Three<V, B extends Three<V, B>> extends Two<V, B> {}

  static <B extends Three<Object, B>> Three<Object, ?> f() {
    throw new AssertionError();
  }

  static final Three<?, ?> F = f();
}
```

```
./checker-framework-2.8.0/checker/bin/javac -processor Nullness Test.java
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: Two<V extends Object, B extends Two<V extends Object, B extends Two<V extends Object, B>>>
  superType: Three<? extends Object, ? extends Two<V extends Object, B extends Two<V extends Object, B extends Two<V extends Object, B>>>>
  Compilation unit: Test.java
  Last visited tree at line 12 column 3:
    static final Three<?, ?> F = f();
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:345)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1085)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #2446.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -3577,7 +3577,8 @@ public AnnotatedTypeMirror widenToUpperBound(
         final TypeMirror wildcardUBTypeMirror = wildcard.getExtendsBound().getUnderlyingType();
         if (types.isSubtype(wildcardUBTypeMirror, toModifyTypeMirror)) {
             return annotatedTypeMirror;
-        } else if (types.isSubtype(toModifyTypeMirror, wildcardUBTypeMirror)) {
+        } else if (types.isSubtype(
+                types.erasure(toModifyTypeMirror), types.erasure(wildcardUBTypeMirror))) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: Can you add a comment why the types are erased in this case but not in the one above?
