### PR TITLE
Non-static fields can't be referenced from a static inner class or enum

### LINKED ISSUE #2587: Dependent type annotations: static inner classes should not refer to instance fields of the outer class
```
public abstract class Issue2587 {
    public enum EnumType {
        // :: error: (expression.unparsable.type.invalid) :: error: (assignment.type.incompatible)
        @KeyFor("myMap") MY_KEY,
        // :: error: (assignment.type.incompatible)
        @KeyFor("enumMap") ENUM_KEY;
        private static final Map<String, Integer> enumMap = new HashMap<>();

        void method() {
            @KeyFor("enumMap") EnumType t = ENUM_KEY;
            int x = enumMap.get(ENUM_KEY);
        }
    }

    public static class Inner {
        // :: error: (expression.unparsable.type.invalid)
        @KeyFor("myMap") String MY_KEY = "";
    }

    private final Map<String, Integer> myMap = new HashMap<>();
}
```
Outputs:
```
Issue2564.java:8: error: [assignment.type.incompatible] incompatible types in assignment.
        @KeyFor("myMap") MY_KEY,
                         ^
  found   : EnumType
  required: @KeyFor("this.myMap") EnumType
Issue2564.java:9: error: [assignment.type.incompatible] incompatible types in assignment.
        @KeyFor("enumMap") ENUM_KEY;
                           ^
  found   : EnumType
  required: @KeyFor("Issue2564.EnumType.enumMap") EnumType
Issue2564.java:13: error: [assignment.type.incompatible] incompatible types in assignment.
            @KeyFor("enumMap") EnumType t = ENUM_KEY;
                                            ^
  found   : @KeyFor("enumMap") EnumType
  required: @KeyFor("Issue2564.EnumType.enumMap") EnumType
Issue2564.java:14: error: [unboxing.of.nullable] unboxing a possibly-null reference enumMap.get(ENUM_KEY)
            int x = enumMap.get(ENUM_KEY);
                               ^
Issue2564.java:20: error: [assignment.type.incompatible] incompatible types in assignment.
        @KeyFor("myMap") String MY_KEY = "";
                                         ^
  found   : String
  required: @KeyFor("this.myMap") String
5 errors
```

### PR DESCRIPTION
**Pull request by Maxi17**
Fixes #2587 

If the annotated element is inside a static class or an enum and the field that the annotation refers to is non-static, then throw an exception.

I will try to make the code cleaner.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java [hunk 1]
```diff
@@ -307,6 +307,19 @@ public Receiver visit(NameExpr expr, FlowExpressionContext context) {
             }
 
             if (fieldElem != null && fieldElem.getKind() == ElementKind.FIELD) {
+                if (!originalReceiver
+                        && TreeUtils.enclosingClass(path) != null
+                        && (TreeUtils.enclosingClass(path)
+                                        .getModifiers()
+                                        .getFlags()
+                                        .contains(Modifier.STATIC)
+                                || TreeUtils.enclosingClass(path).getKind().equals(Tree.Kind.ENUM))
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java]: Enums, such as Tree.Kind, should be compared using `==` rather than `.equals`.

File: framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java [hunk 2]
```diff
@@ -307,6 +307,19 @@ public Receiver visit(NameExpr expr, FlowExpressionContext context) {
             }
 
             if (fieldElem != null && fieldElem.getKind() == ElementKind.FIELD) {
+                if (!originalReceiver
+                        && TreeUtils.enclosingClass(path) != null
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java]: `path` is the TreePath to the expression (in source code) whose type has an annotation with the FlowExpression.  So, this code won't work correctly.  I added a failing test case.

File: framework/tests/flowexpression/InnerClasses.java [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    static class InnerClass2 {
+        public String outerInstanceField = "";
+
+        @FlowExp("outerInstanceField") Object o = null;
+    }
+
+    class TestUses {
+        void method(InnerClass innerClass, InnerClass2 innerClass2) {
+            // :: error: (expression.unparsable.type.invalid) :: error:
+            // (assignment.type.incompatible)
```
Comment (Maxi17) [inline framework/tests/flowexpression/InnerClasses.java]: @smillst I'm not sure why an `expression.unparsable.type.invalid` error is expected here, since the inner class `TestUses` and the method `method` are non-static. Can you please explain why you think it should be issued?
I agree with the `assignment.type.incompatible` error, but I think this is issue #152, `framework/tests/flowexpression/ThisSuper.java` test case. In the last part of the test case, something similar is tested and it fails.

Comment (smillst) [reply framework/tests/flowexpression/InnerClasses.java]: The error should be on the explicitly written annotation `@FlowExp("innerClass.outerInstanceField")`.  
The type of `innerClass` is `InnerClass`. `outerInstanceField` can't be referenced from an instance of `InnerClass`.  Also, if I had written innerClass.outerInstanceField, javac would issue an error.

File: checker/tests/nullness/Issue2587.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
+import java.util.HashMap;
+import java.util.Map;
+import org.checkerframework.checker.nullness.qual.KeyFor;
+
+public abstract class Issue2587 {
+    public enum EnumType {
+        // :: error: (expression.unparsable.type.invalid) :: error: (assignment.type.incompatible)
```
Comment (Maxi17) [inline checker/tests/nullness/Issue2587.java]: I think that a good idea would be to `@SuppressWarnings("assignment.type.incompatible")` for the entire class. These errors only distract from the actual issue.

Comment (smillst) [reply checker/tests/nullness/Issue2587.java]: I agree, just make sure you document why you added the `@SuppressWarnings`.

File: framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java [hunk 5]
```diff
@@ -307,7 +307,21 @@ public Receiver visit(NameExpr expr, FlowExpressionContext context) {
             }
 
             if (fieldElem != null && fieldElem.getKind() == ElementKind.FIELD) {
-                return getReceiverField(s, context, originalReceiver, fieldElem);
+                FieldAccess fieldAccess =
+                        (FieldAccess) getReceiverField(s, context, originalReceiver, fieldElem);
+                String className = fieldAccess.getReceiver().getType().toString();
+                Element scopeClassElement =
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java]: Use `org.checkerframework.javacutil.TypesUtils#getTypeElement` to go from a `TypeMirror` to an `TypeElement`.

File: framework/tests/flowexpression/InnerClasses.java [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+    static class InnerClass2 {
+        public String outerInstanceField = "";
+
+        @FlowExp("outerInstanceField") Object o = null;
+    }
+
+    class TestUses {
+        void method(InnerClass innerClass, InnerClass2 innerClass2) {
+            @SuppressWarnings("assignment.type.incompatible") // Issue 152
```
Comment (smillst) [inline framework/tests/flowexpression/InnerClasses.java]: Because the LHS annotation isn't parsable, this should issue an assignment.type.incompatible error.
