### PR TITLE
Fix compound assignment crash (#1397)

### LINKED ISSUE #1397: Crash with compound assignment and method type parameter inference
Take the following example program:

```java
class Box<T> {}

abstract class CrashCompound {
  abstract <T> T chk(T in);
  abstract <T> T unbox(Box<T> p);

  void foo(Box<Boolean> bb) {
    boolean res = false;
    res |= chk(unbox(bb));
  }
}
```

and run the Nullness Checker on it. You'll get:

```
error: QualifierHierarchy.leastUpperBounds: tried to determine LUB with sets of different sizes!
      Set 1: [] Set 2: [@org.checkerframework.checker.nullness.qual.UnknownKeyFor]
  Compilation unit: CrashCompound.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.QualifierHierarchy.leastUpperBounds(QualifierHierarchy.java:177)
  org.checkerframework.framework.type.treeannotator.PropagationTreeAnnotator.visitCompoundAssignment(PropagationTreeAnnotator.java:123)
  org.checkerframework.framework.type.treeannotator.PropagationTreeAnnotator.visitCompoundAssignment(PropagationTreeAnnotator.java:32)
  com.sun.tools.javac.tree.JCTree$JCAssignOp.accept(JCTree.java:1726)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.treeannotator.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:52)
  org.checkerframework.framework.type.treeannotator.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:20)
  com.sun.source.util.SimpleTreeVisitor.visitCompoundAssignment(SimpleTreeVisitor.java:189)
  com.sun.tools.javac.tree.JCTree$JCAssignOp.accept(JCTree.java:1726)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1280)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1266)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:979)
  org.checkerframework.common.basetype.BaseTypeVisitor.validateTypeOf(BaseTypeVisitor.java:3266)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1776)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1748)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitCompoundAssignment(BaseTypeVisitor.java:1384)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitCompoundAssignment(BaseTypeVisitor.java:160)
```

I verified with current master and with a branch that contains #1387 and can reproduce in both.
The April 2017 release did not exhibit this particular crash.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1397.

### CODE REVIEW

File: framework/tests/all-systems/java8inference/Issue1397.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+public class Issue1397 {
+
+    class Box<T> {}
+
+    abstract class CrashCompound {
+        abstract <T> T chk(T in);
+
+        abstract <T> T unbox(Box<T> p);
+
+        @SuppressWarnings("") //false positives
```
Comment (smillst) [inline framework/tests/all-systems/java8inference/Issue1397.java]: These are fixed in #1387 .

Comment (wmdietl) [inline framework/tests/all-systems/java8inference/Issue1397.java]: Maybe put that comment into the code, so that we don't forget to remove this.

Comment (smillst) [inline framework/tests/all-systems/java8inference/Issue1397.java]: I removed it in #1387.
