### PR TITLE
Type argument inference fixes.

### LINKED ISSUE #6891: The case which is leading to "error: AsSuperVisitor: type is not an erased subtype of supertype."
Hi there
Thank you for The Checker Framework.

I've noticed the following case.

If I run:
```
javac \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED -processor org.checkerframework.checker.nullness.NullnessChecker -cp ~/Downloads/checker-framework-3.48.2/checker/dist/checker.jar Reproduction.java
```

for the following code:
```
private Map<String, String> func(Set<Entity> entities) {

    return Optional.ofNullable(entities)
      .map(t -> t.stream().collect(Collectors.toMap(Entity::getName, Entity::getId))
      ).orElse(Collections.emptyMap());
  }
```

The Checker framework crashes in this way:
```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: Object
  superType: Map<String, String>
  ; The Checker Framework crashed.  Please report the crash.  Version: Checker Framework 3.48.2. 
  Compilation unit: Reproduction.java
  Last visited tree at line 11 column 5:
      return Optional.ofNullable(entities)
  Exception: java.lang.Throwable; java.lang.Throwable
  	at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:38)
  	at org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:148)
  	at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:338)
  	at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:30)
  	at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:313)
  	at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:34)
  	at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:107)
  	at org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:88)
  	at org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:118)
  	at org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:154)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:583)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:555)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:49)
  	at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:313)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:259)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:137)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:3137)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:3112)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:2277)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1717)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:408)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:408)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
  	at org.checkerframework.framework.source.SourceVisitor.visitMethod(SourceVisitor.java:110)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.processMethodTree(BaseTypeVisitor.java:1058)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:954)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:408)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:98)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:603)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:558)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:189)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
  	at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:86)
  	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1347)
  	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1268)
  	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:188)
  	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

It works correctly if I clarify types for Collectors call:
```
Collectors.<Entity, String, String>toMap(Entity::getName, Entity::getId)
```
I've attached the full version of this file: [Reproduction.zip](https://github.com/user-attachments/files/17770682/Reproduction.zip)

Seems like a bug. Possibly relates to #6762 and #6761.

### PR DESCRIPTION
**Pull request by smillst**
Fixing issue #6891 uncovered several other bugs in type argument inference that all had to be fixed together.  (I couldn't separate them because the test would not pass without all the fixes together.)

Fixes #6891.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 1]
```diff
@@ -139,6 +139,28 @@ public Constraint pop() {
...
+   * @param constraint a constraint
+   */
+  public void push(Constraint constraint) {
+    if (constraint != null && !list.contains(constraint)) {
+      list.add(0, constraint);
+    }
+  }
+
+  /**
+   * Adds the constraints to the beginning of this set and matatines the order of the constraints.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:154]: I'm not sure what "matatines" is saying.  Probably "maintains"?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 2]
```diff
@@ -139,6 +139,28 @@ public Constraint pop() {
...
+   *
+   * @param constraints constraints
+   */
+  public void push(ConstraintSet constraints) {
+    for (int i = constraints.list.size() - 1; i > -1; i--) {
+      push(constraints.list.get(i));
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:160]: This method pushes unconditionally, whereas the other `push` has checks.  What is the reason for the difference?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 3]
```diff
@@ -139,6 +139,28 @@ public Constraint pop() {
...
+      list.add(0, constraint);
+    }
+  }
+
+  /**
+   * Adds the constraints to the beginning of this set and matatines the order of the constraints.
+   *
+   * @param constraints constraints
+   */
+  public void push(ConstraintSet constraints) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:158]: I would rename this to "pushAll".

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 4]
```diff
@@ -139,6 +139,28 @@ public Constraint pop() {
...
+    for (int i = constraints.list.size() - 1; i > -1; i--) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:159]: Minor: unless the list is a linked list or very few items are being pushed, this is probably an inefficient way to add multiple items to the front.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 5]
```diff
@@ -162,26 +184,32 @@ public void remove(ConstraintSet subset) {
    */
   public ConstraintSet getClosedSubset(Dependencies dependencies) {
     ConstraintSet subset = new ConstraintSet();
-    Set<Variable> inputDependencies = new LinkedHashSet<>();
-    Set<Variable> outDependencies = new LinkedHashSet<>();
+    Set<Variable> allOutputsOfC = new LinkedHashSet<>();
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:187]: What is "C"?  Is it the variable defined [below](https://github.com/typetools/checker-framework/pull/7002/files#diff-443aa8ad97aad7a9e92c2f377eee7e690b5915c2df3ead07cde153dfd80c34dfR198)?
How will this be used, or why do we care about it?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 6]
```diff
@@ -162,26 +184,32 @@ public void remove(ConstraintSet subset) {
...
+    for (Constraint constraint : list) {
+      if (constraint instanceof TypeConstraint) {
+        allOutputsOfC.addAll(((TypeConstraint) constraint).getOutputVariables());
+      }
+      // No other constraints have output variables
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:192]: Please connect the dots.  Does this mean "... so this code puts, in `allOutputs`, everything that is needed"?
I suggest adding, just before each of the two top-level `for` loops, a comment explaining its purpose.  (And its algorithm, if that isn't obvious once its purpose is stated.)

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 7]
```diff
@@ -162,26 +184,32 @@ public void remove(ConstraintSet subset) {
...
+            if (dependencies.get(in).contains(out) || dependencies.get(out).contains(in)) {
+              found = true;
+            }
+          }
+        }
+        if (!found) {
+          subset.add(constraint);
         }
       } else {
+        // Other kinds of constraints do not have input variables.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:212]: What is the implication of this?  It's related to the purpose of the top-level for loop that this line is in.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 8]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
   /**
    * Resolves all the non-capture variables in {@code variables}.
    *
-   * @param variables the variables
+   * @param vars the variables
    */
-  private void resolveNoCapturesFirst(List<Variable> variables) {
+  private void resolveNoCapturesFirst(List<Variable> vars) {
     Variable smallV;
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:221]: I realize you didn't add this, but could you document what smallV is?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 9]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
+    List<Variable> variables = new ArrayList<>(vars.size());
+    vars.forEach(
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:223]: `forEach` is a useful method when a lambda already exists, but I find it harder to read than a loop if the lambda has to be created.
Here, however, I think it would be clearest to use `retainAll` (with a lambda!).  Are you avoiding that for efficiency reasons?  The implementation of retainAll in ArrayList never moves any item more than once, so it is relatively efficient.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 10]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
-        }
-        if (!v.isCaptureVariable()) {
-          int size = v.getBounds().getVariablesMentionedInBounds().size();
-          if (size < smallest) {
-            smallest = size;
-            smallV = v;
+      boolean change;
+      do {
+        change = false;
+        for (Variable v : new ArrayList<>(variables)) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:235]: The lambda above used `variable` for the name of each element of the list; this uses `v`.  What is the reason for the difference between them?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 11]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
-          break;
-        }
-        if (!v.isCaptureVariable()) {
-          int size = v.getBounds().getVariablesMentionedInBounds().size();
-          if (size < smallest) {
-            smallest = size;
-            smallV = v;
+      boolean change;
+      do {
+        change = false;
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:234]: What does `change` mean?  I think `changed` or `toChange` would be a better name, depending on how it is used.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 12]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
+            // loop again because a new instantiation has been found.
+            change = true;
           }
         }
+      } while (change);
+      for (Variable v : variables) {
+        int size = v.getBounds().getVariablesMentionedInBounds().size();
+        if (size < smallest) {
+          smallest = size;
+          smallV = v;
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:248]: Should `smallV` be named `smallestV`?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 13]
```diff
@@ -215,28 +215,38 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
-          // (Also avoids concurrent modification exception.)
-          break;
-        }
-        if (!v.isCaptureVariable()) {
-          int size = v.getBounds().getVariablesMentionedInBounds().size();
-          if (size < smallest) {
-            smallest = size;
-            smallV = v;
+      boolean change;
+      do {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:233]: The algorithm here is a bit tricky.  Could you document it?  I think it is just removing certain elements.  Is that right?  Why is a fixed-point loop needed?

**Review by mernst — CHANGES_REQUESTED** [review]
Thanks for the fix.  I have a few questions.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java (hunk 2 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:160]: This method calls the other push method and that method does the checking.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java (hunk 9 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:223]: Do you mean `removeIf`?  I don't see a version of `retainAll` that takes a function.  I will change it to:
```
    List<Variable> variables = new ArrayList<>(vars);
    variables.removeIf(v -> v.isCaptureVariable() || v.getBounds().hasInstantiation());
```

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 14]
```diff
@@ -162,26 +184,38 @@ public void remove(ConstraintSet subset) {
...
+    Set<Variable> allOutputs = new LinkedHashSet<>();
+    for (Constraint constraint : list) {
+      if (constraint instanceof TypeConstraint) {
+        allOutputs.addAll(((TypeConstraint) constraint).getOutputVariables());
+      }
+      // No other constraints have output variables
+    }
+
+    // Find a subset of this set where the following is true for all the constraints in the subset:
+    // no input variable of a constraint can influence an output variable of another constraint in
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:197]: By "another constraint", do you mean that it is permitted for an input variable of a given constraint can influence an output of that same constaint, and that is OK?  Or do you mean "an output variable of any constraint in the subset"?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 15]
```diff
@@ -162,26 +184,38 @@ public void remove(ConstraintSet subset) {
...
-          outDependencies.addAll(newOutputs);
-          subset.add(c);
-        } else {
-          // A cycle (or cycles) in the graph of dependencies between constraints exists.
-          subset = new ConstraintSet();
-          break;
+        List<Variable> inputs = c.getInputVariables();
+        boolean found = false;
+        for (Variable in : inputs) {
+          for (Variable out : allOutputs) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:208]: The use of `allOutputs` here enforces a stricter condition than that documented above on lines 196-199.  It enforces that no input of a constraint in the subset can influence any output variable whatever, even of a variable that is not in the subset.  Is that intentional?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 16]
```diff
@@ -162,26 +184,38 @@ public void remove(ConstraintSet subset) {
...
+    // Collection of all outputs of the constraints in this set.
+    Set<Variable> allOutputs = new LinkedHashSet<>();
+    for (Constraint constraint : list) {
+      if (constraint instanceof TypeConstraint) {
+        allOutputs.addAll(((TypeConstraint) constraint).getOutputVariables());
+      }
+      // No other constraints have output variables
+    }
+
+    // Find a subset of this set where the following is true for all the constraints in the subset:
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:196]: This does a greedy search.  Is that an important feature of the algorithm, or simply the implementation that you chose?  Please document either way.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 17]
```diff
@@ -190,12 +224,17 @@ public ConstraintSet getClosedSubset(Dependencies dependencies) {
       return subset;
     }
 
-    outDependencies.clear();
-    inputDependencies.clear();
+    // TODO: double check that this code is correct.
+    // checker/tests/all-systems/java8inference/MapEntryGetFails.java is a test that uses this code.
+    Set<Variable> inputDependencies = new LinkedHashSet<>();
+    Set<Variable> outDependencies = new LinkedHashSet<>();
     // If this subset is empty, then there is a cycle (or cycles) in the graph of dependencies
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:231]: It's true that some cycle exists somewhere.  Is it possible that a closed subset already exists at this moment?  Does it matter?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 18]
```diff
@@ -190,12 +224,17 @@ public ConstraintSet getClosedSubset(Dependencies dependencies) {
...
     // between constraints.
+    // In this case, the constraints in C that participate in a dependency cycle (or cycles) and do
+    // not depend on any constraints outside of the cycle (or cycles) are considered.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:234]: What does "are considered" mean?  Please avoid passive voice and also use an active verb to clarify exactly what is done.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 19]
```diff
@@ -334,9 +373,17 @@ public BoundSet reduceOneStep(Java8InferenceContext context) {
       }
       this.addAll(((ReductionResultPair) result).constraintSet);
     } else if (result instanceof TypeConstraint) {
-      this.add((Constraint) result);
+      // Add the new constraints to the beginning of the list so they are reduced first. This is
+      // because each constraint is supposed to be fully resolved before moving onto another one.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:377]: Is this ordering related to the greediness I asked about earlier?  That greedy algorithm might resolve later variables in the list first; is that OK?

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 20]
```diff
@@ -213,36 +213,65 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
-   * @param variables the variables
+   * @param vars the variables
    */
-  private void resolveNonCapturesFirst(List<Variable> variables) {
-    Variable smallV;
-    do {
-      smallV = null;
+  private void resolveNonCapturesFirst(List<Variable> vars) {
+    // Variables that are not captures and need to be resolved. (Avoid side-effecting vars)
+    List<Variable> variables = new ArrayList<>(vars);
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:222]: Please don't use `variables` as the variable name.  Use `toResolve` or `nonCaptures` or some other term that conveys what these variables are.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java [hunk 21]
```diff
@@ -213,36 +213,64 @@ private BoundSet resolveSmallestSet(Set<Variable> as, BoundSet boundSet) {
...
+    variables.removeIf(Variable::isCaptureVariable);
+    applyInstantiationsToBounds(variables);
+    variables.removeIf(v -> v.getBounds().hasInstantiation());
+
+    // Until variables is empty:
+    // Find the variable, alpha, in `variables` that has the fewest variables (that do not already
+    // have an instantiation) mentioned in alpha's bounds.
+    // Resolve alpha using the "noncapture" resolution method.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:230]: What is the relationship between "instantiate" and "resolve"?

**Review by mernst — CHANGES_REQUESTED** [review]
I have a few questions about the algorithm.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java (hunk 19 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:381]: No, this code is reducing constraints not resolving variables.   (The use of `resolved` in this comment is incorrect and I've rewritten it.)

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java (hunk 21 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java:230]: Resolve means to find an instantiation for a variable using one of the resolution algorithms.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java (hunk 15 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java]: The documentation was wrong.

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java [hunk 22]
```diff
@@ -153,35 +175,49 @@ public void remove(ConstraintSet subset) {
...
-          subset = new ConstraintSet();
-          break;
+        List<Variable> inputsOfSingleConstraint = ((TypeConstraint) constraint).getInputVariables();
+        boolean foundInfluence = false;
+        for (Variable in : inputsOfSingleConstraint) {
+          for (Variable out : allOutputsOfC) {
+            if (dependencies.get(in).contains(out) || dependencies.get(out).contains(in)) {
+              foundInfluence = true;
+              break;
+            }
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java:223]: I would add "if (foundInfluence) break;" here for efficiency, but maybe it doesn't matter.

**Review by mernst — APPROVED** [review]
Thanks!
