### PR TITLE
Soundly handle must call obligations with unknown must call methods

### LINKED ISSUE #5908: Possible unsoundness in the resource leak checker due to ownership + generics
I am applying the resource leak checker to a large program. I encountered some interesting patterns.

Perhaps the most interesting: my program has a number of methods that take ownership of an object but are generic. In some sense these methods "forget" the type of the owned argument, including any must-call requirements. (In practice the owned objects are eventually passed back to a non-generic callback that closes the argument. The flow is not obviously correct and difficult to simplify, and therefore it is important to verify.)

I'm worried that the resource leak checker might be missing some bugs in my program. Consider this simplified example:

```java
package calvin.example;

import org.checkerframework.checker.mustcall.qual.*;

class Resource implements java.io.Closeable {
    @Override
    public void close() {
    }
}

public class Driver {

    public static <T> void sneakyDrop(@Owning T value) {
    }

    public static void main(String[] args) throws Exception {
        Resource x = new Resource();
        sneakyDrop(x);
    }

}
```

To my surprise, the call to `sneakyDrop(x)` seems to satisfy the resource leak checker even though the resource `x` is obviously not being closed.

### PR DESCRIPTION
**Pull request by kelloggm**
Fixes #5908.

~~I'm investigating the false positive in the "correct" version of the test case separately, because I can reproduce it with just the Called Methods Checker (and it's more important to close the soundness loophole).~~

This PR also changes the defaulting scheme used for type variable upperbounds. See the documentation.

Merge with https://github.com/codespecs/daikon/pull/492 ~and https://github.com/plume-lib/plume-util/pull/314~.

### CODE REVIEW

**Review by msridhar — DISMISSED** [review]
I am ok with getting this change in to fix the soundness bug.  However, if we can fix the false positive in the near future, that would be good too.  Without that I'm not sure there is a good way to work around the new warnings other than a suppression.

**Comment by msridhar** [comment]
@kelloggm I'm a little concerned about these new warnings and the impacts they are going to have on users, particularly since the warnings seem to appear in code that has nothing to do with resource management.  I think we should spend a bit of time trying to see if we can change defaulting of type variables to avoid these issues.

**Comment by smillst** [comment]
I was able to change some of the `required.method.not.known` errors into `required.method.not.called` errors.

As far as type variable defaulting, you can make the upper bound of type variables `@MustCall({})` by adding `TypeUseLocation.UPPER_BOUND}` to `@DefaultFor({TypeUseLocation.EXCEPTION_PARAMETER)` to `MustCall.java`. You may not want to do that though.  (Try it and see all the errors.)

What about changing the default of return types that are type variables to `@NotOwning`.  It looks like most of the errors are coming from returned values.  I looked at the code, but I couldn't figure out where to make that change.

For example:
```
public class RLTypeVarDefaulting<R, P> {
  public final R method( P p) {
    R r = other(p);
    return null;
  }

  // Add @NotOwning to the return type and the error in `method` goes away.
  private R other(P p) {
    return null;
  }
}
```

**Comment by kelloggm** [comment]
@smillst, thanks for your suggestions. Here are some notes on these two alternatives; I'd appreciate your (and @msridhar's) help in deciding which of them to take.

> What about changing the default of return types that are type variables to @NotOwning. It looks like most of the errors are coming from returned values. I looked at the code, but I couldn't figure out where to make that change.

I looked into doing this. It's technically possible and relatively easy (the change would need to be made in `MustCallConsistencyAnalyzer#shouldTrackReturnType`, around line 1640 - add a case that checks if the return type is a type variable). I've implemented it on the branch `issue5908-not-owning-on-typevar-returns` of my fork, if you'd like to [take a look](https://github.com/kelloggm/checker-framework/commit/2940d3b7e80097b686c2a7db7e8c0719fdd2d668).

The problem is that this causes some tests to fail, in a way that suggests to me that this change might be unsound. In particular, the following tests fail:
```
    3 expected diagnostics were not found:
      ACSocketTest.java:156: error: (required.method.not.called)
      ACSocketTest.java:160: error: (required.method.not.called)
      EnhancedFor.java:33: error: (required.method.not.called)
```

In each of these cases, we have something like `List<Socket> list` and then some method that produces a `Socket` is called, e.g., `List#get`. In each case, the tests expect that an error ought to be issued (we've produced a seemingly-new Socket!). Since we don't allow `List<@Owning Socket>`, maybe this is okay and the expected behavior, but I am surprised by it and I suspect some users will be too. I haven't been able to write a test case that actually demonstrates unsoundness based on this, though, so it might be that I'm just nervous because we'd be changing the checker's behavior.

> As far as type variable defaulting, you can make the upper bound of type variables @MustCall({}) by adding TypeUseLocation.UPPER_BOUND} to @DefaultFor({TypeUseLocation.EXCEPTION_PARAMETER) to MustCall.java. You may not want to do that though. (Try it and see all the errors.)

I looked into this too, in some detail. The number of new warnings is actually not as large as your comment suggested it might be, and this change actually would remove a large number of false positives in the Checker Framework itself (i.e., would remove warning suppressions) without introducing any new false positives. So, I think we ought to seriously consider it. You can [look at the changes](https://github.com/kelloggm/checker-framework/commit/8ff0341631350359c31359dd0cd49f14a17d840b) yourself on the `issue5908-change-defaults` branch of my fork.

The problem with this change is that it becomes an error to write `List<Socket>` and any other use of a type variable where the type argument itself isn't `@MustCall({})`. That gives the programmer a few (bad) choices when encountering a situation where they need to do so:
* write `List<@MustCall Socket>`. This makes it an error to actually add a `Socket` to the list, since the type of the `Socket` is `@MustCall("close")` but the list requires an empty `@MustCall`. Obviously not great, but it matches our design philosophy that the RLC doesn't support lists of `@Owning` resources.
* write `List<? extends Socket>`. This similarly precludes calls to `add` or other methods that require an instance of the type variable, but it preserves some of the behavior. This is the best choice most of the time, I think.
* suppress some warnings

One thing that I do like about this option is that it limits the false positives to code that actually uses a resource, which is extremely desirable. On the other hand, though, it doesn't give the programmer any real tools to verify code that uses arbitrarily-sized collections of resources (but, as @Calvin-L discovered in #5969, this is already true of the RLC).

**Comment by smillst** [comment]
@kelloggm From your discussion of the two options, I think changing the type variable defaulting makes the most sense.

**Comment by msridhar** [comment]
Based on my best understanding I also agree that changing type variable defaulting may be the best solution for the short term here.

**Comment by kelloggm** [comment]
Based on the feedback from @smillst and @msridhar, I've changed the type variable defaulting rule and wrote some documentation to go with it.

@msridhar can you review again, paying particular attention to the new text in `resource-leak-checker.tex`?

File: checker/tests/mustcall/EditLogInputStream.java [hunk 1]
```diff
@@ -6,6 +6,9 @@ abstract class EditLogInputStream implements Closeable {
 }
 
 interface JournalSet extends Closeable {
-  static final Comparator<EditLogInputStream> LOCAL_LOG_PREFERENCE_COMPARATOR =
+  static final Comparator<? extends EditLogInputStream> LOCAL_LOG_PREFERENCE_COMPARATOR =
+      // This is an undesirable false positive that occurs because of the defaulting used
+      // that the Must Call Checker uses for generics.
```
Comment (msridhar) [inline checker/tests/mustcall/EditLogInputStream.java:11]:
```suggestion
      // This is an undesirable false positive that occurs because of the defaulting
      // that the Must Call Checker uses for generics.
```

File: checker/tests/resourceleak/SneakyDrop.java [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+  public static void main5(String[] args) throws Exception {
+    Resource x = new Resource();
+    sneakyDrop5(x);
+  }
+
+  // TODO: The error here is a false positive: the Called Methods Checker for some reason fails to
+  // recognize that value has had close() called on it. The problem appears to be that
+  // the Called Methods Checker's store isn't updated. I suspect the problem has to do with
+  // generics/type variables.
```
Comment (msridhar) [inline checker/tests/resourceleak/SneakyDrop.java:55]: Is this comment still valid?

**Review by msridhar — APPROVED** [review]
Couple very minor comments but this LGTM overall.  @mernst may want to review the changes to the manual

**Review by msridhar — APPROVED** [review]
Re-approving the changes.  This is assuming nothing needs to be re-reviewed @kelloggm

**Comment by mernst** [comment]
@smillst Could you take a look at the code changes to determine the interactions with your `explicit-extends-object` branch?

**Comment by smillst** [comment]
> @smillst Could you take a look at the code changes to determine the interactions with your `explicit-extends-object` branch?

This pull request makes explicit and implicit upper bounds use the same default, so nothing in this branch will need to change.   In the `explicit-extends-object`,  any `extends @MustCall Object` can be removed.  If there are other annotations on the upper bound, `@MustCall` can be removed.  (This changes could be made in master after this pull request is merged.)

**Review by smillst — APPROVED** [review]
