### PR TITLE
Issue error to user when LTLengthOf annotation is illegal

### LINKED ISSUE #1936: Crash report: Index Checker crashed with @LTLengthOf(value = {"a", "b"}, offset = "x")
Consider:
```java
public class SimpleMethod {
    @NonNegative @LTLengthOf(value = {"this.arr1","this.arr2"}, offset = "1") int offset;
    int[] arr1 = new int[10];
    int[] arr2 = new int[10];

    void simple(int val){
        arr1[this.offset + 1] = val;
        arr2[this.offset] = val;
    }
    public static void main(String args[]) {
    }
}
```
What I'm trying to verify is only [offset + 1] needs to be less than arr1.length. Writing annotations like this is allowed by the checker but will lead to crashing.
I suggest that if optional offset value is written, It should be illegal to have less or more offset elements than value elements. Or simply state this case as an example of use in Javadoc for Annotation Type LTLengthOf.

Full error log with -AprintErrorStack
```java
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing SimpleMethod3.java
  Compilation unit: SimpleMethod3.java
  Exception: java.lang.AssertionError; Stack trace: org.checkerframework.checker.index.upperbound.UBQualifier.createUBQualifier(UBQualifier.java:108)
  org.checkerframework.checker.index.upperbound.UBQualifier.parseLTLengthOf(UBQualifier.java:65)
  org.checkerframework.checker.index.upperbound.UBQualifier.createUBQualifier(UBQualifier.java:45)
  org.checkerframework.checker.index.upperbound.UpperBoundAnnotatedTypeFactory$UpperBoundQualifierHierarchy.isSubtype(UpperBoundAnnotatedTypeFactory.java:317)
  org.checkerframework.framework.type.QualifierHierarchy.findAnnotationInHierarchy(QualifierHierarchy.java:632)
  org.checkerframework.framework.type.QualifierHierarchy.findAnnotationInSameHierarchy(QualifierHierarchy.java:615)
  org.checkerframework.framework.type.AnnotatedTypeMirror.getAnnotationInHierarchy(AnnotatedTypeMirror.java:255)
  org.checkerframework.framework.type.AnnotatedTypeMirror.isAnnotatedInHierarchy(AnnotatedTypeMirror.java:236)
  org.checkerframework.framework.util.defaults.QualifierDefaults$DefaultApplierElement.addAnnotation(QualifierDefaults.java:798)
  org.checkerframework.framework.util.defaults.QualifierDefaults$DefaultApplierElement$DefaultApplierElementImpl.scan(QualifierDefaults.java:983)
  org.checkerframework.framework.util.defaults.QualifierDefaults$DefaultApplierElement$DefaultApplierElementImpl.scan(QualifierDefaults.java:818)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:92)
  org.checkerframework.framework.util.defaults.QualifierDefaults$DefaultApplierElement.applyDefault(QualifierDefaults.java:765)
  org.checkerframework.framework.util.defaults.QualifierDefaults.applyDefaultsElement(QualifierDefaults.java:709)
  org.checkerframework.framework.util.defaults.QualifierDefaults.applyDefaults(QualifierDefaults.java:482)
  org.checkerframework.framework.util.defaults.QualifierDefaults.annotate(QualifierDefaults.java:366)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1463)
  org.checkerframework.checker.index.upperbound.UpperBoundAnnotatedTypeFactory.addComputedTypeAnnotations(UpperBoundAnnotatedTypeFactory.java:180)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1447)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1022)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.getAnnotatedTypeLhs(GenericAnnotatedTypeFactory.java:1325)
  org.checkerframework.framework.flow.CFAbstractTransfer.addFieldValues(CFAbstractTransfer.java:408)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:256)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:92)
  org.checkerframework.dataflow.analysis.Analysis.init(Analysis.java:463)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:183)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1220)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1177)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1107)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1494)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:248)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:291)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:162)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
1 error

```

### PR DESCRIPTION
**Pull request by kelloggm**
Fixes #1936.

### CODE REVIEW

File: checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java [hunk 1]
```diff
@@ -49,6 +52,29 @@ public Void visitArrayAccess(ArrayAccessTree tree, Void type) {
...
+        AnnotationMirror anno = TreeUtils.annotationFromAnnotationTree(node);
+        if (AnnotationUtils.areSameByClass(anno, LTLengthOf.class)) {
+            List<? extends ExpressionTree> args = node.getArguments();
+            if (args.size() == 2) {
+                // if offsets are provided, there must be the same number of them as there are arrays
+                List<String> sequences =
+                        AnnotationUtils.getElementValueArray(anno, "value", String.class, true);
+                List<String> offsets =
+                        AnnotationUtils.getElementValueArray(anno, "offset", String.class, true);
+                if (sequences.size() != offsets.size() && offsets.size() > 0) {
```
Comment (smillst) [inline checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: Why allow more offsets than sequences?  Also, this requirement should be documented in `LTLengthOf.java`.

Comment (kelloggm) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: This doesn't allow more offsets than sequences. An error is issued when the number of offsets isn't equal to the number of sequences and the number of offsets is non-zero (the second condition is necessary to allow `@LTLengthOf("a")`, which has zero offsets but a non-zero number of sequences). I'll add a test to cover that condition, though.

Comment (smillst) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: Oh right.  The error key is "not.enough.offsets", which is confusing because it will be issued when there are too many offsets, too.

Comment (kelloggm) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: Good point. I'll change it to "wrong.number.of.offsets" or something like that instead.

Comment (smillst) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: `offset.not.equal.sequence`, maybe?

Comment (kelloggm) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: What about `different.length.sequences.offsets`? I think I like that better and it's more clear about what the problem is.

Comment (smillst) [reply checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java]: Sounds good.

**Comment by kelloggm** [comment]
@smillst I think this is merge-able now - I should have reassigned you two days ago. If you're okay with it I can go ahead and merge it in.

Thanks!

**Comment by smillst** [comment]
You can merge.  FYI, master is failing, so the "downstream" build will fail on this pull request.

**Comment by kelloggm** [comment]
I can wait until master is passing to merge in that case.
