### PR TITLE
Fixes #607

### LINKED ISSUE #607: Index out of bounds exceptions with var args in byte code and lambda argument
Will add test case as pull request once issue number given.

### PR DESCRIPTION
**Pull request by smillst**
`isVarArgs()` should be called on a method element rather than the parameter element.

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -2987,7 +2987,7 @@ private AnnotatedDeclaredType getFunctionalInterfaceType(Tree lambdaTree,
                 NewClassTree newClass = (NewClassTree) parentTree;
                 int indexOfLambda = newClass.getArguments().indexOf(lambdaTree);
                 Pair<AnnotatedExecutableType, List<AnnotatedTypeMirror>> con = this.constructorFromUse(newClass);
-                AnnotatedTypeMirror constructorParam = AnnotatedTypes.unwrapVarargs(con.first.getParameterTypes(), indexOfLambda);
+                AnnotatedTypeMirror constructorParam = AnnotatedTypes.unwrapVarargs(con.first.getElement().isVarArgs(),con.first.getParameterTypes(), indexOfLambda);
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: Space after first argument.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 2]
```diff
@@ -2995,7 +2995,7 @@ private AnnotatedDeclaredType getFunctionalInterfaceType(Tree lambdaTree,
                 MethodInvocationTree method = (MethodInvocationTree) parentTree;
                 int index = method.getArguments().indexOf(lambdaTree);
                 Pair<AnnotatedExecutableType, List<AnnotatedTypeMirror>> exe = this.methodFromUse(method);
-                AnnotatedTypeMirror param = AnnotatedTypes.unwrapVarargs(exe.first.getParameterTypes(), index);
+                AnnotatedTypeMirror param = AnnotatedTypes.unwrapVarargs(exe.first.getElement().isVarArgs(),exe.first.getParameterTypes(), index);
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: Space after first argument.

File: framework/src/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 3]
```diff
@@ -1259,19 +1259,20 @@ public AnnotatedTypeMirror leastUpperBound(AnnotatedTypeMirror type,
      * Given a list of types representing the formal parameters to a method, get the parameter type
      * expect at the indexth position (unwrapping var args if necessary).
      *
+     * @param hasVarArg whether or not that last parameter is a vararg
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/AnnotatedTypes.java]: The 'that last parameter' reference wasn't clear to me - it depends on the parenthesized part of the body of the javadoc. I would make the `@param` descriptions as independent as possible.

File: framework/src/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 4]
```diff
@@ -1259,19 +1259,20 @@ public AnnotatedTypeMirror leastUpperBound(AnnotatedTypeMirror type,
...
      * @param parameterTypes The list of formal parameters to a method
      * @param index The index into parameterTypes of the parameter we want
      * @return If that parameter is a varArgs, return the component of the var args and NOT the array type.
      *         Otherwise, return the exact type of the parameter in the index position
      */
-    public static AnnotatedTypeMirror unwrapVarargs(List<AnnotatedTypeMirror> parameterTypes, int index) {
+    public static AnnotatedTypeMirror unwrapVarargs(boolean hasVarArg, List<AnnotatedTypeMirror> parameterTypes, int index) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/AnnotatedTypes.java]: The method is called `unwrapVarargs`. Should it ever be called with `hasVarArg` false?
Instead of adding the parameter, should the check for hasVarArg be moved outside?
Or can you optimize the implementation and check hasVarArg first?

**Comment by smillst** [comment]
@wmdietl  Werner, I didn't mean to merge this one before you looked at the changes I made based on your feedback.  I'm happy to address anymore feedback you may have.
