### PR TITLE
JavaExpressionParseUtil: Parse unqualified class names correctly.

### LINKED ISSUE #862: Flow Expressions:  Class names should be resolved based on the declaration scope
```
package pkg1;
import org.checkerframework.checker.nullness.qual.*;
class Class1 {
  public static @NonNull Object field;
}

package pkg2;
import org.checkerframework.checker.nullness.qual.*;
import pkg1.Class1;
class Class2 {
  @RequiresNonNull("Class1.field")
  public void foo() {}

package use;
import pkg2.Class2;
class Use {
    void use(Class2 class2) {
      //:: error: (contracts.precondition.not.satisfied)
      class2.foo();
    }
}
```

The expected error in class Use is not issued; instead, the following error is issued:

```
Class3.java:4: error: [flowexpr.parse.error] cannot parse the expression 'Class1: identifier not found'
       class2.foo();
                 ^
```

Revert the part of this comment that suppresses warnings based on this issue:
https://github.com/codespecs/daikon/commit/437ca4a30c8fd8fa2489e26ae38253117640ad1c

### PR DESCRIPTION
**Pull request by smillst**
See manual change for explantation. I also moved the code that parses identifiers to fields to a new method, so you'll see those changes, too.
Fixes #862. 

Merge with https://github.com/codespecs/daikon/pull/316

### CODE REVIEW

File: javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java [hunk 1]
```diff
@@ -262,6 +262,36 @@ public Element findClass(String name, TreePath path) {
         }
     }
 
+    /**
+     * Finds the class with {@code name} in a given type.
```
Comment (mernst) [inline javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java:266]: Does "in a given type" mean this is looking for a nested class?  Saying that (and even adding "Nested" to the method name) would be clearer, I think.

**Review by mernst — APPROVED** [review]
Looks good, thanks.

I tweaked the documentation in the manual.  If what I wrote is not correct, can we adjust the code to conform to the manual?
