### PR TITLE
Deep copy ATM before modifying it.

### LINKED ISSUE #7070: Type inference with explicit annotations
```
import java.util.Optional;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

public class Issue6740A {
  static class MyClass<Z> {}

  <T> @Nullable T getNullable(MyClass<T> type) {
    throw new RuntimeException();
  }

  static <T> Optional<@NonNull T> ofNullable(@Nullable T value) {
    return Optional.ofNullable(value);
  }

  <T> Optional<@NonNull T> getOpt(int index, MyClass<T> type) {
    return ofNullable(getNullable(type));
  }
}
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #7070.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/UseOfVariable.java [hunk 1]
```diff
@@ -167,21 +167,22 @@ public void addBound(Constraint parent, BoundKind kind, AbstractType bound) {
       // If the use has a primary annotation, then add the bound but with that annotations
       // set to bottom or top.  This makes it so that the java type is still a bound, but
       // the qualifiers do not change the results of inference.
+      AnnotatedTypeMirror copyATM = bound.getAnnotatedType().deepCopy();
+      AbstractType boundCopy = bound.create(copyATM, bound.getJavaType());
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/UseOfVariable.java:171]: Nit: "copyATM" is inconsistent with "boundCopy" and "boundCopy2", as names.

**Review by mernst — APPROVED** [review]
Thanks!

**Comment by fivemeyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Review by mernst — APPROVED** [review]
