### PR TITLE
Fixes #871 (Method reference crash)

### LINKED ISSUE #871: unexpected Throwable (IndexOutOfBoundsException)
... when the following program is compiled:
```
package bar;
import java.nio.file.*;
import java.util.function.Predicate;
interface Foo {
	default Iterable<Path> a() {
		return f(Files::isRegularFile);
	}

	Iterable<Path> f(Predicate<Path> condition) ;
}
```

Full error message: _unexpected Throwable (IndexOutOfBoundsException) while processing D:\workspace_neon\bar\src\main\java\bar\Foo.java; message: Index: 1, Size: 1; invoke the compiler
 with -AprintErrorStack to see the stack trace_.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #871

### CODE REVIEW

File: framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 1]
```diff
@@ -2900,18 +2900,26 @@ private boolean checkReceiverOverride() {
...
             List<AnnotatedTypeMirror> overriderParams = overrider.getParameterTypes();
             List<AnnotatedTypeMirror> overriddenParams = overridden.getParameterTypes();
 
-            // The functional interface of an unbound member reference has an extra parameter (the receiver).
-            if (methodReference
-                    && ((JCTree.JCMemberReference) overriderTree)
-                            .hasKind(JCTree.JCMemberReference.ReferenceKind.UNBOUND)) {
-                overriddenParams = new ArrayList<>(overriddenParams);
-                overriddenParams.remove(0);
+            // Fix up method refernece parameters.
```
Comment (mernst) [inline framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java]: Spell-check.
(I can't make changes directly when the pull request is from a branch that exists only on your own fork.)

**Comment by mernst** [comment]
Seems OK to me, once the typo is fixed.
