### PR TITLE
Correct handling of enclosing type in more places

### LINKED ISSUE #724: AnnotatedDeclaredType#getEnclosingType returns ATM with missing annotations

### LINKED ISSUE #1431: Error: Incomparable types (visitArray_Typevar not overriden in DefaultTypeHierarchy)
This error seems to happen because the method `visitArray_Typevar` is not overriden in `DefaultTypeHierarchy`. The default implementation inherited from `AbstractAtmComboVisitor` raises the error.

Test case:
```java
class Outer<V>{
	class Inner<T extends V>  {
	}
}
public class IncomparableCrash {
	static void m(Outer<Object>.Inner<int[]> ic) {
	}
}
```
Run the checker at master (3fa3c03ed1bd53124a4389f28b7a18f56533e700). Value checker is used just as an example, happens with other checkers as well:
```
checker/bin/javac -AprintErrorStack -processor org.checkerframework.common.value.ValueChecker IncomparableCrash.java
```
Error output:
```
error: Incomparable types ( @UnknownVal int @UnknownVal [], V extends @UnknownVal Object)visitHistory = VisitHistory(  )
  Compilation unit: IncomparableCrash.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:53)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitArray_Typevar(AbstractAtmComboVisitor.java:107)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:292)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:246)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:181)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:159)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkTypeArguments(BaseTypeVisitor.java:1990)
  org.checkerframework.common.basetype.BaseTypeValidator.visitParameterizedType(BaseTypeValidator.java:339)
  org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:170)
  org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:39)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:900)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:89)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:79)
  org.checkerframework.common.basetype.BaseTypeValidator.isValid(BaseTypeValidator.java:69)
  org.checkerframework.common.basetype.BaseTypeVisitor.validateType(BaseTypeVisitor.java:3278)
  org.checkerframework.common.basetype.BaseTypeVisitor.validateTypeOf(BaseTypeVisitor.java:3258)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:836)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:864)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:141)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:568)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:333)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:294)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:962)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

### PR DESCRIPTION
**Pull request by smillst**
1.  `AnnotatedTypeFactory#typeVariablesFromUse` must substitute type parameters of the enclosing type, too.  This fixes #1431. 
2.  AnnotatedTypeVisitors must also visit enclosing types.  This fixes #724 by applying defaults to enclosing types.
3.  Correct how annotations on inner types are applied.

(1 caused a crash that required 2.  2 caused a crash that required 3.)

Downsteam test will pass once https://github.com/typetools/checker-framework-inference/pull/59 is merged.

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java [hunk 1]
```diff
@@ -129,7 +129,8 @@ public R visitDeclared(AnnotatedDeclaredType type, P p) {
             return visitedNodes.get(type);
         }
         visitedNodes.put(type, null);
-        R r = scan(type.getTypeArguments(), p);
+        R r = scan(type.getEnclosingType(), p);
```
Comment (smillst) [inline framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: I think checker-framework-inference is failing because of this change.

Comment (smillst) [reply framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: This isn't the only place that might pass a null to `scan`.  For example, the return type of an executable could be null.   That's why `scan` checks for null.

Comment (wmdietl) [reply framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: Wouldn't the return type be the void type? Why didn't CFI fail before this change then?

File: framework/src/org/checkerframework/framework/util/element/ElementAnnotationUtil.java [hunk 2]
```diff
@@ -360,7 +362,7 @@ static int getBoundIndexOffset(final List<? extends AnnotatedTypeMirror> upperBo
     static AnnotatedTypeMirror getTypeAtLocation(
             AnnotatedTypeMirror type, List<TypeAnnotationPosition.TypePathEntry> location) {
 
-        if (location.isEmpty()) {
+        if (location.isEmpty() && type.getKind() != TypeKind.DECLARED) {
```
[the remark this answers is not in the document]
Comment (smillst) [reply framework/src/org/checkerframework/framework/util/element/ElementAnnotationUtil.java]: (Done below.)

File: framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java (hunk 1 above)
Comment (wmdietl) [reply framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: Ok, I looked at the right `scan` now. I think it would be better to never scan null and we should eventually remove all those null checks in `scan`.

Comment (smillst) [reply framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: Right, not the return type, the receiver type. There wasn't a NPE before because `ConstantToVariable` overrides `visitExecutable`  https://github.com/typetools/checker-framework-inference/blob/master/src/checkers/inference/util/ConstantToVariableAnnotator.java#L39

Comment (smillst) [reply framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java]: I documented that `scan` might scan null (and add more documentation to AnnotatedTypeScanner) in  #1514 .

File: framework/src/org/checkerframework/framework/util/element/ElementAnnotationUtil.java [hunk 3]
```diff
@@ -360,7 +361,9 @@ static int getBoundIndexOffset(final List<? extends AnnotatedTypeMirror> upperBo
...
+            // The annotation on a declared type might apply to the enclosing type, so that case is
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/element/ElementAnnotationUtil.java]: How about: `An annotation with an empty type path on a declared type applies to the outermost enclosing type. This logic is handled together with non-empty type paths in getLocationTypeADT. For other kinds of types no work is required for an empty type path.`
