### PR TITLE
Treat inferred wildcards with typevar upper bounds as typevars.

### LINKED ISSUE #1867: crash: inferred value should not be missing annotations
```java
import java.util.List;

abstract class T {

  interface A {}

  interface B<X extends A> {
    List<? extends X> g();
  }

  abstract List<? extends B<? extends A>> h();

  void f() {
    for (B<? extends A> x : h()) {
      for (A y : x.g()) {}
    }
  }
}
```

```
$ ./checker-framework-2.4.0/checker/bin/javac -AprintErrorStack -processor Nullness Test.java 
...
error: Inferred value should not be missing annotations: ? extends X
  Compilation unit: /usr/local/google/home/cushon/Test.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:725)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.removePrimaryTypeVarApplyUpperBound(DefaultInferredTypesApplier.java:95)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.apply(DefaultInferredTypesApplier.java:73)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.applyInferredType(DefaultInferredTypesApplier.java:55)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.applyInferredAnnotations(GenericAnnotatedTypeFactory.java:1529)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1469)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1447)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1022)
  org.checkerframework.common.basetype.BaseTypeVisitor.validateTypeOf(BaseTypeVisitor.java:3497)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitEnhancedForLoop(BaseTypeVisitor.java:912)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitEnhancedForLoop(BaseTypeVisitor.java:162)
  com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1043)
...
error: Inferred value should not be missing annotations: ? extends X
  Compilation unit: /usr/local/google/home/cushon/Test.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:725)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.removePrimaryTypeVarApplyUpperBound(DefaultInferredTypesApplier.java:95)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.apply(DefaultInferredTypesApplier.java:73)
  org.checkerframework.framework.type.DefaultInferredTypesApplier.applyInferredType(DefaultInferredTypesApplier.java:55)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.applyInferredAnnotations(GenericAnnotatedTypeFactory.java:1529)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1469)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1447)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1022)
  org.checkerframework.common.basetype.BaseTypeVisitor.validateTypeOf(BaseTypeVisitor.java:3497)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitEnhancedForLoop(BaseTypeVisitor.java:912)
  org.checkerframework.checker.nullness.NullnessVisitor.visitEnhancedForLoop(NullnessVisitor.java:236)
  org.checkerframework.checker.nullness.NullnessVisitor.visitEnhancedForLoop(NullnessVisitor.java:54)
  com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1043)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1867

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/DefaultInferredTypesApplier.java [hunk 1]
```diff
@@ -61,9 +61,15 @@ private void apply(
             AnnotationMirror inferred,
             TypeMirror inferredTypeMirror,
             AnnotationMirror top) {
-
         AnnotationMirror primary = type.getAnnotationInHierarchy(top);
         if (inferred == null) {
+            if (inferredTypeMirror.getKind() == TypeKind.WILDCARD) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/DefaultInferredTypesApplier.java]: Would it make sense to move this input validation up to the public method `applyInferredType`?
Also there are two places further down that check whether `inferredTypeMirror.getKind() != TypeKind.TYPEVAR`; could that validation also be done once in the public method? Could you use a more specific subtype of TypeMirror?
If not, it would be good to document why these properties do not need to hold in the other locations.
