### PR TITLE
Print type parameters correctly for outer classes using -Ainfer=stubs

### LINKED ISSUE #3438: -Astubs doesn't write type arguments for outer class when inner class present
When using `-Ainfer=stubs`, creating stub files for classes with inner classes fails to include type arguments in the outer class. Consider this class
```java
public class GenericClass<T> {
    public class InnerClass {
        // Create error to force generation of stub file, ignore.
        Object o = null;
    }
}
```
I compiled it with,
```bash
$CHECKERFRAMEWORK/checker/bin/javac -processor NullnessChecker -Ainfer=stubs GenericClass.java
```
When I inspect the generated stub file, I see
```java
import org.checkerframework.checker.initialization.qual.Initialized;
import org.checkerframework.checker.nullness.qual.Nullable;

class GenericClass {

  class InnerClass {

    // fields:

    @Initialized @Nullable java.lang.Object o;

  }
}
```
Notice that `GenericClass` has no type parameter.

When I try to use this stub file, I get an error:
```bash
$CHECKERFRAMEWORK/checker/bin/javac -processor NullnessChecker -Astubs=build GenericClass.java
```
```
warning: StubParser: annotateTypeParameters: mismatched sizes:  typeParameters (size 0)=[];  typeArguments (size 1)=[T extends Object];  decl=class GenericClass {      class InnerClass {          @Initialized         @Nullable         java.lang.Object o;     } };  elt=GenericClass (class com.sun.tools.javac.code.Symbol$ClassSymbol).; for more details, run with -AstubDebug
GenericClass.java:4: error: [assignment.type.incompatible] incompatible types in assignment.
        Object o = null;
                   ^
  found   : null
  required: @Initialized @NonNull Object
1 error
1 warning
```

Output for
```bash
$CHECKERFRAMEWORK/checker/bin/javac -processor NullnessChecker -Ainfer=stubs GenericClass.java -version -verbose -AprintAllQualifiers
```
[javac_create_stubs_output.txt](https://github.com/typetools/checker-framework/files/4881794/javac_create_stubs_output.txt)

Output for
```bash
$CHECKERFRAMEWORK/checker/bin/javac -processor NullnessChecker -Astubs=build GenericClass.java -version -verbose -AprintAllQualifiers
```

[javac_use_stubs_output.txt](https://github.com/typetools/checker-framework/files/4881795/javac_use_stubs_output.txt)

### PR DESCRIPTION
**Pull request by kelloggm**
fixes #3438

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java [hunk 1]
```diff
@@ -450,6 +452,11 @@ private static boolean isInternalJDKAnnotation(String annotationName) {
     private static int printClassDefinitions(
             String basename, AClass aClass, PrintWriter printWriter) {
         String[] classNames = basename.split("\\$");
+        TypeElement innermostTypeElt = aClass.getTypeElement();
+        TypeElement[] typeElements = getTypeElementsForClasses(innermostTypeElt, classNames);
+        if (innermostTypeElt == null) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:457]: I would test `innermostTypeElt` before using it; that is, transpose the two statements.

File: framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java [hunk 2]
```diff
@@ -459,9 +466,15 @@ private static int printClassDefinitions(
             } else {
                 printWriter.print("class ");
             }
-            printWriter.print(formatAnnotations(aClass.getAnnotations()));
+            if (i == classNames.length - 1) {
+                // Only print class annotations on the innermost class, which corresponds to aClass.
+                // If there should be class annotations on another class, it will have its own stub
+                // file,
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:472]: Refill paragraph.

File: framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java [hunk 3]
```diff
@@ -472,6 +485,29 @@ private static int printClassDefinitions(
...
+     *
+     * @param innermostTypeElt the innermost type element: either an inner class or an outer class
+     *     without any inner classes that should be printed
+     * @param classNames the names of the containing classes, from outer to inner
+     * @return an array of TypeElements whose entry at a given index represents the type named at
+     *     that index in {@code classNames}
+     */
+    private static TypeElement @SameLen("#2") [] getTypeElementsForClasses(
+            TypeElement innermostTypeElt, String[] classNames) {
+        if (classNames.length == 1) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:499]: Nit: I wouldn't use the special case.  This isn't speed-critical code, and a special case gives rise to the possibility of error or incompatibilities.  I think the general case works, so this is not necessary for correctness.

File: framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java [hunk 4]
```diff
@@ -472,6 +485,29 @@ private static int printClassDefinitions(
...
+     * Constructs an array of TypeElements corresponding to the list of classes.
+     *
+     * @param innermostTypeElt the innermost type element: either an inner class or an outer class
+     *     without any inner classes that should be printed
+     * @param classNames the names of the containing classes, from outer to inner
+     * @return an array of TypeElements whose entry at a given index represents the type named at
+     *     that index in {@code classNames}
+     */
+    private static TypeElement @SameLen("#2") [] getTypeElementsForClasses(
+            TypeElement innermostTypeElt, String[] classNames) {
```
[the remark this answers is not in the document]
Comment (kelloggm) [reply framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:497]: We could, but I'd rather keep the array so that I can annotate the result as `@SameLen`, which expresses the actual contract.

**Comment by kelloggm** [comment]
@jwaataja thanks for noticing that I deleted my own test case :) I wrote one, wrote one solution that I didn't like, and then reset the repository and forgot to save the test case. It turned out that it wasn't passing, anyway, so I had to make a (minor) fix to the code.
