### PR TITLE
Correctly determine if a constructor has a receiver.

### LINKED ISSUE #3598: AsSuperVisitor: type is not an erased subtype of supertype
```java
import java.util.Optional;
import java.util.function.Function;

interface A extends B {}

interface B { 
  interface C {}
}

class D extends E implements A {}

class E<F extends E<F, G>, G extends E.J<F, G>> implements B { 
  abstract static class J<H extends E<H, I>, I extends J<H, I>> implements B.C {}
}

class K extends L {}

class L extends D {}

class X<P extends A> implements Function<P, Optional<P>> {

  @Override
  public Optional<P> apply(P protoT) {
    return Optional.empty();
  }

  static Function<K, Optional<K>> f(K k) {
    return new X<>(k);
  }

  X(P p) {}
}
```

```
./checker/bin/javac -processor Nullness X.java
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: A
  superType: AccessControlPolicy
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: X.java
  Last visited tree at line 31 column 5:
      return new X<>(a);
  Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
        at org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:165)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:349)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
        at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:96)
        at org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:78)
        at org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:110)
        at org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:138)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:504)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:43)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #3598.

### CODE REVIEW

**Comment by smillst** [comment]
I'm working on a more complete fix for getting the annotated type of a receiver, implicit receiver, `this`, and `Outer.this`, but it won't be ready for the Sept. release.  We should go ahead a merge this, so the crash is fixed in the Sept. release.

File: framework/tests/all-systems/Issue3598.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import java.util.function.Function;
+
+class Issue3598 {
+
+    static class DClass extends EClass {}
+
+    static class EClass<F> {}
+
+    // Must be Function, can't use interface defined in this class.
```
Comment (mernst) [inline framework/tests/all-systems/Issue3598.java:9]: @smillst There isn't an interface defined in this class.  Could you clarify this comment?
