### PR TITLE
Annotate Optional.orElse with @PolyNull (fixes #1000)

### LINKED ISSUE #1000: Could `Optional.orElse(T)` be annotated with `PolyNull`
Hello,
The method [`Optional.orElse(T)`][1] is currently tagged as follow.

     public @Nullable T orElse(@Nullable T other)

Which means the following code does not type check:

```Java
import java.util.Optional;

class Test {
  String foo() {
    Optional<String> opt = Optional.of("abc");
    return opt.orElse("");
  }
}
```
And instead, give the following error:
```
$ javacheck -version
javac 1.8.0-jsr308-2.1.6
$ javacheck -processor NullnessChecker Test.java
Test.java:6: error: [return.type.incompatible] incompatible types in return.
    return opt.orElse("");
                     ^
  found   : @Initialized @Nullable String
  required: @Initialized @NonNull String
1 error
```

Would not it make sense to change the annotation to use [`PolyNull`][2] instead?

[1]: https://github.com/typetools/checker-framework/blob/checker-framework-2.1.6/checker/jdk/nullness/src/java/util/Optional.java#L253
[2]: http://types.cs.washington.edu/checker-framework/current/api/org/checkerframework/checker/nullness/qual/PolyNull.html

### PR DESCRIPTION
**Pull request by mernst**
This makes the annotated JDK more precise.
The changeset also restricts the type argument to `Optional` to be `@NonNull`, and it removes redundant, conflicting nullness annotations from the lock-annotated JDK.

### CODE REVIEW

File: checker/jdk/nullness/src/java/util/Optional.java [hunk 1]
```diff
@@ -48,7 +49,7 @@
  *
  * @since 1.8
  */
-public final class Optional<T> {
+public final class Optional<@NonNull T extends @NonNull Object> {
```
Comment (wmdietl) [inline checker/jdk/nullness/src/java/util/Optional.java]: The @NonNull on T is not necessary.
