### PR TITLE
Work around to ensure the type argument inference return correct Java type (Fixes #1084)

### LINKED ISSUE #1084: Type is not an erased subtype of supertype: annotated type variable
Stacktrace similar to #1046, but not fixed by the fix for it.
Take:

```
import org.checkerframework.checker.nullness.qual.*;

@SuppressWarnings("nullness")
class MyOpt<T extends Object> {
  static <S> MyOpt<@NonNull S> empty() { return null; }
  static <S> MyOpt<S> of(S p) { return null; }
}

class Issue {
  MyOpt<Long> get() {
    return this.hashCode() > 0 ? MyOpt.of(5L) : MyOpt.empty();
  }
}
```

Run the Nullness Checker on this an you'll get:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Object
  superType: Long
  Compilation unit: Crash.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:725)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.AtmLubVisitor.lubTypeArgument(AtmLubVisitor.java:213)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:198)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:33)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:65)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:638)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitConditionalExpression(TypeFromExpressionVisitor.java:106)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitConditionalExpression(TypeFromExpressionVisitor.java:45)
  com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1245)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
```

The key difference is the `@NonNull` in `empty`. The code doesn't crash without that annotation.

I looked at the types in TypeFromExpression and see:
`TypeFromExpr: this.hashCode() > 0 ? MyOpt.of(5L) : MyOpt.empty() truetype: @Initialized @NonNull MyOpt<@Initialized @NonNull Long> falsetype: @Initialized @NonNull MyOpt<@Initialized @NonNull Object> alub: MyOpt<java.lang.Long>`

Note that the type for the false branch is wrong, using `Object` as type argument instead of `Long`.
So the problem might actually not be with asSuper, but with the type that gets inferred for `empty`.

### PR DESCRIPTION
**Pull request by smillst**

### CODE REVIEW

File: framework/src/org/checkerframework/framework/util/typeinference/solver/EqualitiesSolver.java [hunk 1]
```diff
@@ -381,6 +381,12 @@ public InferredValue mergeConstraints(
         dirty |= updateTargetsWithPartiallyInferredType(equalities, constraintMap, typeFactory);
         inferred = findEqualTarget(equalities, tops);
 
+        if (inferred == null && equalities.types.size() == 1) {
+            // Still could not find an inferred type in all hierarchies, so just use what type is
+            // known.
+            AnnotatedTypeMirror type = equalities.types.keySet().iterator().next();
+            return new InferredType(type);
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/util/typeinference/solver/EqualitiesSolver.java]: How about just setting inferred here and using the single return statement that follows.
