### PR TITLE
If a type has an uninferred type arg, only check primary annotations

### LINKED ISSUE #3032: false positive with method reference
Extracted from https://github.com/typetools/checker-framework/issues/3001#issuecomment-570026011

See test case below, which was extracted from [nomulus](https://github.com/google/nomulus).  Output with the `UnitsChecker`:

```
$ ~/git-repos/checker-framework/checker/bin/javac -processor org.checkerframework.checker.units.UnitsChecker InvoicingPipeline.java
InvoicingPipeline.java:78: error: [argument.type.incompatible] incompatible types in argument.
              .via(BillingEvent::getInvoiceGroupingKey));
                  ^
  found   : @UnknownUnits MapElements</*INFERENCE FAILED for:*/ ? extends @UnknownUnits Object, /*INFERENCE FAILED for:*/ ? extends @UnknownUnits Object>
  required: @UnknownUnits PTransform<? extends @UnknownUnits PInput super @UnitsBottom PCollection<@UnknownUnits BillingEvent>, /*INFERENCE FAILED for:*/ @UnknownUnits ? extends @UnknownUnits POutput>
1 error
```

This has nothing to do with the units checker; the same error comes up with the object construction checker as well.  Test input:

```java
import java.io.Serializable;
public class InvoicingPipeline {
  public static class PCollection<T> implements PValue {
    public <OutputT extends POutput> OutputT apply(
        String name, PTransform<? super PCollection<T>, OutputT> t) {
      return null;
    }
  }
  public abstract static class PTransform<InputT extends PInput, OutputT extends POutput> {
    public abstract void expand(InputT input);
  }
  static interface PInput {}
  static interface POutput {}
  interface PValue extends PInput, POutput {}
  static class BillingEvent {
    InvoiceGroupingKey getInvoiceGroupingKey() {
      return null;
    }
  }
  public static class MapElements<InputT, OutputT>
      extends PTransform<PCollection<? extends InputT>, PCollection<OutputT>> {
    public static <OutputT> MapElements<?, OutputT> into(final TypeDescriptor<OutputT> outputType) {
      return null;
    }
    public static <InputT, OutputT> MapElements<InputT, OutputT> via(
        final ProcessFunction<InputT, OutputT> fn) {
      return null;
    }
    public void expand(PCollection<? extends InputT> input) {}
  }
  static class TypeDescriptor<T> {
    public static <T> TypeDescriptor<T> of(Class<T> type) {
      return null;
    }
  }
  static class InvoiceGroupingKey {}
  @FunctionalInterface
  public interface ProcessFunction<InputT, OutputT> extends Serializable {
    OutputT apply(InputT input) throws Exception;
  }
  private static class GenerateInvoiceRows
      extends PTransform<PCollection<BillingEvent>, PCollection<String>> {
    @Override
    public void expand(PCollection<BillingEvent> input) {
      input.apply(
          "Map to invoicing key",
          MapElements.into(TypeDescriptor.of(InvoiceGroupingKey.class))
              .via(BillingEvent::getInvoiceGroupingKey));
    }
  }
}
```

### PR DESCRIPTION
**Pull request by smillst**
This suppresses more warnings related to #979. 
This fixes #3032.

### CODE REVIEW

**Comment by kelloggm** [comment]
I think this is a much better solution than #3035. I'm closing that PR in favor of this one.

File: framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 1]
```diff
@@ -154,6 +154,25 @@ protected StructuralEqualityComparer createEqualityComparer() {
...
+            for (final AnnotationMirror top : qualifierHierarchy.getTopAnnotations()) {
+                AnnotationMirror subAnno = subtype.getAnnotationInHierarchy(top);
+                AnnotationMirror superAnno = supertype.getAnnotationInHierarchy(top);
+                if (subAnno != null
+                        && superAnno != null
+                        && !qualifierHierarchy.isSubtype(subAnno, superAnno)) {
+                    return false;
+                }
+            }
+            return true;
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: I'm wondering whether this is a bit too coarse-grained.
With this change, even if somewhere deep within a generic type there is an uninferred type argument, only the primary annotations are checked.
Let's take a type `@A M<@B C, @D ?>` where the second type argument is uninferred.
With this change, only `@A` is checked. Wouldn't it be better if also `@B` is checked?
The first type argument isn't affected by the failure to infer the second argument.

What happens if you remove lines 157--159 and 164--174 from the patch? Methods like `isContainedBy` already check for uninferred type arguments, so maybe only the check in `isSubtype` was missing?
Then you wouldn't even need the new `containsUninferredTypeArguments` method.

**Comment by smillst** [comment]
@wmdietl I was able to reduce the scope of this change a bit.  I'm going to go ahead and merge this.
