### PR TITLE
Correctly apply annotations from stub files to type parameters and wildcards

### LINKED ISSUE #824: "? super V" leads to unsatisfiable bounds
The interpretation of "? super V" is "? super V extends @NonNull Object". In the Guava Futures library, there are functions such as:

```java
static <I extends @Nullable Object, O extends @Nullable Object> ListenableFuture<O> transform(ListenableFuture<I> input, Function<? super I,? extends O> function);
```

This leads to the following code failing to type check:

```java
public static ListenableFuture</*@NullableType*/ String> nullableStringTransform(
    ListenableFuture</*@NullableType*/ String> input,
    Function</*@NullableType*/ String, /*@NullableType*/ String> f) {
  return Futures.transform(input, f);
}
```

This appears to be related to us defining annotations in astub files rather than main source code, it doesn't seem to be reproducible if I define equivalent interfaces inline. The error reported is:

```
  found   : @Initialized @NonNull Function<@Initialized @Nullable String, @Initialized @Nullable String>
  required: @Initialized @NonNull Function<? extends @Initialized @NonNull Object super @Initialized @Nullable String, ? extends @Initialized @Nullable String>
```

There is also a second problem. If I change the astub file by adding `@Nullable` to the `Function` parameter like so:

```java
static <I extends @Nullable Object, O extends @Nullable Object> ListenableFuture<O> transform(ListenableFuture<I> input, Function<@Nullable ? super I,? extends O> function);
```

I then cannot compile a non-null version of the method above:

```java
public static ListenableFuture<String> stringTransform(
    ListenableFuture<String> input,
    Function<String, String> f) {
  return Futures.transform(input, f);
}
```

That fails with the error:

```
  found   : @Initialized @NonNull Function<@Initialized @NonNull String, @Initialized @NonNull String>
  required: @Initialized @NonNull Function<@Nullable ? extends @Initialized @Nullable Object super @Initialized @Nullable String, ? extends @Initialized @NonNull String>
```

This seems to contradict the checker framework documentation which states that in `@Nullable X super T` `@Nullable` is an upper rather than a lower bound, and therefore should be substitutable with a non-null type.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #824 and #590.

### CODE REVIEW

File: checker/jtreg/nullness/issue824/Class1.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
+/*
+ * @test
+ * @summary Test case for Issue 824 https://github.com/typetools/checker-framework/issues/824
+ * @compile -XDrawDiagnostics -Xlint:unchecked Class1.java
+ * @compile -XDrawDiagnostics -Xlint:unchecked -processor org.checkerframework.checker.nullness.NullnessChecker -AprintErrorStack -Anomsgtext Class2.java -Astubs=Class1.astub
```
Comment (wmdietl) [inline checker/jtreg/nullness/issue824/Class1.java]: It would be nice to ensure that the correct errors are produced when the stub file is not given. I.e. have a copy of line 5 without the stub option and expected errors.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 2]
```diff
@@ -131,6 +131,7 @@
      * Annotation to added to every method and constructor in the stub file.
      */
     private final AnnotationMirror fromStubFile;
+    private List<AnnotatedTypeMirror> typeParameters = new ArrayList<>();
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: How about making the field final and calling clear() instead of allocating a new object on line 440?

Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Some javadoc for the purpose of the field would be great.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 3]
```diff
@@ -435,9 +437,10 @@ private void parse(
                 stubWarnIfNotFound("StubParser ignoring: " + elt);
             }
         }
+        typeParameters = new ArrayList<>();
     }
 
-    private void parseType(
+    private List<AnnotatedTypeMirror> parseType(
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: It would be good to document what the meaning of the returned ATM is.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 4]
```diff
@@ -845,8 +868,11 @@ private void annotateParameters(
             TypeParameter param = typeParameters.get(i);
             AnnotatedTypeVariable paramType = (AnnotatedTypeVariable) typeArguments.get(i);
 
-            annotate(paramType, param.getAnnotations());
-            if (param.getTypeBound() != null && param.getTypeBound().size() == 1) {
+            if (param.getTypeBound() == null || param.getTypeBound().size() != 1) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Is the `!= 1` case covering intersection and union types? Should it be `> 1`? Maybe add a comment why these don't need to be handled.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 5]
```diff
@@ -743,10 +746,30 @@ private void annotate(AnnotatedTypeMirror atype, Type typeDef) {
...
                 annotate(wildcardType.getSuperBound(), wildcardDef.getSuper());
+                annotate(wildcardType.getExtendsBound(), typeDef.getAnnotations());
+            } else {
+                annotate(atype, typeDef.getAnnotations());
+            }
+        } else if (atype.getKind() == TypeKind.TYPEVAR) {
+            //Add annotations from the declaration of the TypeVariable
+            AnnotatedTypeVariable typeVarUse = (AnnotatedTypeVariable) atype;
+            for (AnnotatedTypeMirror annotatedTypeMirror : typeParameters) {
+                if (annotatedTypeMirror.getKind() != TypeKind.TYPEVAR) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Why do we need to allow this case? Can't we make the type of `typeParameters` more specific and only allow AnnotatedTypeVariables?

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 6]
```diff
@@ -133,6 +133,12 @@
     private final AnnotationMirror fromStubFile;
 
     /**
+     * List of AnnotatedTypeMirrors for class or method type parameters that are in scope of the
+     * elements currently parsed.
+     */
+    private List<AnnotatedTypeVariable> typeParameters = new ArrayList<>();
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Making this final and using `clear` would reduce memory pressure.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 7]
```diff
@@ -435,9 +442,13 @@ private void parse(
                 stubWarnIfNotFound("StubParser ignoring: " + elt);
             }
         }
+        typeParameters = new ArrayList<>();
     }
 
-    private void parseType(
+    /**
+     * @return List of AnnotatedTypeMirrors of the type's type parameters
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: ATM -> ATV.
I assume all returned ATV will be declaration type variables, not use.

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 8]
```diff
@@ -506,9 +517,18 @@ private void parseType(
...
         }
 
-        annotateParameters(typeArguments, typeParameters);
+        annotateTypeParameters(typeArguments, typeParameters);
         annotateSupertypes(decl, type);
         putNew(atypes, elt, type);
+        List<AnnotatedTypeVariable> typeVariables = new ArrayList<>();
+        for (AnnotatedTypeMirror typeV : type.getTypeArguments()) {
+            if (typeV.getKind() != TypeKind.TYPEVAR) {
+                stubAlwaysWarn("Expected an AnnotatedTypeVariable but found " + typeV.getKind());
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Add typeV to error message to make easier to find?

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 9]
```diff
@@ -845,8 +880,11 @@ private void annotateParameters(
...
 
-            annotate(paramType, param.getAnnotations());
-            if (param.getTypeBound() != null && param.getTypeBound().size() == 1) {
+            if (param.getTypeBound() == null || param.getTypeBound().isEmpty()) {
+                // No bound so annotations are both lower and upper bounds
+                annotate(paramType, param.getAnnotations());
+            } else if (param.getTypeBound() != null && param.getTypeBound().size() == 1) {
+                annotate(paramType.getLowerBound(), param.getAnnotations());
                 annotate(paramType.getUpperBound(), param.getTypeBound().get(0));
             }
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: These cover cases of no bounds and exactly one bound. What about multiple bounds?

Comment (smillst) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Type variable declarations can only have extends bounds.

Comment (smillst) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Looking at the code, I'm not sure why TypeParameter#getTypeBounds returns a list.  Maybe for intersection types?

Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Yes, I guess it's for code like this:

````
class A<T extends @TA Iface1 & @TB Iface2>
````

It would be good to at least issue a warning if we see > 1 bounds.

Comment (smillst) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: I confirmed that there are > 1 bounds when the upperbound is an intersection.  I added a warning and I'm working on implementing intersection support.  (But not for this release.)
