### PR TITLE
KeyFor Checker: Convert annotations with parse errors to top for method invocations.

### LINKED ISSUE #6520: expression.unparsable accessing entrySet items after using record property accessor in Collectors.groupingBy
Following test case

```
class Test {

  private record Data(String value) {

  }

  Test(Collection<Data> data) {
    data.stream().collect(Collectors.groupingBy(Data::value))
        .entrySet().stream()
        .filter(entry -> entry.getValue().size() > 1)
        .forEach(entry -> {
          throw new IllegalArgumentException("Duplicate value " + entry.getKey());
        });
  }
}
```

fails compilation with java: [expression.unparsable] Expression invalid in dependent type annotation: [error for expression: data.stream().collect(java.util.stream.Collectors.groupingBy(Data::value)); error: Invalid 'Data::value' because class com.github.javaparser.ast.expr.MethodReferenceExpr is not a supported expression]

on line

```
        .filter(entry -> entry.getValue().size() > 1)
```

It is expected to compile without warnings

### PR DESCRIPTION
**Pull request by smillst**
In the KeyFor Checker only, this changes all qualifiers on the type of a method invocation expression, even qualifiers that are not primary annotations. This is unsound for qualifiers on type arguments or array elements on modifiable objects.

For example, if they type of some method called, `getList(...)`, is changed from `List<@KeyFor("a ? b : c") String>` to `List<@UnknownKeyFor String>`, then the returned list may have `@UnknownKeyFor` strings added.

```
List<String> l = getList(...);
l.add(randoString);
```
This is probably ok for the KeyFor Checker because most of the collections of keys are unmodifiable.  

This fixes #6520.

### CODE REVIEW

**Comment by mernst** [comment]
@smillst Could you fix the CI errors before I take a look?  Thanks.

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -221,4 +230,61 @@ boolean isMapPut(Node node) {
...
+     * Creates a {@code KeyForDependentTypesHelper}.
+     *
+     * @param factory annotated type factory
+     */
+    public KeyForDependentTypesHelper(AnnotatedTypeFactory factory) {
+      super(factory);
+    }
+
+    @Override
+    public void atMethodInvocation(
```
Comment (smillst) [inline checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java:257]: Document unsoundness.

File: framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java [hunk 2]
```diff
@@ -1198,6 +1205,35 @@ private ExpressionErrorCollector() {
...
+
+    /**
+     * Create ErrorAnnoReplacer
+     *
+     * @param qh qualifier hierarchy
+     */
+    private ErrorAnnoReplacer(QualifierHierarchy qh) {
+      super(
+          (AnnotatedTypeMirror type, Void aVoid) -> {
+            AnnotationMirrorSet newAnnos = new AnnotationMirrorSet();
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java:1222]: This does a lot of allocation.  I suggest first determining whether creating a new AnnotationMirrorSet is necessary, and then doing the work only if so.  This requires two passes over the set, but I think it's worth it given how often this will be called.

**Review by mernst — APPROVED** [review]

**Review by mernst — APPROVED** [review]
Thanks!
