### PR TITLE
 Handle NULL types in all possible positions. Fixes #1992.

### LINKED ISSUE #1992: AnnotatedTypeMirror classes aren't equal
This reproduces at head (82702ae4498f25afd21a351cd48b68f1fa7c6a4f).

```java
import java.util.List;
import java.util.function.Function;

class Test {

  interface A {}

  static class B<T extends A> {
    C a;
    T b;
  }

  static class C {
    Function<? super A, E> c;

    enum E {
      NONE
    }
  }

  boolean f(List<B<?>> x) {
    B<?> d = x.get(x.size() - 1);
    return d.a.c.apply(d.b) != C.E.NONE;
  }
}
```

```
./checker-framework/checker/bin/javac -processor Nullness -AprintErrorStack Test.java
error: AnnotatedTypeMirror classes aren't equal.
  type1 = AnnotatedNullType(  null )
  type2 = AnnotatedDeclaredType( A )
  visitHistory = VisitHistory( {Pair(? extends A, ? extends A)=[@org.checkerframework.checker.nullness.qual.UnknownKeyFor], Pair(A, Object)=[@org.checkerframework.checker.nullness.qual.UnknownKeyFor]} )
  Compilation unit: X.java
  Last visited tree at line 23 column 12:
      return d.a.c.apply(d.b) != C.E.NONE;
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:739)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:53)
  org.checkerframework.framework.type.StructuralEqualityComparer.defaultAction(StructuralEqualityComparer.java:56)
  org.checkerframework.framework.type.StructuralEqualityComparer.defaultAction(StructuralEqualityComparer.java:32)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitNull_Declared(AbstractAtmComboVisitor.java:363)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:498)
  org.checkerframework.framework.type.StructuralEqualityComparer.areEqual(StructuralEqualityComparer.java:75)
  org.checkerframework.framework.type.StructuralEqualityComparer.visitWildcard_Wildcard(StructuralEqualityComparer.java:441)
  org.checkerframework.framework.type.StructuralEqualityComparer.visitWildcard_Wildcard(StructuralEqualityComparer.java:32)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:716)
```

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -252,16 +252,13 @@ public StructuralEqualityComparer createEqualityComparer() {
...
-                                convertSpecialIntRangeToStandardIntRange(
-                                        type1.getAnnotationInHierarchy(UNKNOWNVAL)));
-                        type2.replaceAnnotation(
-                                convertSpecialIntRangeToStandardIntRange(
-                                        type2.getAnnotationInHierarchy(UNKNOWNVAL)));
-                        type1.replaceAnnotation(
-                                convertToUnknown(type1.getAnnotationInHierarchy(UNKNOWNVAL)));
-                        type2.replaceAnnotation(
-                                convertToUnknown(type2.getAnnotationInHierarchy(UNKNOWNVAL)));
+                        AnnotationMirror t1am = type1.getAnnotationInHierarchy(UNKNOWNVAL);
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java]: This is a left-over from an alternative fix. It makes the code a bit easier to read, but I can remove this again.

Comment (smillst) [reply framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java]: Does the TODO on line 258 still apply?

Comment (smillst) [reply framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java]: Oh, I was looking at an intermediate commit.  I would prefer this change just be pushed to master, since it is not related to this pull request.
