### PR TITLE
Handle code that is not in a method; fixes #3884

### LINKED ISSUE #3884: NullPointerException on lookupswitch inside lambda in interface field
This could probably be simplified further, but hopefully this is enough to go on:

```java
checker-framework-3.7.1 $ cat ~/code/Foo.java
interface Foo {
  String go(Kind kind);

  Foo FOO =
      kind -> {
        switch (kind) {
          case A:
            break;
        }
        return "";
      };

  enum Kind {
    A, B, C;
  }
}

checker-framework-3.7.1 $ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker ~/code/Foo.java
error: Error in AnnotatedTypeMirror.fromExpression(KeyForAnnotatedTypeFactory, switch#num0)
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /usr/local/google/home/cpovirk/code/Foo.java
  Last visited tree at line 1 column 1:
  interface Foo {
  Exception: java.lang.NullPointerException; java.lang.NullPointerException
        at org.checkerframework.framework.type.AnnotatedTypeFactory.declarationFromElement(AnnotatedTypeFactory.java:2896)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getEnclosingClassOrMethod(AnnotatedTypeFactory.java:1755)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getSelfType(AnnotatedTypeFactory.java:1715)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getImplicitReceiverType(AnnotatedTypeFactory.java:1689)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitIdentifier(TypeFromExpressionVisitor.java:176)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitIdentifier(TypeFromExpressionVisitor.java:70)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2252)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
        at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:40)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1290)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1025)
        at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:224)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitLocalVariable(CFAbstractTransfer.java:672)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitLocalVariable(CFAbstractTransfer.java:94)
        at org.checkerframework.dataflow.cfg.node.LocalVariableNode.accept(LocalVariableNode.java:80)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:338)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:390)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:130)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:107)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:109)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1341)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1267)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1686)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:343)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:322)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:916)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:503)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:496)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:947)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
... snip similar stack trace for NullnessAnnotatedTypeFactory ...
```

Apparently `getEnclosingClassOrMethod` is walking up the tree and not finding a class or method. I would have guessed that the interface would generate one, but maybe the `switch` table is considered to be outside that or something?

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -1757,7 +1760,7 @@ public AnnotatedNullType getAnnotatedNullType(Set<? extends AnnotationMirror> an
      * @param tree tree to whose inner most enclosing method or class is returned.
      * @return the inner most enclosing method or class tree of {@code tree}
      */
-    protected Tree getEnclosingClassOrMethod(Tree tree) {
+    protected @Nullable Tree getEnclosingClassOrMethod(Tree tree) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:1763]: Shouldn't all code be within at least a class? Can we specify more clearly when this method can return null?
In the long term, we should probably think about checking for enclosing lambda's and field declarations and how to handle such trees.

Comment (mernst) [reply framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:1763]: You are right.  Thanks for catching my goof.  I will rework this.

File: javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java [hunk 2]
```diff
@@ -432,8 +432,11 @@ public static boolean hasReceiver(Element element) {
             // A constructor can only have a receiver if the class it creates has an outer type.
             TypeMirror t = element.getEnclosingElement().asType();
             return TypesUtils.hasEnclosingType(t);
-        } else if (element.getKind().isField()) {
-            if (ElementUtils.isStatic(element)) {
+        } else if (element.getKind() == ElementKind.FIELD) {
+            if (ElementUtils.isStatic(element)
+                    // Artificial fields in interfaces are not marked as static, so check that
```
Comment (smillst) [inline javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java:437]: I'm didn't see any easy way to mark them as static, but this could cause problems else where in the code.

**Review by smillst — APPROVED** [review]
I figured out the underlying problem and fixed.
