### PR TITLE
Make `Map.keySet()` handle multiple arguments to `@KeyFor` (fixes #2358)

### LINKED ISSUE #2358: Make `Map.keySet()` handle multiple argments to `@KeyFor`
Currently, the return type of `Map.keySet()` is `Set<@KeyFor("this")>`, with `this` appropriately viewpoint-adapted.
However, the keys should be `"this"` **and** all the keys on the receiver's key type.

A test case appears at `checker/tests/nullness/KeyForMultiple.java`

The current output is

```
$ch/bin/javac -processor nullness KeyForMultiple.java
KeyForMultiple.java:21: error: [assignment.type.incompatible] incompatible types in assignment.
        Set<@KeyFor({"sharedBooks", "sharedCounts1"}) String> otherChars1 = sharedCounts1.keySet();
                                                                                                ^
  found   : Set<@KeyFor("sharedCounts1") String>
  required: Set<@KeyFor({"sharedBooks", "sharedCounts1"}) String>
KeyForMultiple.java:39: error: [assignment.type.incompatible] incompatible types in assignment.
        Set<@KeyFor({"sharedBooks", "sharedCounts2"}) String> otherChars2 = sharedCounts2.keySet();
                                                                                                ^
  found   : Set<@KeyFor("sharedCounts2") String>
  required: Set<@KeyFor({"sharedBooks", "sharedCounts2"}) String>
2 errors
```

(This seems to be the same as issue #414, but that issue was closed as fixed, and the problem still exists.)

### PR DESCRIPTION
**Pull request by Gaoyan1999**
# Summary
Enhance @KeyFor propagation for Map.keySet() by modifying addComputedTypeAnnotations in KeyForAnnotatedTypeFactory.
# Problem
The element type of Set returned by Map.keySet() only carried @KeyFor for the current variable (e.g., "sharedCounts1") and did not inherit @KeyFor values from the Map’s key type argument (e.g., "sharedBooks").
```java
    Map<@KeyFor({"sharedBooks"}) String, Integer> sharedBooks = new HashMap<>();
    Map<@KeyFor({"sharedBooks"}) String, Integer> sharedCounts1 = new HashMap<>();
    Set<@KeyFor({"sharedBooks", "sharedCounts1"}) String> otherChars1 = sharedCounts1.keySet();
```

# Solution
Override visitMethodInvocation in KeyForPropagationTreeAnnotator. When the tree is a Map.keySet() call, read @KeyFor values from the receiver Map’s key type argument and from the current Set element type, merge the names, and update the keySet() return type’s element with the combined @KeyFor.
# Reference
https://github.com/typetools/checker-framework/issues/2358

### CODE REVIEW

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -237,6 +244,88 @@ protected DependentTypesHelper createDependentTypesHelper() {
...
+    // Handle keySet() method invocations: merge KeyFor annotations from Map receiver's type
+    // arguments into the return type's type arguments
+    if (tree instanceof MethodInvocationTree) {
+      MethodInvocationTree methodInvocation = (MethodInvocationTree) tree;
+      if (TreeUtils.isMethodInvocation(methodInvocation, mapKeySet, getProcessingEnv())) {
+        if (type.getKind() == TypeKind.DECLARED) {
+          AnnotatedDeclaredType keySetReturnType = (AnnotatedDeclaredType) type;
+          ExpressionTree receiver = TreeUtils.getReceiverTree(methodInvocation);
+          if (receiver != null) {
+            AnnotatedTypeMirror receiverType = getAnnotatedType(receiver);
```
Comment (smillst) [inline checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java]: This will recompute the type of the receiver which is potentially expensive.  Instead, if you move this code to `org.checkerframework.checker.nullness.KeyForTransfer#visitMethodInvocation` you can use the type of the receiver that dataflow stores in TransferInput.

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java [hunk 2]
```diff
@@ -237,6 +244,88 @@ protected DependentTypesHelper createDependentTypesHelper() {
...
+    // Add existing KeyFor values from the Set's element type
+    if (setElementKeyFor != null) {
+      List<String> setKeyForValues =
+          AnnotationUtils.getElementValueArray(setElementKeyFor, keyForValueElement, String.class);
+      mergedKeyForValues.addAll(setKeyForValues);
+    }
+
+    // Create a new KeyFor annotation with merged values
+    if (!mergedKeyForValues.isEmpty()) {
+      AnnotationMirror mergedKeyFor = createKeyForAnnotationMirrorWithValue(mergedKeyForValues);
```
Comment (smillst) [inline checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java]: This `mergedKeyFor` is equivalent to the greatest lower bound of `setElementKeyFor` and `mapKeyKeyFor` so you could use `org.checkerframework.framework.type.QualifierHierarchy#greatestLowerBoundQualifiers` instead.

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java (hunk 1 above)
Comment (Gaoyan1999) [reply checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java]: Thanks for the suggestion.

I’ve spent the past few days trying your idea in `KeyForTransfer`, but it didn’t work as expected.

My approach was to update the `ResultValue` inside `KeyForTransfer#visitMethodInvocation`.

Here is the pseudocode:

```java
if (isMapKeySet(node)) {
  AnnotatedDeclaredType receiverDeclaredType =
      (AnnotatedDeclaredType) factory.getReceiverType(node.getTree());
  AnnotatedDeclaredType keySetReturnType =
      (AnnotatedDeclaredType) factory.getAnnotatedType(node.getTree());

  // Before: see test case KeyForMultiple.java#m1()
  // receiverDeclaredType: Map<@KeyFor({"sharedBooks"}) String, Integer>
  // keySetReturnType: Set<@KeyFor({"sharedCounts1"}) String>

  mergeKeyForFromMapReceiverIntoKeySetReturn(receiverDeclaredType, keySetReturnType, factory);

  // After merge:
  // keySetReturnType: Set<@KeyFor({"sharedBooks","sharedCounts1"}) String>

  KeyForValue newValue = analysis.createAbstractValue(keySetReturnType);
  result.setResultValue(newValue);
}

```

The merge itself works correctly.

The problem appears in `analysis.createAbstractValue` (and I’m not sure this is the right API to use, maybe there is a correct way to fix it in KeyforTransfer).

`createAbstractValue` only processes annotations on the **primary type**, but after merging, the updated `@KeyFor` information is in `keySetReturnType.typeArgs`. That data never makes it into the `ResultValue`. This case also seems different from the existing `ContainsKey` case.

I also reviewed the checking logic to understand when the transfer result is used.

In `commonAssignmentCheck`, it calls `addComputedTypeAnnotations`, and the transfer result is consumed in `iUseFlow`:

```java
if (iUseFlow) {
  Value inferred = getInferredValueFor(tree);
  if (inferred != null) {
    applyInferredAnnotations(type, inferred);
  }
}

```

However, `applyInferredAnnotations` only handles the **top-level** type — it does not propagate annotations into the generic argument (`String` inside `Set<...>`). Its parameters also don’t include that information, so it cannot pass it through.

**My current solution**

I moved this logic into `KeyForPropagationTreeAnnotator#visitMethodInvocation`, and it works there.

There’s still some duplicated computation, but it seems better than overriding `addComputedTypeAnnotations` directly.

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java (hunk 2 above)
Comment (Gaoyan1999) [reply checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java]: I've used it, and make this function be public.

**Comment by Gaoyan1999** [comment]
Hi @smillst, I’ve addressed the comments and left a note about an issue I ran into. I’d appreciate it if you could take a look.

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java (hunk 1 above)
Comment (smillst) [reply checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java]: > However, `applyInferredAnnotations` only handles the **top-level** type — it does not propagate annotations into the generic argument (`String` inside `Set<...>`). Its parameters also don’t include that information, so it cannot pass it through.

Good point.  My suggestion will not work.

> **My current solution**
> 
> I moved this logic into `KeyForPropagationTreeAnnotator#visitMethodInvocation`, and it works there.
> 
> There’s still some duplicated computation, but it seems better than overriding `addComputedTypeAnnotations` directly.

I agree this is a good solution!

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagationTreeAnnotator.java [hunk 3]
```diff
@@ -102,4 +109,98 @@ public Void visitNewClass(NewClassTree tree, AnnotatedTypeMirror type) {
...
+  @Override
+  public Void visitMethodInvocation(MethodInvocationTree tree, AnnotatedTypeMirror type) {
+    if (isCallToKeyset(tree) && type.getKind() == TypeKind.DECLARED) {
+      AnnotatedDeclaredType keySetReturnType = (AnnotatedDeclaredType) type;
+
+      // Get the receiver type
+      AnnotatedTypeMirror receiverType = atypeFactory.getReceiverType(tree);
+      if (receiverType != null
+          && receiverType.getKind() == TypeKind.DECLARED
+          && !keySetReturnType.getTypeArguments().isEmpty()) {
```
Comment (mernst) [inline checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagationTreeAnnotator.java]: If this is a call to `keySet()`, how could the type arguments be empty?  (Because of raw types??  In that case, please add a comment.)  Would it be better to write an assertion rather than putting a test in the `if`?

The same comment about test vs. assertion applies to `getKind() == DECLARED` immediately above.

**Review by mernst — COMMENTED** [review]
This is very nice.  Thank you!

**Review by mernst — APPROVED** [review]

File: checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagationTreeAnnotator.java (hunk 3 above)
Comment (Gaoyan1999) [reply checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagationTreeAnnotator.java]: Thx, You’re right. There’s no need to check this here. This condition is unnecessary, and I found @smillst has removed it.

**Comment by Gaoyan1999** [comment]
Could someone rerun the pipeline? Thanks in advance.
