### PR TITLE
Unskip tests that required different JDK annotations (Fixes #3149)

### LINKED ISSUE #3149: Crashing invocation of Objects.requiresNonNullElse is permitted
The following code type-checks but should not:
```
    // This should fail typechecks, because it fails at run time.
    System.err.println((Object) requireNonNullElse(null, null));
```

A test case appears in `checker/tests/nullness/ObjectsRequireNonNullElse.java`.

### PR DESCRIPTION
**Pull request by smillst**
This includes changes in https://github.com/typetools/checker-framework/pull/3173. Merge that first.
Fixes #3149.

~~Merge https://github.com/typetools/jdk/pull/36 first.~~

### CODE REVIEW

File: checker/tests/nullness/ObjectsRequireNonNullElse.java [hunk 1]
```diff
@@ -1,4 +1,5 @@
 // Test case for https://tinyurl.com/cfissue/3056 and https://tinyurl.com/cfissue/3149 .
+// Test case for https://tinyurl.com/cfissue/3149 .
```
Comment (wmdietl) [inline checker/tests/nullness/ObjectsRequireNonNullElse.java:2]: The line above already mentions 3149.
