### PR TITLE
Handle while true (Fixes #3249)

### LINKED ISSUE #1727: Initialization problem in while true loop
Testcase(please remove txt file extension after download):

[Bug.java.txt](https://github.com/typetools/checker-framework/files/1592568/Bug.java.txt)
```java
class B {

}

public class Bug {

    private B foo() {
        // Default type for local variable b is @UnknownInitialization @Nullable
        B b;

        while (true) {
            B op = getB();
            if (op == null) {
                b = new B();
                break;
            } else {
                b = op;
                break;
            }
        }

        return b;
    }

     private B getB() {return new B();}
}
```

Command I used:
`javac -processor nullness testinput/typecheck/Bug.java -version -verbose -AprintErrorStack -AprintAllQualifiers`

Console Output:
```
javac 1.8.0-jsr308-2.2.2
[parsing started RegularFileObject[testinput/typecheck/Bug.java]]
[parsing completed 17ms]
[search path for source files: /home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[search path for class files: /home/mier/jsr308/checker-framework/checker/bin-devel/../jdk/annotated,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar,/home/mier/jdk1.8.0_73/jre/lib/resources.jar,/home/mier/jdk1.8.0_73/jre/lib/rt.jar,/home/mier/jdk1.8.0_73/jre/lib/sunrsasign.jar,/home/mier/jdk1.8.0_73/jre/lib/jsse.jar,/home/mier/jdk1.8.0_73/jre/lib/jce.jar,/home/mier/jdk1.8.0_73/jre/lib/charsets.jar,/home/mier/jdk1.8.0_73/jre/lib/jfr.jar,/home/mier/jdk1.8.0_73/jre/classes,/home/mier/jdk1.8.0_73/jre/lib/ext/sunpkcs11.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunjce_provider.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/localedata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/zipfs.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/cldrdata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/dnsns.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunec.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jfxrt.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/nashorn.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jaccess.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Object.class)]]
Round 1:
	input files: {B, Bug}
	annotations: []
	last round: false
Processor org.checkerframework.checker.nullness.NullnessChecker matches [] and returns false.
[search path for source files: /home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[search path for class files: /home/mier/jsr308/checker-framework/checker/bin-devel/../jdk/annotated,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar,/home/mier/jdk1.8.0_73/jre/lib/resources.jar,/home/mier/jdk1.8.0_73/jre/lib/rt.jar,/home/mier/jdk1.8.0_73/jre/lib/sunrsasign.jar,/home/mier/jdk1.8.0_73/jre/lib/jsse.jar,/home/mier/jdk1.8.0_73/jre/lib/jce.jar,/home/mier/jdk1.8.0_73/jre/lib/charsets.jar,/home/mier/jdk1.8.0_73/jre/lib/jfr.jar,/home/mier/jdk1.8.0_73/jre/classes,/home/mier/jdk1.8.0_73/jre/lib/ext/sunpkcs11.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunjce_provider.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/localedata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/zipfs.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/cldrdata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/dnsns.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunec.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jfxrt.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/nashorn.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jaccess.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Object.class)]]
Round 2:
	input files: {}
	annotations: []
	last round: true
[search path for source files: /home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[search path for class files: /home/mier/jsr308/checker-framework/checker/bin-devel/../jdk/annotated,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar,/home/mier/jdk1.8.0_73/jre/lib/resources.jar,/home/mier/jdk1.8.0_73/jre/lib/rt.jar,/home/mier/jdk1.8.0_73/jre/lib/sunrsasign.jar,/home/mier/jdk1.8.0_73/jre/lib/jsse.jar,/home/mier/jdk1.8.0_73/jre/lib/jce.jar,/home/mier/jdk1.8.0_73/jre/lib/charsets.jar,/home/mier/jdk1.8.0_73/jre/lib/jfr.jar,/home/mier/jdk1.8.0_73/jre/classes,/home/mier/jdk1.8.0_73/jre/lib/ext/sunpkcs11.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunjce_provider.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/localedata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/zipfs.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/cldrdata.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/dnsns.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/sunec.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jfxrt.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/nashorn.jar,/home/mier/jdk1.8.0_73/jre/lib/ext/jaccess.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../javacutil/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../stubparser/stubparser.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/scene-lib/bin,/home/mier/jsr308/checker-framework/checker/bin-devel/../../../annotation-tools/annotation-file-utilities/annotation-file-utilities.jar,/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/checker-qual.jar,.,./bin,./build,/home/mier/Downloads/weka-3-8-1/mysql-connector-java-5.0.8/mysql-connector-java-5.0.8-bin.jar]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Object.class)]]
[checking B]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/io/Serializable.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/AutoCloseable.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/FromByteCode.class]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/Retention.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/RetentionPolicy.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/Target.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/ElementType.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/SubtypeOf.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/FromStubFile.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/KeyFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/UnknownKeyFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/KeyForBottom.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/TargetLocations.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/TypeUseLocation.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/DefaultFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/ImplicitFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/LiteralKind.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/Map.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/PolyAll.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/PolymorphicQualifier.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/PolyKeyFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build/org/checkerframework/dataflow/qual/Pure.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build/org/checkerframework/dataflow/qual/SideEffectFree.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build/org/checkerframework/dataflow/qual/Deterministic.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build/org/checkerframework/dataflow/qual/TerminatesExecution.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/Unqualified.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/Map$Entry.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/Covariant.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Class.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/EnsuresNonNullIf.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/ConditionalPostconditionAnnotation.class]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Class$AnnotationData.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Class$MethodArray.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Class$ReflectionData.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Class$Atomic.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Class$EnclosingMethodInfo.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/reflect/AnnotatedElement.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/reflect/Type.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/lang/reflect/GenericDeclaration.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/String.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/LTLengthOf.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/LTEqLengthOf.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/IndexFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/IndexOrHigh.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/LengthOf.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/index/qual/IndexOrLow.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/common/value/qual/ArrayLenRange.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/common/value/qual/MinLen.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/reflect/Method.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/SuppressWarnings.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/NoSuchMethodException.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/SecurityException.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/reflect/Constructor.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Character.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Character$CharacterCache.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Character$UnicodeScript.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Character$UnicodeBlock.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Character$Subset.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Comparable.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/CharSequence.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Enum.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/initialization/qual/UnknownInitialization.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/Raw.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/String$CaseInsensitiveComparator.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/System.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/UnsupportedOperationException.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Throwable.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/TimeZone.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/lang/Cloneable.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/logging/Logger.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/logging/Logger$SystemLoggerHelper.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/logging/Logger$LoggerBundle.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/ResourceBundle.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/logging/Filter.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/logging/LogRecord.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/logging/Level.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/logging/Handler.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$CharPropertyNames.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BnMS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BnM.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Bound.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$NotBehindS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$NotBehind.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BehindS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Behind.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Neg.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Pos.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Conditional.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$First.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$CIBackRef.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BackRef.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$LazyLoop.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Loop.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Prolog.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$GroupTail.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$GroupRef.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$GroupHead.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Branch.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BranchConn.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$GroupCurly.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Curly.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Ques.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$UnixDot.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Dot.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$All.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceUS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceIS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceU.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceI.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Slice.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SliceNode.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/regex/Pattern$HorizWS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/regex/Pattern$VertWS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Ctype.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Utype.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Category.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Script.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Block.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SingleU.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SingleI.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Single.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$SingleS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BmpCharProperty.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$CharProperty.class)]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/java/util/regex/Pattern$LineEnding.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$UnixDollar.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Dollar.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$LastMatch.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$UnixCaret.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Caret.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$End.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Begin.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$StartS.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Start.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$LastNode.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$Node.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$BitClass.class)]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/regex/Pattern$TreeInfo.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/initialization/qual/Initialized.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/initialization/qual/UnderInitialization.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/initialization/qual/NotOnlyInitialized.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/initialization/qual/FBCBottom.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/NonNull.class]]
[loading ZipFileIndexFileObject[/home/mier/jdk1.8.0_73/lib/ct.sym(META-INF/sym/rt.jar/javax/lang/model/type/TypeKind.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/DefaultInUncheckedCodeFor.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/Nullable.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/PolyNull.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/MonotonicNonNull.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../framework/build/org/checkerframework/framework/qual/MonotonicQualifier.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/NonRaw.class]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../checker/build/org/checkerframework/checker/nullness/qual/PolyRaw.class]]
[loading ZipFileIndexFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../dist/jdk8.jar(java/util/Collection.class)]]
[loading RegularFileObject[/home/mier/jsr308/checker-framework/checker/bin-devel/../../dataflow/build/org/checkerframework/dataflow/qual/Pure$Kind.class]]
[wrote RegularFileObject[testinput/typecheck/B.class]]
[checking Bug]
testinput/typecheck/Bug.java:22: error: [return.type.incompatible] incompatible types in return.
        return b;
               ^
  found   : @UnknownInitialization @Nullable B
  required: @Initialized @NonNull B
[total 1149ms]
1 error
```

Expected: no errors
Actual: return type incompatible on line 22.

Reasoning: `while(true)` loop is guaranteed to be executed and both branches(if&else) initializes b to be a `@NonNull` value. So at line 22, `b`'s type should be `@Initialized @NonNull`.

### LINKED ISSUE #3249: CFG for `while (true)`
The CFG generator should treat `true` specially when used as a `while` condition.

Consider the following class:

```
public class WhileTrueInitialization {

  private final double field;

  WhileTrueInitialization() {
    double local;
    while (true) {
      local = 1;
      break;
    }
    field = local;
  }
}
```

Running
```
javacheck -g WhileTrueInitialization.java -processor nullness
```
yields
```
WhileTrueInitialization.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
    field = local;
            ^
  found   : @UnknownInitialization @NonNull double
  required: @Initialized @NonNull double
1 error
```

The problem is apparent from viewing the control flow graph:  `while (true)` is treated like any other `while` construct in that there is a branch that skips the entire body.  That is not possible when the condition is `true`, so the CFG should not include that branch.

This is a duplicate of #1727, but with a smaller test case.

### PR DESCRIPTION
**Pull request by d367wang**
This PR fixes both issue https://github.com/typetools/checker-framework/issues/3249 and issue https://github.com/typetools/checker-framework/issues/1727, by adapting the CFG in the following way:

If the loop condition is checked to be a constant true (according to the same logic in **javac** flow analysis), then the loop condition does not have an else-branch, i.e. the block holding the loop condition is directly followed by the one holding the loop entry, instead of followed by a conditional block.

Fixes #1727 and Fixes #3249`

### CODE REVIEW

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java [hunk 1]
```diff
@@ -4913,15 +4915,30 @@ public Node visitWhileLoop(WhileLoopTree tree, Void p) {
             // Condition
             addLabelForNextNode(conditionStart);
             assert tree.getCondition() != null;
+            // Determine whether loop condition is a constant true, according to the compiler logic.
```
Comment (smillst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:4918]: `true` is a literal not a constant. So this should say `Determine whether loop condition is the boolean literal "true",`.   You've used `constant` instead of `literal` in other places in this pull request.  Please change all uses.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java [hunk 2]
```diff
@@ -4985,6 +5002,35 @@ public Node visitOther(Tree tree, Void p) {
         }
     }
 
+    /**
+     * Determine whether loop condition {@link JCTree} is a constant true, according to the compiler
```
Comment (smillst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:5006]: This method works for any tree, even if that tree is not a loop condition.  We might find uses for this method outside of this class, would you please move it to `TreeUtils` and rename it to `isLiteralTrue`.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java (hunk 1 above)
Comment (mernst) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:4918]: More generally, a literal appears in source code, and a constant is an expression that can be evaluated at compile time.  So, `true` is both a literal and a constant.  `4 > 3` is a constant.

Using these terms consistently will help to make the code easier to read.  Thanks!

(I haven't read the code to determine whether it is checking for the literal `true` or the constant `true`.)

Comment (wmdietl) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:4918]: @smillst This PR correctly uses constant. The compiler handles "!false" and "6 > 4" as being the compile-time constant true.

@d367wang Please add the following test case:

```java
    Issue3249() {
        double local;
        while (6 > 4) {
            local = 1;
            break;
        }
        field = local;
    }
```

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java (hunk 2 above)
Comment (wmdietl) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:5006]: Moving to `TreeUtils` sounds good. As name I would use `isExpressionConstantTrue` or `isExprConstTrue`, or the current `isCondConstTrue`.

**Comment by wmdietl** [comment]
> FYI, when a pull request fixes an issue, then the pull request description should say `fixes #XXXX` or `fixes #XXXX and fixes #XXXX`. That way those issues will be closed when the pull request is merge. You could use one of [the other ways](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). I've updated this pull request description.

What do you mean here? I renamed this issue 7 days ago an don't see a further edit.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java (hunk 2 above)
Comment (smillst) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java:5006]: The Javadoc should say `is a compile-time constant true` or as the JLS uses `a condition expression has the constant value true`.  (I clearly misunderstood the term `constant true`, other might, too.)

**Comment by smillst** [comment]
@wmdietl, you changed the title of the issue.  I updated the pull request description which is the first comment.  If you add `fixes #XXXX` in the title, it doesn't actually link the issue, which is why you had to manually link it later.  Though if you just have `fixes #XXXX` in the title, it will still close the issue when it is merged because it is in the git commit message.

**Comment by wmdietl** [comment]
> @wmdietl, you changed the title of the issue.

Here do you mean "pull request" instead of "issue"?

You're pointing out that even though the first sentence of the PR description is `This PR fixes both issue #3249 and issue #1727` you added the last sentence `Fixes #1727 and Fixes #3249` to actually also convince GitHub to link the issues.
