### PR TITLE
Call hasFieldInvariantAnnotation instead of checking annotations.

### LINKED ISSUE #1347: Initialization Checker confused by delegating constructors and generic fields
The following test case:

```java
class Test<T> {
    T t;

    Test(T t) {
        this(t, 0);
    }

    Test(T t, int i) {
        this.t = t;
    }
}
```

produces the following error:

```
error: [initialization.fields.uninitialized] the constructor does not initialize fields: t
    Test(T t) {
    ^
```

If the field is of a specific type rather than `T`, the checker is happy.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1347

### CODE REVIEW

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -170,7 +170,22 @@ protected boolean isInitializationAnnotation(AnnotationMirror anno) {
      * @param field field that might have invariant annotation
      * @return whether or not field has the invariant annotation
      */
-    protected abstract boolean hasFieldInvariantAnnotation(VariableTree field);
+    protected boolean hasFieldInvariantAnnotation(VariableTree field) {
```
Comment (wmdietl) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: I would suggest making this method `final`. So far this signature was the extension point and subclasses could implement this method. Now these implementation would stop working, because they should override the newly introduced abstract method below.
By making the method `final` we break such subclasses, which seems nicer than silently failing.
Do you agree?

File: checker/tests/nullness/init/Issue1347.java [hunk 2]
```diff
@@ -0,0 +1,23 @@
+// Issue1347 case for Issue 1347.
```
Comment (wmdietl) [inline checker/tests/nullness/init/Issue1347.java]: Adapt header.

File: checker/tests/nullness/init/Issue1347.java [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    Issue1347(T t) {
+        this(t, 0);
+    }
+
+    Issue1347(T t, int i) {
+        this.t = t;
+        this.t2 = t;
+        this.o = new Object();
+    }
+    //:: error: (initialization.fields.uninitialized)
```
Comment (wmdietl) [inline checker/tests/nullness/init/Issue1347.java]: Nit: add empty line before this.

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java (hunk 1 above)
Comment (wmdietl) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: At the moment it isn't clear how to choose between these two methods and which one to override.
Adding final will clarify which one to override.
Maybe adding a comment to this method can clarify that it's just a convenience method for the other one.
