### PR TITLE
Restore ability to use unannotated stub file to override annotations in bytecode

### LINKED ISSUE #3597: Handling of annotation defaulting in stubs between 3.4.0 and 3.4.1
Prior to `3.4.0`, a stub file without annotations could be used to override annotations present in the corresponding classpath dependency (in the example below, the stub file for `p.B#f` has an implicitly non-null return type, which overrides the nullable type in the source file).

Was this change deliberate? The most likely culprit I see is https://github.com/typetools/checker-framework/commit/3ce0ab57300439da3646cdf5b93408440a048a2b. The repro doesn't use `-Ainfer`, and passing `-AmergeStubsWithSource` has no effect. If this change was deliberate, is there a way to restore the previous behaviour?

```
=== stubs/p.astub
package p;

import org.checkerframework.checker.nullness.qual.Nullable;

class B {
  Object f();
}
=== p/B.java
package p;

import org.checkerframework.checker.nullness.qual.Nullable;

class B {
  @Nullable
  Object f() {
    return new Object();
  }
}
=== p/A.java
package p;

class A {
  void f() {
    System.err.println(new B().f().toString());
  }
}
```

Compiling with `p.B` on the classpath, and with its corresponding stub, produces a diagnostic with `3.4.1` but not with `3.4.0`:

```
./checker-framework-3.4.0/checker/bin/javac p/B.java
./checker-framework-3.4.0/checker/bin/javac -Astubs=stubs -processor Nullness -sourcepath : -cp . p/A.java 
./checker-framework-3.4.1/checker/bin/javac -Astubs=stubs -processor Nullness -sourcepath : -cp . p/A.java 
p/A.java:5: error: [dereference.of.nullable] dereference of possibly-null reference new B().f()
    System.err.println(new B().f().toString());
                                ^
1 error
```

### PR DESCRIPTION
**Pull request by kelloggm**
Fixes #3597, which was an unintended side-effect of #2871. 

The actual fix is making the call to `clearAnnotations` in `StubParser#annotate` unconditional. Removing that code revealed some other problems, though, which this PR also contains fixes for.

The first other problem was that one of the tests for stub-based WPI (`UsesAnonymous.java`) failed with an extra `override.param.invalid` error. Examining the stub file made it clear that the generated stub was (mostly) correct, but that annotations that were actually present in the source code were being ignored (and it seems that the guard for the `clearAnnotations` call was a hack to avoid the problem), because they were printed as fully-qualified annotations. The stub parser, however, ignored any annotations that weren't imported directly. I therefore modified the stub parser to also read fully-qualified annotations in stub files.

That change fixed the initial failing test, but caused another WPI test case (`MultiDimensionalArrays.java`) to fail. Examining the generated stub files for that class made it clear that 3+ dimensional arrays were being printed incorrectly. The test hadn't failed before because the fully-qualified annotations weren't being used. I discovered that our belief about the order in which javac stores arrays was *wrong*; scene-lib and javac do actually store arrays in the same order. I'm not sure how we made that mistake. That allowed me to remove/simplify a bunch of code in `SceneToStubWriter`, though I did have to change the specification of `formatArrayTypeImpl`: it now only prints the "array" part of the type, and relies on `formatArrayType` to print the component type.

### CODE REVIEW

**Comment by kelloggm** [comment]
The test failure on this PR is interesting. It's not clear to me that the behavior in this PR is wrong, so I'm going to leave the failing test (for now) and instead describe the behavior here. I'd appreciate input from reviewers on which behavior is preferable.

The failing test is the one for #2059, which checks that `-AstubWarnIfNotFound` issues an error if (e.g.) `org.checkerframework.checker.nullness.qual.NonNull` (only) is imported in a stub file, but `org.checkerframework.checker.nullness.qual.Nullable` is used. The test fails because instead of issuing one error for an unknown annotation, it issues two errors: the expected one for the unknown annotation and another "type not found" error.

The latter, new error is caused by the change in this PR that attempts to treat an unimported annotation as a fully-qualified name. In this case, what that means is that the stub parser tries to load the class `Nullable` (in the default package). Since this doesn't exist as an annotation, the "type not found" error is issued.

The new error is therefore sensible given what the stub parser is trying to do, but I also think it's somewhat annoying for users. It would require a bit of refactoring to avoid the error, but it's not technically challenging. The question is whether we want to expose to the user that the stub parser tried (and failed) to load the default package's `@Nullable`, or not.

File: framework/src/main/java/org/checkerframework/framework/stub/StubParser.java [hunk 1]
```diff
@@ -1204,6 +1185,18 @@ private void annotate(AnnotatedTypeMirror type, List<AnnotationExpr> annotations
         }
         for (AnnotationExpr annotation : annotations) {
             AnnotationMirror annoMirror = getAnnotation(annotation, allStubAnnotations);
+            if (annoMirror == null) {
+                // If the annotation was not imported, then #getAllStubAnnotations does
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/stub/StubParser.java:1189]: This should be moved into `getAnnotation`.  Or is there some reason it can't be?

File: framework/src/main/java/org/checkerframework/framework/stub/StubParser.java [hunk 2]
```diff
@@ -1204,6 +1185,18 @@ private void annotate(AnnotatedTypeMirror type, List<AnnotationExpr> annotations
...
+                // not add it to the allStubAnnotations field. This code compensates for
+                // that deficiency by adding the annotation when it is encountered (i.e. here).
+                TypeElement annoTypeElt = getTypeElement(annotation.getNameAsString());
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/stub/StubParser.java:1192]: Just call `TypeElement classElement = elements.getTypeElement(typeName);` directly so that the more sensible warning will be issued below.  (Make sure to document why getTypeElement isn't called.)

File: framework/src/main/java/org/checkerframework/framework/stub/StubParser.java [hunk 3]
```diff
@@ -142,9 +142,8 @@
     private final Elements elements;
 
     /**
-     * The set of annotations found in the stub file. Keys are simple (unqualified) names. (This may
-     * be a problem in the unlikely occurrence that a type-checker supports two annotations with the
-     * same simple name.)
+     * The set of annotations found in the stub file. Keys are names. There are two entries for each
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/stub/StubParser.java:145]: In several places you deleted `simple`, instead, could you please change it to `both fully-qualified and simple names`.  That's important information.

File: framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java [hunk 4]
```diff
@@ -173,79 +173,29 @@ private static String formatAnnotations(Collection<? extends Annotation> annos)
      * @return the type formatted to be written to Java source code, followed by a space character
      */
     private static String formatArrayType(ATypeElement scenelibRep, ArrayType javacRep) {
-        int levels =
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:176]: The changes in this file should be merged to master in a separate commit. Can you open a separate PR with these changes?   I'll merge that PR first, so it's fine to leave these changes in this PR.  Also, can you add a test case for this that is unrelated to the other changes in this file?

Comment (kelloggm) [reply framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:176]: > The changes in this file should be merged to master in a separate commit

I agree that would be cleaner. The reason I didn't do it is:

> can you add a test case for this that is unrelated to the other changes in this file?

I cannot. The error here only affects the order of the parts of the type that are contained in the javac representation. With respect to arrays, that means that the only parts that are incorrectly ordered are the `[]`s - even the inferred annotations were ordered correctly before. The error only shows up when there are printable, but not inferred, annotations - which javac prints using fully-qualified names. So it's not possible to test these changes without the fix to the stub parser, but fixing the stub parser causes the existing tests to fail (because the algorithm is wrong).

Comment (kelloggm) [reply framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:176]: > even the inferred annotations were ordered correctly before

What I mean by this is that the `sceneLibRep` and its associated structures in the old code caused inferred annotations on the inner arrays types to be printed in the correct order, even though the array parts themselves (the `[]`s and any annotations in the javac types) were printed in the wrong order.

Comment (smillst) [reply framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:176]: Thanks for the explantation.  I understand why you can't add a test case (or rather why the existing test case didn't fail until the other bugs where fixed).   Could you still open a separate PR without a test case?  Then we can just merge that one first, then merge this one.

Comment (kelloggm) [reply framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java:176]: #3601 has these changes
