### PR TITLE
Correctly type `T.super`

### LINKED ISSUE #6060: Checker crash with latest sources (6/27/23)
Using the test branch of https://github.com/markro49/jOOQ/. Builds with 3.35.0 fine (there are many checker warnings).  
command:
(cd to jOOQ subdirectory)
mvn -V -B -e clean compile -Dcheckerframework.checkers=org.checkerframework.checker.signedness.SignednessChecker -Dcheckerframework.suppress="type.anno.before"

But if build with current checked sources (as of 6/27/23) gets following error:
[WARNING]   ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /home/markro/myjooq/jOOQ/src/main/java/org/jooq/ResultQuery.java
  Last visited tree at line 145 column 1:
  public interface ResultQuery<R extends Record> extends Fields, Query, Iterable<R>, Publisher<R> {
  Exception: org.checkerframework.javacutil.BugInCF: Enclosing type not found Iterable<T extends Object> ResultQuery<R extends Record>; org.checkerframework.javacutil.BugInCF: Enclosing type not found Iterable<T extends Object> ResultQuery<R extends Record>
    at org.checkerframework.framework.util.AnnotatedTypes.asOuterSuper(AnnotatedTypes.java:281)
    at org.checkerframework.framework.util.AnnotatedTypes.addTypeVarMappings(AnnotatedTypes.java:561)
    at org.checkerframework.framework.util.AnnotatedTypes.substituteTypeVariables(AnnotatedTypes.java:534)
    at org.checkerframework.framework.util.AnnotatedTypes.asMemberOfImpl(AnnotatedTypes.java:457)
    at org.checkerframework.framework.util.AnnotatedTypes.asMemberOf(AnnotatedTypes.java:386)
    at org.checkerframework.framework.util.AnnotatedTypes.asMemberOf(AnnotatedTypes.java:350)
    at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMemberSelect(TypeFromExpressionVisitor.java:268)
    at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMemberSelect(TypeFromExpressionVisitor.java:76)
    at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2458)
    at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:81)
    at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:40)
    at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1682)
    at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1352)
    at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:211)
    at org.checkerframework.framework.flow.CFAbstractTransfer.visitFieldAccess(CFAbstractTransfer.java:606)
    at org.checkerframework.common.value.ValueTransfer.visitFieldAccess(ValueTransfer.java:471)
    at org.checkerframework.common.value.ValueTransfer.visitFieldAccess(ValueTransfer.java:73)
    at org.checkerframework.dataflow.cfg.node.FieldAccessNode.accept(FieldAccessNode.java:85)
    at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:349)
    at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:377)
    at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:151)
    at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:105)
    at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:147)
    at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1544)
    at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1444)
    at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1933)
    at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:423)
    at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:536)
    at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:184)
    at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
    at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
    at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:86)
    at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1043)
    at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:558)
    at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:551)
    at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:188)
    at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
    at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
    at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
    at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
    at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
    at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
    at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
    at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
    at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
  Caused by: java.lang.Throwable
    at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:34)
    ... 45 more

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6060.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -2183,6 +2183,25 @@ public AnnotatedDeclaredType getEnclosingType(TypeElement typeElement, Tree tree
...
+  /**
+   * Returns the super {@link AnnotatedTypeMirror} of the enclosing type at the location of {@code
+   * tree} that is the same type as {@code typeElement}.
+   *
+   * @param typeElement type of the enclosing type to return
+   * @param tree location to use
+   * @return the super enclosing type at the location of {@code tree} that is the same type as
+   *     {@code typeElement}
+   */
+  public AnnotatedDeclaredType getEnclosingSuperType(TypeElement typeElement, Tree tree) {
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2195]: I find the contract of `getEnclosingSuperType` confusing.  I suggest changing it to just return the matching enclosing type (that's simpler and feels more like a logical unit), and having the client compute the supertype.

**Review by mernst — APPROVED** [review]
After addressing my comment, please merge.
