### PR TITLE
Correct subtyping for captured wildcard and uncaptured wildcard (Issue 870)

### LINKED ISSUE #870: Bogus error "lambda.param.type.incompatible"
The following program can be compiled by javac. If, however, the NullnessChecker is used, one gets 

_[9,33] error: [lambda.param.type.incompatible] incompatible parameter types in lambda expression._
```
package bar;

import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

public class Bar {
	public static Stream<? extends ZipEntry> entries(ZipFile zipFile) {
		return zipFile.stream().filter(entry -> !entry.isDirectory() && entry.getName().endsWith(".xml"));
	}
}
```

No error is issued if you write
`(ZipEntry entry) -> !entry.isDirectory() && ...`

### PR DESCRIPTION
**Pull request by smillst**
Fixes #870

### CODE REVIEW

File: javacutil/src/org/checkerframework/javacutil/InternalUtils.java [hunk 1]
```diff
@@ -247,6 +248,19 @@ public static boolean isCaptured(TypeVariable typeVar) {
     }
 
     /**
+     * If typeVar is a captured wildcard, returns that wildcard; otherwise returns null.
+     */
+    public static WildcardType getCapturedWildcard(TypeVariable typeVar) {
+        if (isCaptured(typeVar)) {
+            if (typeVar instanceof AnnotatedType) {
```
Comment (wmdietl) [inline javacutil/src/org/checkerframework/javacutil/InternalUtils.java]: I think you can simplify this and always call `unannotatedType`, it does no harm.
If you want to special case, the `instanceof` should be a Kind check.
