### PR TITLE
Ignore functional interfaces that are uninferred type arguments.

### LINKED ISSUE #2781: ClassCastException when using lambda with inferred generic destination type
With checker framework 2.10.1, I can produce an internal ClassCastException with a certain pattern of lambda plus generics code.  Here's the minimal sample:

```
import java.util.function.Function;
import java.util.stream.Stream;

public class LambaWrapped
{
    class Wrapper<T>
    {
        public Wrapper(T t) { }
    }

    public final Stream<Wrapper<Function<String, String>>> getStreamOfWrappedFunctions()
    {
        // This gives an error (inferred type in new)
        return Stream.<Wrapper<Function<String, String>>>of(new Wrapper<>(e -> e));
        // This is fine (explicit type in new)
        //return Stream.<Wrapper<Function<String, String>>>of(new Wrapper<Function<String, String>>(e -> e));
    }
}
```

I run with the NullnessChecker and I get the error below.  As noted in the example, the problem is the inferred type for the `new Wrapper<>` part.  The exception goes away if I specify the type in the new.  Glancing at the checker framework source, it looks like the code is assuming the lambda destination of a constructor parameter is a known declared type, but here that's not the case.   The Stream wrapper is not a distraction; this seems to be necessary to produce the error (because I guess the type inference becomes harder?).

I don't mind if I have to provide an annotation now for this case, but a compiler error with the real location would be better than the internal ClassCastException where I had to hunt to figure out the cause.

Error:

```
[ERROR] SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processingambaWrapped.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType
  Compilation unit: LambaWrapped.java
  Last visited tree at line 5 column 1:
  public class LambaWrapped
  Exception: java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType; Stack trace: org.checkerframework.framework.type.AnnotatedTypeFactory.getFunctionalInterfaceType(AnnotatedTypeFactory.java:3688)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getFnInterfaceFromTree(AnnotatedTypeFactory.java:3624)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getFnInterfaceFromTree(AnnotatedTypeFactory.java:3604)
  org.checkerframework.framework.type.TypeFromMemberVisitor.inferLambdaParamAnnotations(TypeFromMemberVisitor.java:95)
  org.checkerframework.framework.type.TypeFromMemberVisitor.visitVariable(TypeFromMemberVisitor.java:34)
  org.checkerframework.framework.type.TypeFromMemberVisitor.visitVariable(TypeFromMemberVisitor.java:22)
  com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:864)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromMember(TypeFromTree.java:50)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromMember(AnnotatedTypeFactory.java:1317)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromElement(AnnotatedTypeFactory.java:1238)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1046)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:312)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:93)
  org.checkerframework.dataflow.analysis.Analysis.init(Analysis.java:470)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:183)
  org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1248)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1180)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1515)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:320)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1009)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:522)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:515)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
  org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
  org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
  org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
  org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
  org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
  org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
  org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
  org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
  org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
  org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processing LambaWrapped.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType
  Compilation unit: LambaWrapped.java
  Last visited tree at line 5 column 1:
  public class LambaWrapped
  Exception: java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType; Stack trace: org.checkerframework.framework.type.AnnotatedTypeFactory.getFunctionalInterfaceType(AnnotatedTypeFactory.java:3688)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getFnInterfaceFromTree(AnnotatedTypeFactory.java:3624)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getFnInterfaceFromTree(AnnotatedTypeFactory.java:3604)
  org.checkerframework.framework.type.TypeFromMemberVisitor.inferLambdaParamAnnotations(TypeFromMemberVisitor.java:95)
  org.checkerframework.framework.type.TypeFromMemberVisitor.visitVariable(TypeFromMemberVisitor.java:34)
  org.checkerframework.framework.type.TypeFromMemberVisitor.visitVariable(TypeFromMemberVisitor.java:22)
  com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:864)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromMember(TypeFromTree.java:50)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromMember(AnnotatedTypeFactory.java:1317)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromElement(AnnotatedTypeFactory.java:1238)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1046)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:312)
  org.checkerframework.framework.flow.CFAbstractTransfer.initialStore(CFAbstractTransfer.java:93)
  org.checkerframework.dataflow.analysis.Analysis.init(Analysis.java:470)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:183)
  org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1248)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1180)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1515)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:320)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1009)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:522)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
  org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
  org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
  org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
  org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
  org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
  org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
  org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
  org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
  org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
  org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #2781.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -3596,9 +3596,8 @@ public AnnotatedTypeMirror widenToUpperBound(
      * @param tree member reference tree
      * @return the functional interface and the function type that this method reference targets
      */
-    public Pair<AnnotatedDeclaredType, AnnotatedExecutableType> getFnInterfaceFromTree(
-            MemberReferenceTree tree) {
-        return getFnInterfaceFromTree((Tree) tree);
+    public AnnotatedExecutableType getFunctionTypeTree(MemberReferenceTree tree) {
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: Update Javadoc.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 2]
```diff
@@ -3972,7 +3974,7 @@ protected void checkForAnnotatedJdk() {
             return;
         }
         checkedJDK = true;
-        if (checker.hasOption("nocheckjdk")) {
+        if (PluginUtil.getJreVersion() != 8 || checker.hasOption("nocheckjdk")) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java]: Shouldn't we check for the annotated JDK also on JDK 9+?

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 3]
```diff
@@ -3586,35 +3586,33 @@ public AnnotatedTypeMirror widenToUpperBound(
...
      * <p>The target type of a lambda is the type to which it is assigned or casted.
      *
      * @param tree lambda expression tree
-     * @return the functional interface and the function type that this lambda targets
+     * @return the function type that this lambda targets
      */
-    public Pair<AnnotatedDeclaredType, AnnotatedExecutableType> getFnInterfaceFromTree(
-            LambdaExpressionTree tree) {
-        return getFnInterfaceFromTree((Tree) tree);
+    public AnnotatedExecutableType getFunctionTypeTree(LambdaExpressionTree tree) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: The method name is a bit odd - it sounds like it would return a type. Other methods below use `FromTree` to make this clearer.
So how about `getFunctionTypeFromTree` for this one? Or `getFunctionTypeFromLambdaTree`?

Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: Similar comment for `getFunctionTypeTree` above.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 4]
```diff
@@ -3045,17 +3043,21 @@ protected boolean checkMethodReferenceAsOverride(
...
+                            memberReferenceTree,
+                            invocationType,
+                            enclosingType,
+                            invocationReturnType,
+                            functionType,
+                            (AnnotatedDeclaredType) functionalInterface,
+                            functionTypeReturnType);
+            return overrideChecker.checkOverride();
+        } else {
+            return !atypeFactory.ignoreUninferredTypeArguments;
```
[the remark this answers is not in the document]
Comment (smillst) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java]: I added a comment above.
