### PR TITLE
Fixes 759: Correct isSubtype for two wildcards

### LINKED ISSUE #759: Unexpected type error because missing capture conversion
Take:

```java
class IncompatibleTypes {
    void possibleValues(final Class<? extends Enum> enumType) {
        lowercase(enumType.getEnumConstants());
    }

    <T extends Enum<T>> void lowercase(final T... items) {
    }
}
```

Running any checker on this file will result in:

```
error: [argument.type.incompatible] incompatible types in argument.
        lowercase(enumType.getEnumConstants());
                                           ^
  found   : ?[ extends @UnknownKeyFor Enum super @KeyForBottom Void] @UnknownKeyFor []
  required: ?[ extends @UnknownKeyFor Enum super @KeyForBottom Void] @UnknownKeyFor []
```

The wildcard should be captured properly and no error is expected here.

(The following three checkers produce different errors which should also be investigated:

```
GUI Effect Checker (no imcompatible error, passed)
Lock Checker
	found : ? extends @GuardedBy @LockPossiblyHeld Enum @GuardedBy @LockPossiblyHeld []
	 required: @LockPossiblyHeld ? extends @GuardedBy @LockPossiblyHeld Enum @GuardedBy @LockPossiblyHeld []
Aliasing Checker
	found : ? extends @MaybeAliased @MaybeLeaked Enum @MaybeAliased @MaybeLeaked []
	required: @MaybeLeaked ? extends @MaybeAliased @MaybeLeaked Enum @MaybeAliased @MaybeLeaked []
```
)

### PR DESCRIPTION
**Pull request by smillst**
Fixes #759

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 1]
```diff
@@ -779,6 +780,27 @@ public Boolean visitWildcard_Typevar(AnnotatedWildcardType subtype, AnnotatedTyp
...
+            boolean subtypeHasAnno = subtype.getAnnotationInHierarchy(currentTop) != null;
+            boolean supertypeHasAnno = supertype.getAnnotationInHierarchy(currentTop) != null;
+
+            if (subtypeHasAnno && supertypeHasAnno) {
+                // if both have primary annotations then just check the primary annotations
+                // as the bounds are the same
+                return isPrimarySubtype(subtype, supertype, true);
+
+            } else if (!subtypeHasAnno && !supertypeHasAnno && areEqualInHierarchy(subtype, supertype, currentTop)) {
+                // two unannotated uses of the same wildcard are of the same type
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: I don't think this is true in general. Two different wildcard uses might bind to two different types.
I think a big TODO to correctly implement capture conversion would be good here.

Comment (smillst) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: I added a todo efac1071ba447084e5f66c76015fc5118059b831.
