### PR TITLE
Declaration annotations don't apply to array component types (Fixes #2888)

### LINKED ISSUE #2888: Aliased declaration annotations on array component types
According to https://checkerframework.org/manual/#declaration-annotations-moved we are moving aliased declaration annotations from the array component to the array type.

The following example:

```java
import com.sun.istack.internal.Nullable;

class Demo {
    @Nullable Object [] noa;
    
    @Nullable Object [] foo(@Nullable Object [] p) {
        noa = p;
        noa = foo(noa);
        noa = foo(p);
        return p;
    }
}
```

(`com.sun.istack.internal.Nullable` only exists in JDK 8; I didn't look which of our other aliases might exist in both 8 and 11.)

Should compile without any error, but raises six:

```
Demo.java:3: error: [initialization.fields.uninitialized] the constructor does not initialize fields: noa
class Demo {
^
Demo.java:8: error: [assignment.type.incompatible] incompatible types in assignment.
        noa = foo(noa);
                 ^
  found   : @Initialized @NonNull Object @Initialized @Nullable []
  required: @Initialized @Nullable Object @Initialized @NonNull []
Demo.java:8: error: [argument.type.incompatible] incompatible types in argument.
        noa = foo(noa);
                  ^
  found   : @Initialized @Nullable Object @Initialized @NonNull []
  required: @Initialized @NonNull Object @Initialized @Nullable []
Demo.java:9: error: [assignment.type.incompatible] incompatible types in assignment.
        noa = foo(p);
                 ^
  found   : @Initialized @NonNull Object @Initialized @Nullable []
  required: @Initialized @Nullable Object @Initialized @NonNull []
Demo.java:9: error: [argument.type.incompatible] incompatible types in argument.
        noa = foo(p);
                  ^
  found   : @Initialized @Nullable Object @Initialized @NonNull []
  required: @Initialized @NonNull Object @Initialized @Nullable []
Demo.java:10: error: [return.type.incompatible] incompatible types in return.
        return p;
               ^
  type of expression: @Initialized @Nullable Object @Initialized @NonNull []
  method return type: @Initialized @NonNull Object @Initialized @Nullable []
6 errors
```

The field `noa` is `@Nullable`, as that annotation is transferred from the component type to the array, so there shouldn't be an initialization warning.
All the calls and assignments are between syntactically equal types, so the errors are equally unexpected.

### PR DESCRIPTION
**Pull request by smillst**
This is already the case for elements, so this fix is for trees.

Fixes #2888.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 1]
```diff
@@ -30,11 +31,17 @@ public AnnotatedTypeMirror visitVariable(VariableTree node, AnnotatedTypeFactory
         AnnotatedTypeMirror result = TypeFromTree.fromTypeTree(f, node.getType());
 
         // Add primary annotations
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: Can you add a comment to the method, similar to what org.checkerframework.framework.util.element.ElementAnnotationUtil.addAnnotationsFromElement is doing?
Cross-references between the two places are probably also a good idea, to make sure they get updated together.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 2]
```diff
@@ -30,11 +31,17 @@ public AnnotatedTypeMirror visitVariable(VariableTree node, AnnotatedTypeFactory
...
-        List<? extends AnnotationTree> annos = node.getModifiers().getAnnotations();
-        if (annos != null && !annos.isEmpty()) {
-            List<AnnotationMirror> ams = TreeUtils.annotationsFromTypeAnnotationTrees(annos);
+        List<? extends AnnotationTree> annoTrees = node.getModifiers().getAnnotations();
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: This change only overrides `visitVariable`, wheras `addAnnotationsFromElement` is used in other contexts as well.
In particular, this probably doesn't do the right thing for method return types - they are not variables. Could you add a test to make sure?

File: javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java [hunk 3]
```diff
@@ -801,4 +801,26 @@ public static Name getElementValueClassName(
...
     }
+
+    /**
+     * Returns true if anno is a declaration annotation. In other words, returns true if anno cannot
+     * be written on uses of types.
+     *
+     * @param anno the AnnotationMirror
+     * @return true if anno is a declaration annotation.
+     */
+    public static boolean isDeclarationAnnotation(AnnotationMirror anno) {
```
Comment (wmdietl) [inline javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java]: Move this method next to `org.checkerframework.framework.util.AnnotatedTypes.isTypeAnnotation(AnnotationMirror, Class<?>)` or move that one here? It would be better to have them next to each other or have cross-references.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 4]
```diff
@@ -30,11 +31,17 @@ public AnnotatedTypeMirror visitVariable(VariableTree node, AnnotatedTypeFactory
...
+        if (annoTrees != null && !annoTrees.isEmpty()) {
+            List<AnnotationMirror> annos = TreeUtils.annotationsFromTypeAnnotationTrees(annoTrees);
             AnnotatedTypeMirror innerType = AnnotatedTypes.innerMostType(result);
-            innerType.addAnnotations(ams);
+            for (AnnotationMirror anno : annos) {
+                if (AnnotationUtils.isDeclarationAnnotation(anno)) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: Note how the logic in `addAnnotationsFromElement` is different: it only checks whether the annotation is part of the `org.checkerframework` package, not that it is a declaration annotation.
Shouldn't the logic between these two be the same?

Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: No, for elements, the annotation in `@Nullable Object []` is placed in a different location in the element depending on whether it is a type annotation or a declaration annotation. For elements, we only need to move our compatibility annotations to the component type.   

For trees, the annotation in `@Nullable Object []` is the same place in the tree no matter whether the annotation is a declaration annotation or a type annotation.  So we have to move it to the correct place.  

I did forget to treat our compatibility annotations as type annotations, so I've made that change.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java (hunk 2 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: There is a test, `foo2`.  Because annotations from methods are decoded using the element rather than the tree, this logic isn't needed there. (I added a comment in that method below.) All other places where a declaration annotation can be written are variables.  So this should be enough.

File: javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java (hunk 3 above)
Comment (smillst) [reply javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java]: `isTypeAnnotation` is never used and it uses a static cache.  How about I just deprecate that method?  I moved `hasTypeQualifierElementTypes` here.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java (hunk 1 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: Done below.

File: framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java [hunk 5]
```diff
@@ -84,8 +84,10 @@ public static void applyAllElementAnnotations(
      * @param type the type to annotate
      * @param annotations the annotations to add
      */
-    static void addAnnotationsFromElement(
+    static void addDeclarationAnnotationsFromElement(
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java]: I'll probably merge this change separately, but I think this rename should help clarify what's happening here.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java (hunk 2 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: Sounds good.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 6]
```diff
@@ -58,7 +72,8 @@ public AnnotatedTypeMirror visitMethod(MethodTree node, AnnotatedTypeFactory f)
 
         // TODO: Needed to visit parameter types, etc.
         // It would be nicer if this didn't decode the information from the Element and
-        // instead also used the Tree.
+        // instead also used the Tree. If this is implemented, then care needs to be taken to put
+        // any alias declaration annotations in the correct place for return types that are arrays.
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: A reference to `ElementAnnotationUtil.addDeclarationAnnotationsFromElement` might be good here.

File: framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java (hunk 5 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java]: Yes, this is a better name.

File: javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java (hunk 3 above)
Comment (wmdietl) [reply javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java]: Deprecating `isTypeAnnotation` sounds good and this is the more appropriate location for `hasTypeQualifierElementTypes`, so moving here is good.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java (hunk 6 above)
Comment (smillst) [reply framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java]: Done below.
