### PR TITLE
Be hostile to null values in AnnotationUtils; fixes #2820

### LINKED ISSUE #2820: AnnotationUtils.areSameByClass() should return false if its first argument is null.
Consider the following test case:
```
class NPETypeParams<T> {
    void method(T data) { }
}
```

I added the following code in `NullnessVisitor.java`: 

```
@Override
 public Void visitMethod(MethodTree node, Void p) {
     HashSet<AnnotationMirror> paramAnnotations = new HashSet<>();
     for (VariableTree param : node.getParameters()) {
         paramAnnotations.add(
                 atypeFactory
                         .getAnnotatedType(param)
                         .getAnnotationInHierarchy(atypeFactory.NULLABLE));
     }
     for (AnnotationMirror atm : paramAnnotations) {
         if (AnnotationUtils.areSame(atm, atypeFactory.NULLABLE)) { }
         if (AnnotationUtils.areSameByClass(atm, Nullable.class)) { }
     }
     return super.visitMethod(node, p);
 }
```

This causes a NPE at the call to `AnnotationUtils.areSameByClass`:

```
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing ./checker/tests/determinism/NPETypeParams.java
  Compilation unit: ./checker/tests/determinism/NPETypeParams.java
  Last visited tree at line 3 column 5:
      void method(T data) { }
  Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.javacutil.AnnotationUtils.annotationName(AnnotationUtils.java:74)
  org.checkerframework.javacutil.AnnotationUtils.areSameByName(AnnotationUtils.java:143)
  org.checkerframework.javacutil.AnnotationUtils.areSameByClass(AnnotationUtils.java:163)
  org.checkerframework.checker.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:224)
  org.checkerframework.checker.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:33)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:298)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:164)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:383)
  org.checkerframework.checker.initialization.InitializationVisitor.processClassTree(InitializationVisitor.java:295)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:336)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:164)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:522)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  com.sun.tools.javac.main.Main.compile(Main.java:302)
  com.sun.tools.javac.main.Main.compile(Main.java:162)
  com.sun.tools.javac.Main.compile(Main.java:57)
  com.sun.tools.javac.Main.main(Main.java:43)
1 error

```
Note that the call to `AnnotationUtils.areSame` does not cause an exception (it returns `false`). To be consistent, `AnnotationUtils.areSameByClass` should return `false` if its first argument is null.

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

File: javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java [hunk 1]
```diff
@@ -122,8 +122,11 @@ public static boolean areSameByName(
         if (a1 == a2) {
             return true;
         }
-        if (a1 == null || a2 == null) {
-            return false;
+        if (a1 == null) {
+            throw new BugInCF("Unexpected null first argument to areSameByName");
```
Comment (smillst) [inline javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java]: The parameters are still annotated with `@Nullable`.

Comment (wmdietl) [reply javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java]: Thanks for noticing! I adapted the two method signatures.
