### PR TITLE
Fix bad parsing of Long MIN_VALUE and Integer MIN_VALUE

### LINKED ISSUE #2830: Stub parser crashes when parsing Long.MIN_VALUE in annotation
Consider the following stub file (`Long.astub`):

```
import org.checkerframework.common.value.qual.IntVal;

package java.lang;

class Long {
     static @IntVal(-9223372036854775808L) Long MIN_VALUE;
}
```

Running the stub parser on this file or any other with an annotation whose value in `Long.MIN_VALUE` will crash the stub parser, because it tries to parse the long value as a unary minus and a long, instead of as a negative long. The same problem happens with `Integer.MIN_VALUE`. I haven't tested other minimum values, but I suspect they'll show the same behavior. I don't think this has anything to do with the fact that I tested it with the Value Checker - a quick reader of `StubParser.java` suggested that it would happen for any annotation whose value is the minimum value of an integral type.

Running this command line:
`javac -processor org.checkerframework.common.value.ValueChecker -Astubs=Long.astub *any Java files*`

produces a stack trace like this (tested on `master`):

```
error: SourceChecker.typeProcessingStart: unexpected Throwable (NumberFormatException); message: For input string: "9223372036854775808"
  Exception: java.lang.NumberFormatException: For input string: "9223372036854775808"; Stack trace: java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  java.base/java.lang.Long.parseLong(Long.java:696)
  java.base/java.lang.Long.parseLong(Long.java:817)
  com.github.javaparser.ast.expr.LongLiteralExpr.asLong(LongLiteralExpr.java:107)
  org.checkerframework.framework.stub.StubParser.getValueOfExpressionInAnnotation(StubParser.java:1591)
  org.checkerframework.framework.stub.StubParser.getValueOfExpressionInAnnotation(StubParser.java:1595)
  org.checkerframework.framework.stub.StubParser.handleExpr(StubParser.java:1740)
  org.checkerframework.framework.stub.StubParser.getAnnotation(StubParser.java:1545)
  org.checkerframework.framework.stub.StubParser.annotateDecl(StubParser.java:1139)
  org.checkerframework.framework.stub.StubParser.processField(StubParser.java:1062)
  org.checkerframework.framework.stub.StubParser.processTypeDecl(StubParser.java:562)
  org.checkerframework.framework.stub.StubParser.processCompilationUnit(StubParser.java:505)
  org.checkerframework.framework.stub.StubParser.processStubUnit(StubParser.java:488)
  org.checkerframework.framework.stub.StubParser.process(StubParser.java:482)
  org.checkerframework.framework.stub.StubParser.parse(StubParser.java:442)
  org.checkerframework.framework.stub.StubParser.parse(StubParser.java:394)
  org.checkerframework.framework.stub.StubTypes.parseStubFiles(StubTypes.java:221)
  org.checkerframework.framework.type.AnnotatedTypeFactory.parseStubFiles(AnnotatedTypeFactory.java:2982)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:246)
  org.checkerframework.common.value.ValueAnnotatedTypeFactory.<init>(ValueAnnotatedTypeFactory.java:182)
  org.checkerframework.common.value.ValueVisitor.createTypeFactory(ValueVisitor.java:143)
  org.checkerframework.common.value.ValueVisitor.createTypeFactory(ValueVisitor.java:36)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:220)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:209)
  org.checkerframework.common.value.ValueVisitor.<init>(ValueVisitor.java:39)
  org.checkerframework.common.value.ValueChecker.createSourceVisitor(ValueChecker.java:29)
  org.checkerframework.common.value.ValueChecker.createSourceVisitor(ValueChecker.java:21)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:904)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:99)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:860)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:157)
  jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
  jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
  jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
  jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
  jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
  jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
  jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
1 error
```

### PR DESCRIPTION
**Pull request by kelloggm**
fixes #2830

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/stub/StubParser.java [hunk 1]
```diff
@@ -1590,16 +1590,26 @@ private Object getValueOfExpressionInAnnotation(
...
-                        getValueOfExpressionInAnnotation(
-                                name, ((UnaryExpr) expr).getExpression(), valueKind);
-                if (value instanceof Number) {
-                    return convert((Number) value, valueKind, true);
-                }
+            switch (expr.toString()) {
+                    // Special-case the minimum values.  Separately parsing a "-" and a value
+                    // doesn't correctly handle the minimum values, because the absolute value of
+                    // the smallest member of an integral type is larger than the largest value.
+                case "-9223372036854775808L":
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/stub/StubParser.java]: Programmers can write the "L" in lowercase (even though they should not, since "l" looks like "1").
