### PR TITLE
Correct capture type variable method.

### LINKED ISSUE #4852: Crash in AnnotatedTypeFactory.doesNotContainOthers
This reproduces at head, after the fix for #4849

```java
import org.checkerframework.checker.nullness.qual.Nullable;

interface X<E extends X<E, B>, B extends X.Y<E, B>> {
  abstract class Y<E extends X<E, B>, B extends X.Y<E, B>> {}
}

class T {
  private void f(@Nullable X<?, ?> x) {
  }
}
```

```
$ javac -processor Nullness T.java
error: Not found: capture#220 extends X<capture#220, capture#99 extends Y<capture#220, capture#99>>,capture#99 extends Y<capture#220 extends X<capture#220, capture#99>, capture#99>
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: T.java
  Last visited tree at line 8 column 18:
    private void f(@Nullable X<?, ?> x) {
  Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:34)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.doesNotContainOthers(AnnotatedTypeFactory.java:4998)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.order(AnnotatedTypeFactory.java:4968)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.applyCaptureConversion(AnnotatedTypeFactory.java:4853)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.applyCaptureConversion(AnnotatedTypeFactory.java:4750)
        at org.checkerframework.common.basetype.BaseTypeValidator.visitParameterizedType(BaseTypeValidator.java:549)
        at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:334)
        at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:57)
        at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:955)
        at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:206)
        at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:194)
        at org.checkerframework.common.basetype.BaseTypeValidator.isValid(BaseTypeValidator.java:108)
        at org.checkerframework.common.basetype.BaseTypeVisitor.validateType(BaseTypeVisitor.java:4484)
        at org.checkerframework.common.basetype.BaseTypeVisitor.validateTypeOf(BaseTypeVisitor.java:4471)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:1463)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:190)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:974)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:356)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:190)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:203)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #4852.

### CODE REVIEW

**Review by mernst — APPROVED** [review]

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -5007,7 +5008,9 @@ private void copy(AnnotatedDeclaredType uncapturedType, AnnotatedDeclaredType ca
   @SuppressWarnings("interning:not.interned") // must be the same object from collection
   private AnnotatedTypeVariable doesNotContainOthers(
       Collection<? extends AnnotatedTypeVariable> collection) {
+    AnnotatedTypeVariable first = null;
     for (AnnotatedTypeVariable candidate : collection) {
+      first = candidate;
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:5013]: The current code returns the last, not first, candidate if no other matches.
I think this line should be `if (first == null) { first = candidate; }`.

**Review by mernst — CHANGES_REQUESTED** [review]

**Review by mernst — APPROVED** [review]
