### PR TITLE
Correctly check for the invariant annotation on type vars.

### LINKED ISSUE #1044: Uninitialized field check for type parameters with @Nullable bound
The following program:

```
public class TypeVarInit<V> {
  V f;

  public static void main(String[] args) {
    new TypeVarInit<String>().f.toString();
  }
}
```

compiles without error with the Nullness Checker.
When executing it, it results in a NullPointerException:

```
Exception in thread "main" java.lang.NullPointerException
	at TypeVarInit.main(TypeVarInit.java:5)
```

I would have expected:

```
TypeVarInit.java:1: error: [initialization.fields.uninitialized] the constructor does not initialize fields: f
public class TypeVarInit<V> {
       ^
1 error
```

Note that if the upper bound of `V` is changed from the implicit `@Nullable Object` to `@NonNull Object` we get the expected error:

```
TypeVarInit.java:1: error: [initialization.fields.uninitialized] the constructor does not initialize fields: f
public class TypeVarInit<V extends Object> {
       ^
1 error
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1044

### CODE REVIEW

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -159,6 +159,17 @@ protected boolean isInitializationAnnotation(AnnotationMirror anno) {
      */
     public abstract AnnotationMirror getFieldInvariantAnnotation();
 
+    /**
+     * Returns whether or not field has the invariant annotation.
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: Replacing `field` with `{@code field}` would make it clearer that the parameter is meant here.

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java [hunk 2]
```diff
@@ -159,6 +159,17 @@ protected boolean isInitializationAnnotation(AnnotationMirror anno) {
...
+     *
+     * <p>If the field is a type variable, this method return false if any possible instantiation of
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: return -> returns.

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java [hunk 3]
```diff
@@ -159,6 +159,17 @@ protected boolean isInitializationAnnotation(AnnotationMirror anno) {
...
+     * the type parameter could have the invariant annotation.
+     *
+     * @param field field that might have invariant annotation
+     * @return whether or not field has the invariant annotation
+     */
+    protected abstract boolean hasInvariantAnnotation(VariableTree field);
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: For symmetry with `getFieldInvariantAnnotation` how about naming this `hasFieldInvariantAnnotation`?

File: checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java [hunk 4]
```diff
@@ -507,8 +507,26 @@ public NullnessTypeAnnotator(InitializationAnnotatedTypeFactory<?, ?, ?, ?> atyp
 
     @Override
     public AnnotationMirror getFieldInvariantAnnotation() {
-        Elements elements = processingEnv.getElementUtils();
-        return AnnotationUtils.fromClass(elements, NonNull.class);
+        return NONNULL;
+    }
+
+    /**
+     * Returns whether or not field has the invariant annotation.
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: Same comments as on javadoc for the overridden method. Can the common parts be inherited to reduce duplication?

File: checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java [hunk 5]
```diff
@@ -507,8 +507,26 @@ public NullnessTypeAnnotator(InitializationAnnotatedTypeFactory<?, ?, ?, ?> atyp
...
+     *
+     * <p>If the field is a type variable, this method return false if any possible instantiation of
+     * the type parameter could have the invariant annotation. In other words, is the lower
+     * bound @NonNull?
+     *
+     * @param field field that might have invariant annotation
+     * @return whether or not field has the invariant annotation
+     */
+    @Override
+    protected boolean hasInvariantAnnotation(VariableTree field) {
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: Isn't this the implementation for all type systems? Instead of making the method abstract, how about using this implementation in the superclass? Then any future subclasses that need to change this behavior could still override the method.

File: checker/tests/nullness/init/Issue1044.java [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+
+        Inner7() {}
+    }
+
+    static class Inner8<@Nullable T extends @Nullable Object> {
+        T f;
+
+        Inner8() {}
+    }
+}
```
Comment (wmdietlGC) [inline checker/tests/nullness/init/Issue1044.java]: For completeness, isn't `Inner9<V extends Object>` missing?

File: checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java (hunk 5 above)
Comment (smillst) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: This is only the implementation for systems where the invariant annotation is bottom.  If it is some other annotation, then a type is has the invariant annotation if the lower bound annotation is a subtype of (or equal to) the invariant annotation and the upper bound is a super type of (or equal to) the annotation.  

By making this method abstract, it forces future subclasses to implement this method.

Comment (wmdietl) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: Adding some explanation like this to the javadoc would be useful.

File: checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java (hunk 4 above)
Comment (wmdietl) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: Would using `{@inheritDoc}` remove the duplication?

**Comment by smillst** [comment]
@wmdietl  I've lost track.  Is this ready to be merged or do you want to review it again?

File: checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java [hunk 7]
```diff
@@ -159,6 +159,17 @@ protected boolean isInitializationAnnotation(AnnotationMirror anno) {
      */
     public abstract AnnotationMirror getFieldInvariantAnnotation();
 
+    /**
+     * Returns whether or not {@code field} has the invariant annotation.
+     *
+     * <p>If the {@code field} is a type variable, this method returns false if any possible
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java]: Doesn't it return true if any possible instantiation of the type parameter could have the invariant annotation?
Adding a reference to the NullnessATF or an explanation of the check against the lower bound (if the invariant annotation is bottom) would also be helpful.
