### PR TITLE
Make SameLen annotations on parameters symmetric

### LINKED ISSUE #2434: SameLen property should be inferred on both variables
Consider the following code:
`import org.checkerframework.checker.index.qual.*;`
`class checkerr{`
`public void abc(String x, @SameLen("#1") String y){`
`}`
`public void err(@SameLen("#2") String a, String b){`
`abc(a,b);`
`}`
`}`
Run it by typing in the terminal:
javac -processor org.checkerframework.checker.index.IndexChecker checkerr.java

Output:
checkerr.java:6: error: [argument.type.incompatible] incompatible types in argument.
abc(a,b);
      ^
  found   : @SameLen("b") String
  required: @SameLen("a") String
1 error

Now if we annotate 'a' to be of the same length as of 'b', 'b' should automatically be inferred to have the same length as 'a', which clearly fails during above code.

### PR DESCRIPTION
**Pull request by kelloggm**
This pull request adds defaulting so that `@SameLen` annotations on formal that refer to other parameters are symmetric. For example, the declaration:
```java
void foo(int @SameLen("#2")[] a, int[] b)
```
is defaulted to
```java
void foo(int @SameLen("#2")[] a, int @SameLen("#1")[] b)
```

Fixes #2434.

@Maxi17 contributed significantly to this PR, and I would appreciate any comments he has on it.

### CODE REVIEW

**Comment by smillst** [comment]
FYI: GitHub allow co-authors: https://help.github.com/en/articles/creating-a-commit-with-multiple-authors.

**Comment by Maxi17** [comment]
It looks great. There is another issue related to this PR whose test case now passes: #2493.

File: checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java [hunk 1]
```diff
@@ -249,4 +256,62 @@ AnnotationMirror getAnno(Node n) {
...
+
+                // the SameLen value is in the list of params, so modify the type of
+                // that param in the store
+                AnnotationMirror newSameLen =
+                        aTypeFactory.createSameLen(
+                                Collections.singletonList(paramNames.get(index)));
+                Receiver otherParamRec = null;
+                try {
+                    otherParamRec =
+                            aTypeFactory.getReceiverFromJavaExpressionString(
```
Comment (smillst) [inline checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java]: You have the tree, so you should be able to get the receiver from that.  Try 
https://checkerframework.org/api/org/checkerframework/framework/util/FlowExpressionParseUtil.html#internalReprOfVariable-org.checkerframework.framework.type.AnnotatedTypeFactory-com.sun.source.tree.VariableTree-
