### PR TITLE
Fix crash in convertToRange() (Issue 1579)

### LINKED ISSUE #1579: Value Checker crash in RangeOrListOfValues.convertToRange
```
public class ValueCrash {
    public int[][] method(int[] array1, int[] array2) {
        // Required for crash
        for (int i = 0; i < array1.length; i++) {
        }  
        return new int[][]{ array1, array2 };
    }
}
```

Causes the following crash:
```
error: SourceChecker.typeProcess: unexpected Throwable (NoSuchElementException) while processing ValueCrash.java
  Compilation unit: ValueCrash.java
  Exception: java.util.NoSuchElementException; Stack trace: java.util.ArrayList$Itr.next(ArrayList.java:854)
  java.util.Collections.min(Collections.java:596)
  org.checkerframework.common.value.RangeOrListOfValues.convertToRange(RangeOrListOfValues.java:116)
  org.checkerframework.common.value.RangeOrListOfValues.add(RangeOrListOfValues.java:50)
  org.checkerframework.common.value.ValueAnnotatedTypeFactory$ValueTreeAnnotator.handleInitializers(ValueAnnotatedTypeFactory.java:1062)
  org.checkerframework.common.value.ValueAnnotatedTypeFactory$ValueTreeAnnotator.visitNewArray(ValueAnnotatedTypeFactory.java:961)
  org.checkerframework.common.value.ValueAnnotatedTypeFactory$ValueTreeAnnotator.visitNewArray(ValueAnnotatedTypeFactory.java:942)
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1579

### CODE REVIEW

File: framework/tests/value/Issue1579.java [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// Test case for Issue 1579
+// https://github.com/typetools/checker-framework/issues/1579
+
+public class Issue1579 {
+    public int[][] method(int[] array1, int[] array2) {
+        // Required for crash
+        for (int i = 0; i < array1.length; i++) {}
+
+        //TODO: This shouldn't issue an error.
```
Comment (smillst) [inline framework/tests/value/Issue1579.java]: I've got another branch that fixes this warning.  I'll post a pull request after this one is merged.
