### PR TITLE
Fix crash with additional argument constraints.

### LINKED ISSUE #6421: `StackOverflowError` related to JLS type inference
**Issue**

Running the latest version of the Checker Framework (head of `master` should be sufficient) appears to crash with a `StackOverflowError` related to type inference. A sample log is available [here](https://gist.github.com/jyoo980/24515d5850b8668b1451f5e2ac6420cf), and the steps to reproduce this error are below.

I have attempted to isolate the commit that introduced this error via `git bisect`, which yielded [this commit](https://github.com/typetools/checker-framework/commit/bc0b44db4f877674e1cf121d3825709af3e45ac5) as the most likely culprit.

**Steps to Reproduce**
```txt
# Clone the sample program that induces the error, and check out the branch with the local CF config changes
git clone git@github.com:jyoo980/fixture-monkey.git
cd fixture-monkey/
git checkout yoo/local-cf

# Ensure that your local copy of the Checker Framework is up-to-date and run it on the program
./gradlew -PcfLocal compileJava
```
**Expected output** 
The program should type-check (not cleanly, though) and the CF should not crash.

**Actual output** 
The CF crashes; the log is available [here](https://gist.github.com/jyoo980/24515d5850b8668b1451f5e2ac6420cf). Running the same program with the same command on a prior commit of the Checker Framework (I tested at the commit [immediately before](https://github.com/typetools/checker-framework/commit/ccec69e53393e3c6dbbbc7bc53f8ad60be6fd679)) does not crash.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6421 .

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/typeinference8/InvocationTypeInference.java [hunk 1]
```diff
@@ -524,6 +524,57 @@ private ConstraintSet createAdditionalArgConstraints(
     return c;
   }
 
+  /**
+   * Recursively search for method invocations and new class trees. If any are found, the additional
+   * variables, bounds, and constraints are returned. This method is called by {@link
+   * #createAdditionalArgConstraints(ExpressionTree, AbstractType, Theta)} when that method
+   * encounters a lambda. This method is different be because it does not add checked exception
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/typeinference8/InvocationTypeInference.java:531]: extra "be"

**Review by mernst — APPROVED** [review]
LGTM
