### PR TITLE
Avoid uninferred wildcard crash.

### LINKED ISSUE #1775: ArrayType must be represented by AnnotatedArrayType for un-inferred wildcard
Take this example, which is based on #419, and run a checker on it (tested with Regex and Nullness):

```java
class Failure {
    interface Box<A> {
        <B extends A> B get();
    }

    <S extends String> Box<S[]> getBox() {
	return null;
    }

    void m() {
        for (String s : getBox().get()) {}
    }
}
```

and you will get:

```
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing Issue419.java; message: ArrayType must be represented by AnnotatedArrayType
  Compilation unit: Issue419.java
  Exception: java.lang.AssertionError: ArrayType must be represented by AnnotatedArrayType; Stack trace: org.checkerframework.framework.flow.CFCFGBuilder$CFCFGTranslationPhaseOne.createEnhancedForLoopArrayVariable(CFCFGBuilder.java:148)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:3646)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:1440)
  com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1043)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3247)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1440)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1554)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1601)
  org.checkerframework.framework.flow.CFCFGBuilder.run(CFCFGBuilder.java:61)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1138)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1115)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1045)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1422)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:247)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:292)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:163)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

This is related to #979 and came up when working through problems with going to Java 9.
If nothing else, it should be another test case.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1775.

### CODE REVIEW

File: framework/src/org/checkerframework/framework/flow/CFCFGBuilder.java [hunk 1]
```diff
@@ -144,6 +148,16 @@ protected VariableTree createEnhancedForLoopArrayVariable(
             factory.shouldCache = false;
             AnnotatedTypeMirror annotatedArrayType = factory.getAnnotatedType(expression);
             factory.shouldCache = oldShouldCache;
+            if (annotatedArrayType.getKind() == TypeKind.WILDCARD) {
+                if (((AnnotatedWildcardType) annotatedArrayType).isUninferredTypeArgument()) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/flow/CFCFGBuilder.java]: How about simply doing `&&` of the two conditions?

File: framework/src/org/checkerframework/framework/flow/CFCFGBuilder.java [hunk 2]
```diff
@@ -144,6 +148,16 @@ protected VariableTree createEnhancedForLoopArrayVariable(
...
+                    TypeMirror type = TreeUtils.typeOf(expression);
+                    AnnotatedArrayType newArrayType =
+                            (AnnotatedArrayType)
+                                    AnnotatedTypeMirror.createType(type, factory, false);
+                    newArrayType.setComponentType(annotatedArrayType);
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/flow/CFCFGBuilder.java]: Should the array type get any annotations?
The Nullness Checker e.g. ensures that we only do an enhanced-for over a non-null array. What defaults get applied to this type?
