### PR TITLE
Decode annotations on enclosing types correctly

### LINKED ISSUE #3562: Inability to write annotations on the outer class portion of an inner class name
Dataflow seems to break with inner class types.
```java
import org.checkerframework.checker.tainting.qual.*;

public class C {
    void method(@Tainted Inner param) {
        @Tainted C. @Untainted Inner local = param;
    }

    class Inner {
    }
}
```
I get this error,
```
C.java:5: error: [type.invalid.conflicting.annos] invalid type: conflicting annotations [@Tainted, @Untainted] in type "@Tainted C.@Tainted @Untainted Inner"
        @Tainted C. @Untainted Inner local = param;
                                     ^
```
I would expect to instead get an invalid assignment error. It seems dataflow tries to replace the inner type but doesn't remove the old annotation.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #3562 .

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 1]
```diff
@@ -26,17 +30,52 @@
...
+        }
+
+        if (result.getKind() == TypeKind.DECLARED
+                &&
+                // Annotations on enum constants are not in the TypeMirror and always apply to the
+                // innermost type, so handle them in the else block.
+                elt.getKind() != ElementKind.ENUM_CONSTANT) {
+
+            // Decode the annotations from the type mirror because the annotations are already in
+            // the correct place for enclosing types. For example, @Tainted Outer.Inner and @Tainted
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java:56]: "For example" sounds like it is following up on a previous point, but I think here it might be introducing a new point.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 2]
```diff
@@ -26,17 +30,52 @@
...
+            // Inner. For both types @Tainted is stored in node.getModifiers(), but they apply to
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java:57]: Are they stored on the same node (that is, both are stored on the node for `Inner`)?  If so, I would say that.  If not, the fact that they apply to different types may not be so surprising.

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java [hunk 3]
```diff
@@ -26,17 +30,52 @@
...
+            AnnotatedTypes.applyAnnotationsFromDeclaredType(annotatedDeclaredType, declaredType);
+
+            // Handle declaration annotations
+            for (AnnotationMirror anno : modifierAnnos) {
+                if (AnnotationUtils.isDeclarationAnnotation(anno)) {
+                    // This does not treat Checker Framework compatqual annotations differently,
+                    // because it's not clear whether the annotation should apply to the outermost
+                    // enclosing type or the innermost.
+                    result.addAnnotation(anno);
+                } // If anno is not a declaration annotation, it should have been applied in the
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java:72]: I don't understand why this comment is attached to the curly brace rather than on a separate line.  Can you clarify why?

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 4]
```diff
@@ -1444,4 +1445,25 @@ public static void copyOnlyExplicitConstructorAnnotations(
             }
         }
     }
+
+    /**
+     * Add all the annotations in {@code declaredType} to {@code annotatedDeclaredType}.
```
Comment (mernst) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1450]: Maybe state explictly that this includes both declaration and type annotations.
