### PR TITLE
Correct Vector.copyInto code

### LINKED ISSUE #1522: Crash if method is called `copyInto` and has one parameter
Take

```java
class CopyInto {
  void copyInto(String p) {}
  void bar() {
    copyInto("Hi");
  }
}
```

and run any type system on the file to get the crash at the bottom of this issue.
In `framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java` the check is only for the method name and number of parameters, ignoring whether the receiver is really a subtype of Vector.
See BaseTypeVisitor#isVectorCopyInto and BaseTypeVisitor#typeCheckVectorCopyIntoArgument.

This situation should be handled more gracefully, but without adding a large performance overhead for each method invocation check.

```
error: SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processing CopyInto.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedArrayType
  Compilation unit: CopyInto.java
  Exception: java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedArrayType; Stack trace: org.checkerframework.common.basetype.BaseTypeVisitor.typeCheckVectorCopyIntoArgument(BaseTypeVisitor.java:1165)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:965)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:573)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:338)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:299)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:962)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:495)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
error: SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processing CopyInto.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedArrayType
  Compilation unit: CopyInto.java
  Exception: java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedArrayType; Stack trace: org.checkerframework.common.basetype.BaseTypeVisitor.typeCheckVectorCopyIntoArgument(BaseTypeVisitor.java:1165)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:965)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:294)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:573)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:378)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:267)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:1)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:338)
  org.checkerframework.checker.initialization.InitializationVisitor.processClassTree(InitializationVisitor.java:320)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:299)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:1)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:962)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
2 errors
```

### PR DESCRIPTION
**Pull request by smillst**
Don't crash when a method is named `copyInto`, but isn't `Vector#copyInto` or a method that overrides it.  Fixes #1522.

Fixing the above caused an "AsSuper" crash in the case where the Java type of the component  argument isn't a super type of Vector's type argument.  (See line 16 in  checker/tests/nullness/Issue1522.java for an example.) The BaseTypeVisitor now issues a `vector.copyinto.type.incompatible` error in that case.  It could alternatively issue no warning or a warning only if the primary annotations are not in the correct relationship.

### CODE REVIEW

File: checker/tests/nullness/Issue1522.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        v.copyInto(stringArray);
+    }
+
+    void copyVectorErrors(Vector<@Nullable String> v, Integer[] intArray, String[] stringArray) {
+        //:: error: (vector.copyinto.type.incompatible)
+        v.copyInto(stringArray);
+    }
+
+    void copyStackErrors(
+            SubClassVector<@Nullable String> v, Integer[] intArray, String[] stringArray) {
```
Comment (wmdietl) [inline checker/tests/nullness/Issue1522.java]: Does the case where both the vector type argument and the array component type are `@Nullable String` work?

File: framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 2]
```diff
@@ -179,6 +179,9 @@
     /** An instance of the {@link ContractsUtils} helper class. */
     protected final ContractsUtils contractsUtils;
 
+    /** The element for java.util.Vector#copyInto. */
+    private final ExecutableElement vectorCopyInto;
```
Comment (wmdietl) [inline framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java]: How about either moving field `vectorType` up here or this field down? I think it would be nice if they are next to each other.

File: framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 3]
```diff
@@ -193,6 +196,9 @@ public BaseTypeVisitor(BaseTypeChecker checker) {
         this.visitorState = atypeFactory.getVisitorState();
         this.typeValidator = createTypeValidator();
         this.vectorType = atypeFactory.fromElement(elements.getTypeElement("java.util.Vector"));
```
Comment (wmdietl) [inline framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java]: Can we change these two fields to lazy initialization? Looking up elements and methods is rather costly and this is behavior that gets used very, very seldom.

File: checker/build.xml [hunk 4]
```diff
@@ -1452,7 +1452,7 @@ So, use our own archived version.
     </target>
 
     <target name="download-jdk" description="Downloads jdk8.jar from checkerframework.org/dev-jdk to checker/jdk and checker/dist">
-        <get src="https://checkerframework.org/dev-jdk/jdk8.jar" dest="jdk/jdk8.jar"/>
+        <get src="https://github.com/smillst/checker-framework-jdk/releases/download/smillst%2Fissue1522/jdk8.jar" dest="jdk/jdk8.jar"/>
```
Comment (smillst) [inline checker/build.xml]: Revert before merge!

**Comment by wmdietl** [comment]
@mernst There was a `Revert before merge!` comment that you ignored.

**Comment by mernst** [comment]
Sorry, my bad.  I'll fix it.  Thanks for noticing.

**Comment by smillst** [comment]
I fixed it.

**Comment by mernst** [comment]
Thanks, you beat me to it.
