### PR TITLE
Fix #1738: determine the appropriate java.util.Iterator type.

### LINKED ISSUE #1738: Crash in TreeBuilder.buildIteratorMethodAccess for Iterator type with multiple type parameters
Reported to us as uber/NullAway#104.  Minimal-ish repro input:
```java
import java.util.Iterator;
class Repro {
    static class TwoParamIterator<T,R> implements Iterator<T> {
        @Override
        public boolean hasNext() { return false; }
        @Override
        public T next() { return null; }
    }
    static class TwoParamCollection<T,R> implements Iterable<T> {
        @Override
        public TwoParamIterator<T,R> iterator() {
            return new TwoParamIterator<T,R>();
        }
    }
    static void test() {
        TwoParamCollection<String,String> c = new TwoParamCollection<>();
        for (String s: c) {
            s.hashCode();
        }
    }
}
```
When I run with CF 2.3.1 nullness checker I get:
```
$ javac -AprintErrorStack -processor org.checkerframework.checker.nullness.NullnessChecker Repro.java
error: SourceChecker.typeProcess: unexpected Throwable (IllegalArgumentException) while processing Repro.java; message: Incorrect number of type arguments
  Compilation unit: Repro.java
  Exception: java.lang.IllegalArgumentException: Incorrect number of type arguments; Stack trace: com.sun.tools.javac.model.JavacTypes.getDeclaredType0(JavacTypes.java:246)
  com.sun.tools.javac.model.JavacTypes.getDeclaredType(JavacTypes.java:222)
  org.checkerframework.javacutil.trees.TreeBuilder.buildIteratorMethodAccess(TreeBuilder.java:122)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:3533)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:1440)
  com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1043)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3247)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1440)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1554)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1601)
  org.checkerframework.framework.flow.CFCFGBuilder.run(CFCFGBuilder.java:61)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1138)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1115)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1045)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1422)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:247)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:282)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:163)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:495)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

File: javacutil/src/org/checkerframework/javacutil/trees/TreeBuilder.java [hunk 1]
```diff
@@ -140,6 +142,27 @@ public MemberSelectTree buildIteratorMethodAccess(ExpressionTree iterableExpr) {
         return iteratorAccess;
     }
 
+    /** Find the supertype of iteratorType that conforms to java.util.Iterator. */
+    private DeclaredType findIteratorSupertype(DeclaredType iteratorType) {
```
Comment (smillst) [inline javacutil/src/org/checkerframework/javacutil/trees/TreeBuilder.java]: Could you use `com.sun.tools.javac.code.Types#asSuper` instead of this method?  Or is there some reason not to use `asSuper`?

Comment (wmdietl) [reply javacutil/src/org/checkerframework/javacutil/trees/TreeBuilder.java]: Thanks! I had only looked in the model version of Types, not in the javac version. I changed this and at least the nullness tests continue to work.
