### PR TITLE
Treat assert methods as assert statements.

### LINKED ISSUE #1497: Support for general assertion frameworks
There are several frameworks that provide methods that take a boolean and throw an exception if the boolean is false. Instead of:

```java
assert value != null && value.something(): "@AssumeAssertion(nullness)"
```

one might write:

```java
Verify.verify(value != null && value.something());
```

Using Google Guava as an example: https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Verify.java#L98

Methods like `Verify.verifyNotNull` https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Verify.java#L137 can be annotated to require a non-null argument.  (This was done in commit https://github.com/typetools/guava/commit/eda5f9cb5c3f6ba4434bead4fb8ea12dffc10f3c .)

Methods that take an arbitrary boolean should similarly be annotatable somehow.
One possibility

```java
@ThrowsIf(expression="#1", result=false, exception=VerifyException.class)
public static void verify(boolean expression);
```

or maybe as a generalization of the existing https://github.com/typetools/checker-framework/blob/master/dataflow/src/org/checkerframework/dataflow/qual/TerminatesExecution.java

```java
@TerminatesExecutionIf(expression="#1", result=false)
public static void verify(boolean expression);
```

For `assert` we provide command-line flags to select whether they should be assumed enabled or disabled and require a special marker message `"@AssumeAssertion(nullness)"`.
This flexibility doesn't seem necessary for such libraries.

Implementing the logic for these new specifications should be easily generalizable from the existing handling of `assert`.

### LINKED ISSUE #3345: @AssumeAssertion for JUnit methods
Writing [`@AssumeAssertion`](https://checkerframework.org/manual/#assumeassertion) in an `assert` statement's message makes the Checker Framework trust that the assertion succeeds.
This behavior should also apply to JUnit's `assert*` methods.

The classes that define relevant methods are
https://junit.org/junit4/javadoc/latest/org/junit/Assert.html
https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html

### PR DESCRIPTION
**Pull request by smillst**
I've add the Guava annotations here: https://github.com/typetools/guava/pull/79.   I didn't see any methods that can be marked `@AssertMethod` in AssertJ or Hamcreast.  `@AssertMethod`s take a boolean expression and those libraries don't take boolean expressions.

Fixes #3345 and fixes #1497

### CODE REVIEW

File: checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+   * The class of the exception thrown by this method. The default is {@link AssertionError}.
+   *
+   * @return class of the exception thrown by this method
+   */
+  Class<?> value() default AssertionError.class;
+
+  /**
+   * The one-based index of the boolean parameter that is tested. If the parameter is false, the
+   * method throws an exception. The check can be reversed by use of the {@link #result} element; if
+   * {@link result} is false, then the method throws an exception if the parameter is true.
```
Comment (mernst) [inline checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java:43]: This documentation seems inconsistent with the documentation for `result`.  Shouldn't `result` default to false rather than true?

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 2]
```diff
@@ -1298,6 +1319,26 @@ protected List<Node> convertCallArguments(
     int numFormals = formals.size();
 
     ArrayList<Node> convertedNodes = new ArrayList<>(numFormals);
+    AnnotationMirror assertMethodAnno =
+        annotationProvider.getDeclAnnotation(method, AssertMethod.class);
+    int param = -1;
```
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1324]: What does `param` represent?  Please document it.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 3]
```diff
@@ -1298,6 +1319,26 @@ protected List<Node> convertCallArguments(
...
+    TypeMirror assertType = null;
+    boolean assertTrue = true;
```
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1326]: To avoid re-assignment (and, more importantly, make clear that there is no reassignment), I would declare these variables where they currently are declared, but remove the initializers and put them in an `else` clause.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 4]
```diff
@@ -1298,6 +1319,26 @@ protected List<Node> convertCallArguments(
     int numFormals = formals.size();
 
     ArrayList<Node> convertedNodes = new ArrayList<>(numFormals);
+    AnnotationMirror assertMethodAnno =
+        annotationProvider.getDeclAnnotation(method, AssertMethod.class);
+    int param = -1;
+    TypeMirror assertType = null;
```
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1325]: This is an exception type, not the type of an `assert` statement.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 3 above)
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1326]: `isAssertTrue` would be a more descriptive name for this variable.

**Comment by msridhar** [comment]
FYI we implemented something similar to this for NullAway in https://github.com/uber/NullAway/pull/608, via customized CFG translation.  Maybe not for this PR, but it'd be cool if a client of dataflow could add to the set of methods to be treated in this manner, even if the methods don't have the appropriate annotation.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 5]
```diff
@@ -1634,6 +1683,40 @@ protected void translateAssertWithAssertionsEnabled(AssertTree tree) {
...
+   */
+  protected void treatMethodAsAssert(
+      MethodInvocationTree tree, TypeMirror assertType, boolean assertTrue, Node condition) {
+
+    // all necessary labels
+    Label thenLabel = new Label();
+    Label elseLabel = new Label();
+    ConditionalJump cjump = new ConditionalJump(thenLabel, elseLabel);
+    extendWithExtendedNode(cjump);
+    if (!assertTrue) {
```
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1702]: Could you put this logic in the `cjump` assignment, using either `if` or `?:`?

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AssertionErrorNode.java [hunk 6]
```diff
@@ -1,27 +1,43 @@
...
+  /** The node for the expression after {@code :} in the assert statement or null. */
+  protected final @Nullable Node detail;
+
+  /**
+   * Creates an AssertionErrorNode.
+   *
+   * @param tree tree for the assert statement or assert method.
+   * @param condition the node of the condition when if false the assertion exception is thrown
+   * @param detail node for the expression after {@code :} in the assert statement or null
+   * @param type the type of the assert statement
```
Comment (mernst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AssertionErrorNode.java:38]: This is the type of an exception, not of the statement itself.

**Review by mernst — CHANGES_REQUESTED** [review]

File: checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+   * {@link #result} is false, then the method throws an exception if the parameter is true.
+   *
+   * @return the one-based index of the boolean parameter that is tested
+   */
+  int parameter() default 1;
+
+  /**
+   * On which value for {@link #parameter} does the method complete normally?
+   *
+   * @return the result for {@link #parameter} on which the method completes normally
```
Comment (smillst) [inline checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java:52]: The documentation on `result` was incorrect.  I've fixed it, but now I'm wondering if `result` is a little confusing.   

The `result = false` means that the method will complete normally if the expression is false. Here's an example use on a Junit method.
```
  @AssertMethod(value = AssertionFailedError.class, result = false)
	public static void assertFalse(boolean condition, String message);
```

It's kind of nice that `assertFalse` matches with `result = false`.  But maybe it is a little confusing.  

I could rename `result` to `exceptionalResult` and change it meaning to "which result causes the exception to be thrown":
```
  @AssertMethod(value = AssertionFailedError.class, exceptionalResult = true)
	public static void assertFalse(boolean condition, String message);
```

Comment (mernst) [reply checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java:52]: I agree that the name is confusing.  I think renaming and/or changing the polarity is the right thing to do.

File: checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+   * @return the one-based index of the boolean parameter that is tested
+   */
+  int parameter() default 1;
+
+  /**
+   * On which value for {@link #parameter} does the method throw an exception?
+   *
+   * @return the result for {@link #parameter} on which the method throw an exception
+   */
+  boolean exceptionalResult() default false;
```
Comment (mernst) [inline checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java:57]: Use of "result" here could be misleading because this is not about the annotated method's result.  Rather, it is about the *value* of the boolean expression whose index is passed as `parameter`.

More seriously, though, there are multiple names used for this concept in the source code:
```
exceptionalResult
exceptionOnResult
isAssertTrue
```

This suggests we have not yet found the best name (or we have not settled on it).  Let's find a good name and use it consistently in the documentation and in the code.  I lean toward `isAssertTrue` or `exceptionalValue` or `exceptionalBooleanValue`.

**Review by mernst — CHANGES_REQUESTED** [review]
Just a few minor suggestions left.

File: checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java (hunk 8 above)
Comment (smillst) [reply checker-qual/src/main/java/org/checkerframework/dataflow/qual/AssertMethod.java:57]: Rename to `isAssertFalse = true`  defaults to `false`

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 9]
```diff
@@ -1353,13 +1382,79 @@ protected List<Node> convertCallArguments(
...
   }
 
+  /**
+   * Returns the AssertMethodTuple for {@code method}. If {@code method} is not an assert method,
+   * then {@link AssertMethodTuple#NONE} is returned.
+   *
+   * @param method a method element that might be an assert method
+   * @return the AssertMethodTuple for {@code method}
+   */
+  protected AssertMethodTuple getAssertMethodTuple(ExecutableElement method) {
```
Comment (smillst) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1402]: >FYI we implemented something similar to this for NullAway in https://github.com/uber/NullAway/pull/608, via customized CFG translation. Maybe not for this PR, but it'd be cool if a client of dataflow could add to the set of methods to be treated in this manner, even if the methods don't have the appropriate annotation. This could be done, e.g., by having an overridable method in CFGTranslationPhaseOne that checks whether a method should be treated as an assertion method.

@msridhar subclasses can override this method to add addtional methods that should be treated as asserts.
