### PR TITLE
When building a type tree, don't recur infinitely on wildcards

### LINKED ISSUE #3929: Crash report: error: SourceChecker.typeProcess: unexpected Throwable (StackOverflowError).
Test case:

```
package tainting;

import java.util.ArrayList;
import java.util.List;

public class CategorySeriesHandler {

    public void endElement(DefaultKeyedValues arg) {
        for (Object o : arg.getKeys()) {
        }
    }
}

class DefaultKeyedValues<K extends Comparable<K>> {
    public List<K> getKeys() {
        return new ArrayList<>();
    }
}

```

command:
`javac -processor tainting checker/tests/tainting/CategorySeriesHandler.java`

output:
```
error: SourceChecker.typeProcess: unexpected Throwable (StackOverflowError) while processing checker/tests/tainting/CategorySeriesHandler.java
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: checker/tests/tainting/CategorySeriesHandler.java
  Last visited tree at line 6 column 1:
  public class CategorySeriesHandler {
  Exception: java.lang.StackOverflowError; java.lang.StackOverflowError
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.QualIdent(TreeMaker.java:667)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.QualIdent(TreeMaker.java:669)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.QualIdent(TreeMaker.java:669)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.QualIdent(TreeMaker.java:669)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.QualIdent(TreeMaker.java:669)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.Type(TreeMaker.java:790)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker$AnnotationBuilder.visitCompoundInternal(TreeMaker.java:913)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker$AnnotationBuilder.translate(TreeMaker.java:935)
        at jdk.compiler/com.sun.tools.javac.tree.TreeMaker.Annotation(TreeMaker.java:947)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:63)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:115)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:151)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:115)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:151)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:115)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:151)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:115)
        at org.checkerframework.framework.flow.CFTreeBuilder.createAnnotatedType(CFTreeBuilder.java:151)
       ....
       1 error
```

### PR DESCRIPTION
**Pull request by smillst**
Fixes #3929.

### CODE REVIEW

**Review by mernst — APPROVED** [review]

File: framework/src/main/java/org/checkerframework/framework/flow/CFTreeBuilder.java [hunk 1]
```diff
@@ -33,6 +34,17 @@
  */
 public class CFTreeBuilder extends TreeBuilder {
 
+    /**
+     * To avoid infinite recursions, record each wildcard that has been converted to a tree. This
+     * set is cleared each time {@link #buildAnnotatedType(AnnotatedTypeMirror)} is called.
+     */
+    private Set<AnnotatedWildcardType> visitedWildcards = new HashSet<>();
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/flow/CFTreeBuilder.java:41]: The field could be final.
