### PR TITLE
Handle uninferred type parameter in array accesses (Fixes #3020)

### LINKED ISSUE #3020: AssertionError: visitArrayAccess on a non-AnnotatedArrayType
Minimized from [the real code](https://github.com/google/guava/blob/28b36c80447729d1edeffedd70dc4a7ac91e76ce/guava/src/com/google/common/util/concurrent/FuturesGetChecked.java#L189) (which doesn't yet contain the call to "`passThrough`," which is really going to be a call to `requireNonNull`):

```java
$ cat SomeEnum.java 
enum SomeEnum {
  INSTANCE;

  void retrieveConstant() {
    Class<?> theClass = SomeEnum.class;
    Object unused = passThrough(theClass.getEnumConstants())[0];
  }

  <T> T passThrough(T t) {
    return t;
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker SomeEnum.java
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing SomeEnum.java
  Compilation unit: SomeEnum.java
  Last visited tree at line 1 column 1:
  enum SomeEnum {
  Exception: java.lang.AssertionError; Stack trace: org.checkerframework.framework.type.TypeFromExpressionVisitor.visitArrayAccess(TypeFromExpressionVisitor.java:228)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitArrayAccess(TypeFromExpressionVisitor.java:71)
  com.sun.tools.javac.tree.JCTree$JCArrayAccess.accept(JCTree.java:2080)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1214)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:992)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:201)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitArrayAccess(CFAbstractTransfer.java:637)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitArrayAccess(CFAbstractTransfer.java:93)
  org.checkerframework.dataflow.cfg.node.ArrayAccessNode.accept(ArrayAccessNode.java:49)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:418)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:215)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:190)
  org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1253)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1171)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1520)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:320)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:523)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:516)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  com.sun.tools.javac.main.Main.compile(Main.java:302)
  com.sun.tools.javac.main.Main.compile(Main.java:162)
  com.sun.tools.javac.Main.compile(Main.java:57)
  com.sun.tools.javac.Main.main(Main.java:43)
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing SomeEnum.java
  Compilation unit: SomeEnum.java
  Last visited tree at line 1 column 1:
  enum SomeEnum {
  Exception: java.lang.AssertionError; Stack trace: org.checkerframework.framework.type.TypeFromExpressionVisitor.visitArrayAccess(TypeFromExpressionVisitor.java:228)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitArrayAccess(TypeFromExpressionVisitor.java:71)
  com.sun.tools.javac.tree.JCTree$JCArrayAccess.accept(JCTree.java:2080)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1214)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:992)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:201)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitArrayAccess(CFAbstractTransfer.java:637)
  org.checkerframework.checker.nullness.NullnessTransfer.visitArrayAccess(NullnessTransfer.java:197)
  org.checkerframework.checker.nullness.NullnessTransfer.visitArrayAccess(NullnessTransfer.java:57)
  org.checkerframework.dataflow.cfg.node.ArrayAccessNode.accept(ArrayAccessNode.java:49)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:418)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:215)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:190)
  org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1253)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1171)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1520)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:320)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:523)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  com.sun.tools.javac.main.Main.compile(Main.java:302)
  com.sun.tools.javac.main.Main.compile(Main.java:162)
  com.sun.tools.javac.Main.compile(Main.java:57)
  com.sun.tools.javac.Main.main(Main.java:43)
2 errors
```

The failing assertion is [`type instanceof AnnotatedArrayType`](https://github.com/typetools/checker-framework/blob/checker-framework-3.0.1/framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java#L228).

[Source file](https://github.com/typetools/checker-framework/files/4010278/SomeEnum.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/4010277/err.txt) attached.

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java [hunk 1]
```diff
@@ -224,8 +225,17 @@ public AnnotatedTypeMirror visitArrayAccess(ArrayAccessTree node, AnnotatedTypeF
             f.visitorState.setAssignmentContext(null);
 
             AnnotatedTypeMirror type = f.getAnnotatedType(node.getExpression());
-            assert type instanceof AnnotatedArrayType;
-            return ((AnnotatedArrayType) type).getComponentType();
+            if (type instanceof AnnotatedArrayType) {
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java]: Should this is TypeKinds instead of instanceof?

File: framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java [hunk 2]
```diff
@@ -224,8 +225,17 @@ public AnnotatedTypeMirror visitArrayAccess(ArrayAccessTree node, AnnotatedTypeF
...
+                return ((AnnotatedArrayType) type).getComponentType();
+            } else if (type instanceof AnnotatedWildcardType) {
+                // Clean-up after Issue #979.
+                AnnotatedWildcardType wc = (AnnotatedWildcardType) type;
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java]: Do you expect this to be an uninferred type argument? If so should we check that it is?

**Comment by wmdietl** [comment]
@smillst Thanks for the comments, I've addressed both.
