### PR TITLE
Reduce the number of false positives and crashes from uninferred wildcards.

### LINKED ISSUE #1377: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 5
This issue is against the code in #1373 as it is right now (including https://github.com/typetools/checker-framework/pull/1373/commits/1a8b2a4fb2771bbc4655305f6559945d78540308):

Run the Nullness Checker on:

```java
interface Function<P, R> {
  R apply(P p);
}

interface Foo<V> {
  static <U> Foo<U> of(Foo<U> in) {
    return in;
  }

  <S> Foo<S> m1(Function<? super V, S> f);
  <T> Foo<T> m2(Function<V, T> f);
}

class Crash5 {
  void foo(Foo<Void> p) {
    Foo.of(p.m1(in -> p))
        .m2(empty -> 5);
  }
}
```

This results in the following stack trace:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @FBCBottom @NonNull Object
  superType: @FBCBottom @NonNull Foo<@Initialized @Nullable Void>
  Compilation unit: Crash5.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1087)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:496)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:257)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:192)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:170)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
```

### LINKED ISSUE #1379: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 6
This issue might be fixed by the fix for #1377, but because the stack trace is different, I worked on minimizing this crash.
I again checked against #1373, which will be master soon.
Take:

```java
interface Box<V> {
}

interface Trans<I, O> {
  Box<O> apply(I in);
}

abstract class Crash6 {
  abstract <I, O> Box<O> app(Box<I> in, Trans<? super I, ? extends O> t);

  abstract <I, O> Trans<I, O> pass(Trans<I, O> t);

  abstract Box<Number> box(Number p);

  void foo(Box<Number> p) {
    app(p, pass(this::box));
  }
}
```

Run the Nullness Checker to get:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @Nullable Object
  superType: @Initialized @NonNull Number
  Compilation unit: Crash6.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.QualifierPolymorphism$PolyCollector.visitDeclared(QualifierPolymorphism.java:458)
  org.checkerframework.framework.util.QualifierPolymorphism$PolyCollector.visitDeclared(QualifierPolymorphism.java:342)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:900)
  org.checkerframework.framework.type.visitor.SimpleAnnotatedTypeVisitor.visit(SimpleAnnotatedTypeVisitor.java:64)
  org.checkerframework.framework.util.QualifierPolymorphism$PolyCollector.visit(QualifierPolymorphism.java:393)
  org.checkerframework.framework.util.QualifierPolymorphism.annotate(QualifierPolymorphism.java:272)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkMethodReferenceAsOverride(BaseTypeVisitor.java:2372)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:1175)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCMemberReference.accept(JCTree.java:1987)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
```

Note how there is `QualifierPolymorphism` on this stack trace, which isn't on #1377.

### LINKED ISSUE #1384: Method type argument inference: lambda parameter types and method references
Taking current master, including #1380 and #1381 but they shouldn't impact this, run the Nullness Checker on:

```java
interface Box<T> {}

interface Function<P, R> {
    R apply(P p);
}

interface Utils {
  <I, O> Box<O> foo(
      Box<I> input, Function<? super I, ? extends O> function);
  <I, O> Function<I, O> bar(
      Function<? super I, ? extends O> function);
}

class FalsePositive {
  Box<Integer> demo(Utils u, Box<String> bs) {
    return u.foo(
        bs,
        u.bar(
            (String s) -> 5
              )
                 );
  }
}
```

One gets:

```
FalsePositives.java:19: error: [lambda.param.type.incompatible] incompatible parameter types in lambda expression.
            (String s) -> 5
                    ^
  found   : ? extends @Initialized @Nullable Object
  required: @Initialized @NonNull String
1 error
```

The uninferred wildcard should be ignored (if not in conservative mode).

### LINKED ISSUE #1398: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 7
Take either master or a branch that contains #1387 and the following input:

```java
interface Pair<A, B> {}
interface Triple<A, B, C> {}
interface Quadruple<A, B, C, D> {}

interface Box<T> {
  <A, B> Pair<A, B> doTriple(Triple<? super T, A, B> t);

  <A, BA extends Box<A>> BA doPair(
      Pair<? super T, ? extends A> p,
      BoxMaker<A, BA> bm);
}

class BoxMaker<T, C extends Box<T>> {}

abstract class Crash7 {
  abstract <T, O> Pair<T, O> bar(Pair<T, O> in);

  void foo(Box<String> bs,
      BoxMaker<Number, Box<Number>> bm,
      Pair<String, Number> psn,
      Triple<Number, Object, Number> t) {
    bs.doPair(bar(psn), bm)
        .doTriple(t);
  }
}
```

Running the Nullness Checker gives, when using #1387:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @Nullable Object
  superType: @Initialized @NonNull Number
  Compilation unit: Crash7.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1110)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:485)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.checkAndSubtype(DefaultTypeHierarchy.java:330)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevarSubtype(DefaultTypeHierarchy.java:1026)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Declared(DefaultTypeHierarchy.java:854)
```

With master I get:

```
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing /usr/local/google/home/wernerd/workspaces/wmdietlGC-github.com/checker-framework/checker/Crash7.java
  Compilation unit: /usr/local/google/home/wernerd/workspaces/wmdietlGC-github.com/checker-framework/checker/Crash7.java
  Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:553)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:510)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:54)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:259)
```

This works in the April 2017 release.

I spent a significant amount of time trying to reproduce and minimize this test.
I'm not quite sure it is minimal yet, but every simplification I had tried removed the crash.

### LINKED ISSUE #1399: False positive for KeyFor checker with long literal
Take the following simple program and run the Nullness Checker:

```java
class Box<T> {
  static <T> Box<T> box(Class<T> type) {
    return new Box<T>();
  }
  void act(T instance) {}
}

abstract class Math {
  abstract <T> Box<T> id(Box<T> in);

  void foo(Math m) {
    m.id(Box.box(Long.class)).act(10L);
  }
}
```

The output is:

```
Math.java:12: error: [argument.type.incompatible] incompatible types in argument.
    m.id(Box.box(Long.class)).act(10L);
                                  ^
  found   : @UnknownKeyFor long
  required: ?[ extends @UnknownKeyFor Object super @KeyForBottom Void]
1 error
```

This occurs with master and an older version of #1387. Haven't tried with newest version of #1387, but wanted to report it for the test case.

### LINKED ISSUE #1407: AsSuperVisitor Declared_Primitive: type is not a box primitive.
While trying to reproduce an issue similar to #1398 I ran into a different exception.
This is using #1387 with all included fixes there.

Take:

```java
import org.checkerframework.checker.nullness.qual.Nullable;

abstract class Crash7b {
  abstract <T> T foo(@Nullable T p1, @Nullable T p2);

  abstract <T extends Number> @Nullable T bar(int p1, T p2);

  int demo() {
    return foo(
        bar(5, 3),
        3);
  }
}
```

Running the Nullness Checker gives:

```
error: AsSuperVisitor Declared_Primitive: type is not a box primitive.
  Compilation unit: Crash7b.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Primitive(AsSuperVisitor.java:362)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Primitive(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:332)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Primitive(DefaultTypeHierarchy.java:611)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Primitive(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:332)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory$KeyForTypeHierarchy.isSubtype(KeyForAnnotatedTypeFactory.java:164)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:173)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:151)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1781)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:1216)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1390)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
```

As I'm trying to go after a different bug, I didn't spend much time minimizing this test case. Maybe it can be simplified a bit more.

### LINKED ISSUE #1408: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 7b
An exception with a similar stack trace as #1398, but didn't get fixed by its fix in #1387.

Take

```java
abstract class Crash7b {
  interface Demo {}
  interface SubDemo extends Demo {}

  abstract <S> S foo(S p1, S p2);

  abstract <T extends Demo> T bar(T p2);

  SubDemo demo(SubDemo p) {
    return foo(bar(p), p);
  }
}
```

Running the Nullness Checker gives:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Demo
  superType: @Initialized @NonNull SubDemo
  Compilation unit: Crash7b.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:485)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:173)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:151)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:221)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1781)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:204)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:1216)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1390)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
```

### LINKED ISSUE #1415: error: MultiGraphQualifierHierarchy found an unqualified type
In a repo with master and #1387 take:

```java
class Optional<T> {
  static <T> Optional<T> absent() { return null; }
  static <T> Optional<T> of(T p) { return null; }
}

class Box<T> {
  void box(T p) {}
}

class Crash9 {
  <T extends Enum<T>> void foo(boolean b,
      Box<Optional<T>> box,
      Class<T> enumClass) {
    box.box(
        b
        ? Optional.<T>absent()
        : Optional.of(Enum.valueOf(enumClass, "hi"))
            );
  }
}
```

Running the Nullness Checker results in a few exceptions and assertion errors, starting with:

```
error: MultiGraphQualifierHierarchy found an unqualified type.  Please ensure that your implicit rules cover all cases and/or use a @DefaultQualifierInHierarchy annotation.
  Compilation unit: Crash9.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.checkAnnoInGraph(MultiGraphQualifierHierarchy.java:506)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.isSubtype(MultiGraphQualifierHierarchy.java:470)
  org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory$KeyForQualifierHierarchy.isSubtype(KeyForAnnotatedTypeFactory.java:253)
  org.checkerframework.framework.util.AtmLubVisitor.lubPrimaryOnBoundedType(AtmLubVisitor.java:329)
  org.checkerframework.framework.util.AtmLubVisitor.visitTypevar_Typevar(AtmLubVisitor.java:290)
  org.checkerframework.framework.util.AtmLubVisitor.visitTypevar_Typevar(AtmLubVisitor.java:31)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:662)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.util.AtmLubVisitor.lubTypeArgument(AtmLubVisitor.java:243)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:184)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:31)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.util.AtmLubVisitor.visitTypevar_Typevar(AtmLubVisitor.java:287)
  org.checkerframework.framework.util.AtmLubVisitor.visitTypevar_Typevar(AtmLubVisitor.java:31)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:662)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.util.AtmLubVisitor.lubTypeArgument(AtmLubVisitor.java:243)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:184)
  org.checkerframework.framework.util.AtmLubVisitor.visitDeclared_Declared(AtmLubVisitor.java:31)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:66)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:629)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitConditionalExpression(TypeFromExpressionVisitor.java:105)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitConditionalExpression(TypeFromExpressionVisitor.java:45)
  com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1245)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
```

(This is Crash9... I'm still trying to repro Crash8 and started working on this one...)

### LINKED ISSUE #1416: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 8
In a repo with master and #1387 take:

```java
import java.util.Comparator;
import java.util.stream.Stream;

class Crash10 {
  long order(Stream<Long> sl) {
    return sl
        .max(Comparator.naturalOrder())
        .orElse(0L);
  }
}
```

Running the Nullness Checker gives:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Comparable<? extends @Initialized @NonNull Object super T extends @Initialized @NonNull Comparable<?>>
  superType: @Initialized @NonNull Long
  Compilation unit: Crash10.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:485)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.checkAndSubtype(DefaultTypeHierarchy.java:330)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevarSubtype(DefaultTypeHierarchy.java:1030)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Declared(DefaultTypeHierarchy.java:858)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:632)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.checkAndSubtype(DefaultTypeHierarchy.java:330)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedBy(DefaultTypeHierarchy.java:400)
  org.checkerframework.framework.type.DefaultTypeHierarchy.compareTypeArgs(DefaultTypeHierarchy.java:588)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:561)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:497)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.checkAndSubtype(DefaultTypeHierarchy.java:330)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedBy(DefaultTypeHierarchy.java:400)
  org.checkerframework.framework.type.DefaultTypeHierarchy.compareTypeArgs(DefaultTypeHierarchy.java:588)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:561)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:497)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:173)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:151)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:221)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1781)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:204)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2237)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:939)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:160)
```

### LINKED ISSUE #1417: Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 9
In a repo with master and #1387 take:

```java
interface Bar {}
interface SubBar extends Bar {}

interface Barber<S extends Bar> {
  S call(S s);
}

abstract class Crash12 {
  abstract void foo(Barber<?> b);

  void crash() {
    foo( (SubBar p) -> p);
  }
}
```

Running the Nullness Checker gives:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Bar
  superType: @Initialized @NonNull SubBar
  Compilation unit: Crash12.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:485)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:173)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:151)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:221)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitLambdaExpression(BaseTypeVisitor.java:1161)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitLambdaExpression(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1628)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2241)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:939)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:298)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:58)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:568)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:382)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:58)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
```

### PR DESCRIPTION
**Pull request by smillst**
This pull request is both fixing crashes and false positives associated type method type argument inference, lambdas, and/or member references. 

Fixes #1384, fixes #1399, fixes #1398, fixes #1407, fixes #1408, fixes #1415, fixes #1416, fixes #1377, fixes #1379 and fixes #1417.

### CODE REVIEW

File: checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java [hunk 1]
```diff
@@ -299,6 +302,24 @@ protected AnnotatedTypeFormatter createAnnotatedTypeFormatter() {
...
+                new SimpleAnnotatedTypeScanner<Void, Void>() {
+                    @Override
+                    protected Void defaultAction(AnnotatedTypeMirror type, Void aVoid) {
+                        if (type == null) {
+                            return null;
+                        }
+                        if (type.getKind() == TypeKind.WILDCARD
+                                && ((AnnotatedWildcardType) type).isUninferredTypeArgument()
+                                && ignoreUninferredTypeArguments) {
+                            type.replaceAnnotations(qualHierarchy.getBottomAnnotations());
```
Comment (wmdietlGC) [inline checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java]: This is not working well for me and it's also not clear why this should be a Nullness Checker specific change.
It works better if instead of adding all bottom annotations, this adds only NONNULL.
In general, I would try using the same defaults as `java.lang.Object` would get. There is no easy way to do this, I think, other than asking the type factory to annotate `java.lang.Object` and then taking the annotations from there.

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 2]
```diff
@@ -1022,7 +1027,7 @@ protected boolean visitWildcardSupertype(
     protected boolean visitWildcardSubtype(
             AnnotatedWildcardType subtype, AnnotatedTypeMirror supertype, VisitHistory visited) {
         if (subtype.isUninferredTypeArgument()) {
-            return ignoreUninferredTypeArguments;
+            return subtype.atypeFactory.ignoreUninferredTypeArguments;
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Doing the same in `visitWildcardSupertype` removed a few more false positives.

**Comment by wmdietlGC** [comment]
Thanks for all the improvements in this PR!
Here another false positive caused by uninferred wildcards; let me know if I should file it as a separate bug first.

```java
abstract class FP {
  class Box<T> {}
  interface Function<S, T> { T apply(S p); }

  abstract <T> Box<Box<T>> foo(Box<? extends Box<? extends T>> p);

  abstract <T> Box<Box<T>> bar(Function<Number, T> f);

  abstract String baz(Number p);

  Box<Box<String>> demo() {
    return foo(bar(this::baz));
  }
}
```

Running the Nullness Checker on this gives:

```
FP.java:12: error: [return.type.incompatible] incompatible types in return.
    return foo(bar(this::baz));
              ^
  found   : FP.@Initialized @NonNull Box<FP.@Initialized @NonNull Box<? extends @Initialized @Nullable Object>>
  required: FP.@Initialized @NonNull Box<FP.@Initialized @NonNull Box<@Initialized @NonNull String>>
1 error
```

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 3]
```diff
@@ -3495,55 +3489,49 @@ private void assertFunctionalInterface(
...
+        List<AnnotatedTypeMirror> newTypeArguments =
+                new ArrayList<>(functionalType.getTypeArguments());
+
+        for (int i = 0; i < functionalType.getTypeArguments().size(); i++) {
+            AnnotatedTypeMirror argType = functionalType.getTypeArguments().get(i);
+            if (argType.getKind() == TypeKind.WILDCARD) {
+                AnnotatedWildcardType wildcardType = (AnnotatedWildcardType) argType;
+
+                TypeMirror wildcardUbType = wildcardType.getExtendsBound().getUnderlyingType();
+                TypeMirror correctArgType = groundTargetJavaType.getTypeArguments().get(i);
```
Comment (wmdietlGC) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: #1424 is caused by this line.
I don't see a check that `groundTagetJavaType` and `functionalType` have the same number of type arguments.
This is causing a crash somewhere else, too, but it's been harder to reproduce.

Comment (smillst) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: The same crash or a different one?  (I fixed the crash in #1424.)

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 4]
```diff
@@ -1255,6 +1261,15 @@ protected void addComputedTypeAnnotations(Element elt, AnnotatedTypeMirror type)
     }
 
     /**
+     * Adds default annotations to {@code type}.
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: The class documentation states that `This implementation only adds qualifiers explicitly specified by the programmer.` and that `addComputedTypeAnnotations` should be overridden to customize how annotations are added.
Do we need a one-argument version of `addComputedTypeAnnotations` and use that name instead of the new `addDefaultAnnotations`? Or can we provide a `Tree` or an `Element` to use the already existing implementations in the call sites of `addDefaultAnnotations`?
The javadoc should at least discuss what the relationship to the existing methods is.
I would add a big TODO to this method that this API needs to be cleaned up.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 5]
```diff
@@ -3463,17 +3461,13 @@ private AnnotatedDeclaredType getFunctionalInterfaceType(
         }
     }
 
-    private void assertFunctionalInterface(
-            com.sun.tools.javac.code.Types javacTypes,
-            Type type,
-            Tree contextTree,
-            Tree lambdaTree) {
+    private void assertFunctionalInterface(Type type, Tree contextTree, Tree lambdaTree) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: How about making the first argument a `TypeMirror` and casting here, to safe all the casts in the invocations?

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 6]
```diff
@@ -429,6 +418,17 @@ protected boolean isContainedBy(
         }
     }
 
+    private boolean ignoreUninferred(AnnotatedTypeMirror inside) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: I would maybe add the `TypeArgument` to the method name and use `type` instead of `inside`, to avoid confusion with the parameter names used in the calls of this method.

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java [hunk 7]
```diff
@@ -1030,15 +1039,15 @@ protected Boolean visitUnionSubtype(
     protected boolean visitWildcardSupertype(
             AnnotatedTypeMirror subtype, AnnotatedWildcardType supertype, VisitHistory visited) {
         if (supertype.isUninferredTypeArgument()) { //TODO: REMOVE WHEN WE FIX TYPE ARG INFERENCE
-            return isSubtype(subtype, supertype.getExtendsBound());
+            return supertype.atypeFactory.ignoreUninferredTypeArguments;
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: Should this add `|| isSubtype(...)` to perform the previous subtype test if uninferred TAs should not be ignored?

File: framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java [hunk 8]
```diff
@@ -1370,6 +1376,24 @@ public void addComputedTypeAnnotations(Element elt, AnnotatedTypeMirror type) {
         Pair<AnnotatedExecutableType, List<AnnotatedTypeMirror>> mfuPair =
                 super.methodFromUse(tree);
         AnnotatedExecutableType method = mfuPair.first;
+
+        if (method.getReturnType().getKind() == TypeKind.WILDCARD
+                && ((AnnotatedWildcardType) method.getReturnType()).isUninferredTypeArgument()) {
+            // Get the correct Java type from the tree and use it as the upper bound of the
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java]: Could you add a comment why this change is done here instead of in the superclass?

File: framework/src/org/checkerframework/framework/type/SupertypeFinder.java [hunk 9]
```diff
@@ -196,6 +197,18 @@
             return supertypes;
         }
 
+        private void subTypeVarsInWildcards(
+                Map<TypeParameterElement, AnnotatedTypeMirror> mapping) {
+            for (AnnotatedTypeMirror atm : mapping.values()) {
+                if (atm.getKind() == TypeKind.WILDCARD) {
+                    // Because the upper bound of the wildcard is copied from the upper bound of
+                    // the type parameter in #fixWildcardBound, it might contain references to
+                    // other type variables.  This replaces thos references.
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: thos -> those

Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: Maybe add why this is done here instead of as part of `fixWildcardBound`. Because you need the full mapping?

File: framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java [hunk 10]
```diff
@@ -202,6 +202,17 @@ public boolean hasDefaultsForCheckedCode() {
         return false;
     }
 
+    /** @return the default qualifiers for this hierarchy */
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java]: Method summary javadoc like for the other methods would be good.

File: framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java [hunk 11]
```diff
@@ -739,8 +739,9 @@ private void handleUninferredTypeVariables(
         for (AnnotatedTypeVariable atv : methodType.getTypeVariables()) {
             final TypeVariable typeVar = atv.getUnderlyingType();
             if (targets.contains(TypeAnnotationUtils.unannotatedType(typeVar))) {
-                final AnnotatedTypeMirror inferredType = inferredArgs.get(typeVar);
-                if (inferredType == null) {
+                AnnotatedTypeMirror inferredType = inferredArgs.get(typeVar);
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java]: Why remove the `final`?

File: framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java [hunk 12]
```diff
@@ -328,8 +330,14 @@ private static boolean containsUninferredTypeParameter(
                                     annotatedTypeVar.getUnderlyingType()));
         }
 
+        return containsTypeParameter(type, typeVars);
+    }
+
+    /** @return true if the type contains a use of a type variable in typeVariables. */
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java]: Method summary javadoc like for the other methods would be good.

File: framework/tests/framework/BridgeMethods.java [hunk 13]
```diff
@@ -19,7 +19,9 @@ void use() {
         c.id(new @Odd Object());
 
         // Oddness is wrong! Would also fail with ClassCastException.
-        //:: error: (argument.type.incompatible) :: warning: [unchecked] unchecked call to id(T) as a member of the raw type C
+        // TODO: false postive
```
Comment (wmdietl) [inline framework/tests/framework/BridgeMethods.java]: Should `postive` be `negative`? You changed an expected error into a comment.

File: javacutil/src/org/checkerframework/javacutil/InternalUtils.java [hunk 14]
```diff
@@ -452,4 +452,28 @@ public static int compareDiagnosticPosition(Tree tree1, Tree tree2) {
 
         return Integer.compare(pos1.getStartPosition(), pos2.getStartPosition());
     }
+
+    /**
+     * @return whether or not {@code type} is a functional interface type (as defined in JLS 9.8).
```
Comment (wmdietl) [inline javacutil/src/org/checkerframework/javacutil/InternalUtils.java]: Method summary javadoc like for the other methods would be good.

File: checker/jtreg/nullness/issue824/Class2.out [hunk 15]
```diff
@@ -1,10 +1,9 @@
 Class2.java:14:39: compiler.err.proc.messager: (type.argument.type.incompatible)
 Class2.java:15:22: compiler.err.proc.messager: (type.argument.type.incompatible)
 Class2.java:15:47: compiler.err.proc.messager: (type.argument.type.incompatible)
-Class2.java:16:31: compiler.err.proc.messager: (type.argument.type.incompatible)
```
Comment (smillst) [inline checker/jtreg/nullness/issue824/Class2.out]: This is a false negative.  I'll add a comment.

File: framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java (hunk 7 above)
Comment (smillst) [inline framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java]: No, that causes a crashes.  I'll add a comment.

File: checker/tests/nullness/MisuseProperties.java [hunk 16]
```diff
@@ -16,7 +16,9 @@ void propertiesToHashtable(Properties p) {
         p.put("line.separator", null);
         Hashtable h = p;
         // Error, because HashTable value has NonNull bound.
-        //:: error: (argument.type.incompatible) :: warning: [unchecked] unchecked call to put(K,V) as a member of the raw type java.util.Hashtable
+        // TODO: false negative.
```
Comment (smillst) [inline checker/tests/nullness/MisuseProperties.java]: I did this for all TODOs in test cases where fixing type argument inference will address the todo.  The remaining `// TODO: false negative` comments are false negatives from raw types.  I'm not sure if they will/should be fixed by type argument inference.  I could add references to #635 for those.

File: checker/tests/nullness/java8inference/FalsePositives.java [hunk 17]
```diff
@@ -0,0 +1,61 @@
+
```
Comment (smillst) [inline checker/tests/nullness/java8inference/FalsePositives.java]: Add issue reference above.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java (hunk 4 above)
Comment (smillst) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: We need this method because at the call sites, there is no tree or element that corresponds to `type`.  I did not name this method `addComputedTypeAnnotations` because it only adds `defaults`. 

I added a comment to caution the use of this method.

File: checker/tests/nullness/MisuseProperties.java (hunk 16 above)
Comment (wmdietl) [inline checker/tests/nullness/MisuseProperties.java]: Thanks. Adding #635 for the ones involving raw types sounds perfect.

File: checker/tests/nullness/java8inference/FalsePositives.java (hunk 17 above)
Comment (wmdietl) [inline checker/tests/nullness/java8inference/FalsePositives.java]: https://github.com/typetools/checker-framework/pull/1387#issuecomment-316147360 for other parts.

File: framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 18]
```diff
@@ -2009,6 +2013,12 @@ protected void checkTypeArguments(
         }
     }
 
+    private boolean isUninferredWildcard(AnnotatedTypeMirror type) {
```
Comment (wmdietl) [inline framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java]: Maybe `isIgnoredUninferredWildcard` to highlight that it only applies if TAs are ignored.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 19]
```diff
@@ -136,8 +135,9 @@
  *
  * <p>Type system checker writers may need to subclass this class, to add implicit and default
  * qualifiers according to the type system semantics. Subclasses should especially override {@link
- * AnnotatedTypeFactory#addComputedTypeAnnotations(Element, AnnotatedTypeMirror)} and {@link
- * #addComputedTypeAnnotations(Tree, AnnotatedTypeMirror)}.
+ * AnnotatedTypeFactory#addComputedTypeAnnotations(Element, AnnotatedTypeMirror)}, {@link
+ * #addComputedTypeAnnotations(Tree, AnnotatedTypeMirror)}, and {@link
+ * #addDefaultAnnotations(AnnotatedTypeMirror)}.
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: I would list the third one as a temporary hack, not as one of the intended extension points.

File: framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 20]
```diff
@@ -3495,55 +3511,71 @@ private void assertFunctionalInterface(
...
+                } else {
+                    newTypeArguments.set(i, wildcardType.getSuperBound());
                 }
             }
-            overriddenType.setTypeArguments(newTypeArguments);
         }
+        functionalType.setTypeArguments(newTypeArguments);
+
+        // When the groundTargetJavaType is different from the underlying type of functionalType,
+        // only the main annotations are copied.  Add default annotations in places withouth
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: withouth -> without

File: framework/tests/framework/BridgeMethods.java [hunk 21]
```diff
@@ -19,7 +19,9 @@ void use() {
         c.id(new @Odd Object());
 
         // Oddness is wrong! Would also fail with ClassCastException.
-        //:: error: (argument.type.incompatible) :: warning: [unchecked] unchecked call to id(T) as a member of the raw type C
+        // TODO: false negative
```
Comment (wmdietl) [inline framework/tests/framework/BridgeMethods.java]: Reference to raw type issue.
