### PR TITLE
Correct enclosing class for NewClassTrees. (Fixes #3022 and #2975)

### LINKED ISSUE #2975: AsSuperVisitor: type is not an erased subtype of supertype.
This is using checker-framework 3.0.1 with OpenJDK 11.0.2 with the NullnessChecker only.  I have the following simplified code in two classes, which compiles fine in plain Java:

```
package sup;

import java.util.function.Consumer;

public class Parent<T extends AutoCloseable>
{
    protected class Wrapper
    {
        protected Wrapper(Consumer<T> makeExpression)
        {
        }
    }
}
```

and

```
package sup;

import java.io.Closeable;

public class Child extends Parent<Closeable>
{
    Wrapper x = new Wrapper(Child::takesCloseable);

    private static void takesCloseable(Closeable rhs)
    {
    }
}
```

There is nothing special about Closeable here, it's just a handy interface from the core classes where Closeable extends AutoCloseable to shorten the example.  Some combination of the inner class in the parent using the parent's type parameter plus the method reference in the subclass seems to cause a problem.  The error goes through the well-named BugInCF class which is why I'm reporting it here.  Stack trace of errors is:

```
[ERROR] AsSuperVisitor: type is not an erased subtype of supertype.
[ERROR]   type: @UnknownKeyFor AutoCloseable
[ERROR]   superType: @UnknownKeyFor Closeable
[ERROR]   Compilation unit: C:\Users\neil\IdeaProjects\testchecker\mymodule\src\main\java\sup\Child.java
[ERROR]   Last visited tree at line 7 column 29:
[ERROR]       Wrapper x = new Wrapper(Child::takesCloseable);
[ERROR]   Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:338)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
[ERROR]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
[ERROR]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_NotTypevarNorWildcard(AsSuperVisitor.java:583)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:590)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:28)
[ERROR]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:631)
[ERROR]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
[ERROR]   org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:451)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:401)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.access$100(AbstractQualifierPolymorphism.java:325)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism.resolve(AbstractQualifierPolymorphism.java:225)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.checkMethodReferenceAsOverride(BaseTypeVisitor.java:3032)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:1619)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMemberReference.accept(JCTree.java:2205)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2824)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitNewClass(BaseTypeVisitor.java:1557)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitNewClass(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1711)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:223)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visitVariable(SourceVisitor.java:100)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:1043)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:974)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:384)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:339)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
[ERROR]   org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
[ERROR]   org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:523)
[ERROR]   org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:516)
[ERROR]   org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
[ERROR]   org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
[ERROR]   org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
[ERROR]   org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
[ERROR]   org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
[ERROR]   org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]   org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]   org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]   org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]   org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]   org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]   org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]   org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]   org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] AsSuperVisitor: type is not an erased subtype of supertype.
[ERROR]   type: @Initialized @NonNull AutoCloseable
[ERROR]   superType: @Initialized @NonNull Closeable
[ERROR]   Compilation unit: C:\Users\neil\IdeaProjects\testchecker\mymodule\src\main\java\sup\Child.java
[ERROR]   Last visited tree at line 7 column 29:
[ERROR]       Wrapper x = new Wrapper(Child::takesCloseable);
[ERROR]   Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:338)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
[ERROR]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
[ERROR]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_NotTypevarNorWildcard(AsSuperVisitor.java:583)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:590)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visitTypevar_Declared(AsSuperVisitor.java:28)
[ERROR]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:631)
[ERROR]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
[ERROR]   org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
[ERROR]   org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:451)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:401)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.access$100(AbstractQualifierPolymorphism.java:325)
[ERROR]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism.resolve(AbstractQualifierPolymorphism.java:225)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.checkMethodReferenceAsOverride(BaseTypeVisitor.java:3032)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:1619)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitMemberReference(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMemberReference.accept(JCTree.java:2205)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2824)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitNewClass(BaseTypeVisitor.java:1557)
[ERROR]   org.checkerframework.checker.nullness.NullnessVisitor.visitNewClass(NullnessVisitor.java:553)
[ERROR]   org.checkerframework.checker.nullness.NullnessVisitor.visitNewClass(NullnessVisitor.java:54)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1711)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:223)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visitVariable(SourceVisitor.java:100)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:1043)
[ERROR]   org.checkerframework.checker.initialization.InitializationVisitor.visitVariable(InitializationVisitor.java:167)
[ERROR]   org.checkerframework.checker.initialization.InitializationVisitor.visitVariable(InitializationVisitor.java:52)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:974)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:384)
[ERROR]   org.checkerframework.checker.initialization.InitializationVisitor.processClassTree(InitializationVisitor.java:295)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:339)
[ERROR]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
[ERROR]   jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[ERROR]   jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
[ERROR]   org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
[ERROR]   org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:523)
[ERROR]   org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
[ERROR]   jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[ERROR]   jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
[ERROR]   org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
[ERROR]   org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
[ERROR]   org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
[ERROR]   org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
[ERROR]   org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]   org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]   org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]   org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]   org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]   org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]   org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]   org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]   org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]   org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]   org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]   org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] -> [Help 1]
```

### LINKED ISSUE #3022: Type variables are not substituted for implicit receivers of inner class constructor calls
This passes the nullness checker under 3.0.0 but fails under 3.0.1. I think it should pass.

```java
$ cat Sub.java
abstract class Super<K> {
  class Wrapper {
    Wrapper(K key) {}
  }
}

class Sub<K> extends Super<K> {
  void wrap(K key) {
    new Wrapper(key);
  }
}
```
```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker Sub.java 
Sub.java:9: error: [argument.type.incompatible] incompatible types in argument.
    new Wrapper(key);
                ^
  found   : K extends @Initialized @Nullable Object
  required: K extends @Initialized @Nullable Object
1 error
```

This is minimized from [the real code](https://github.com/google/guava/blob/28b36c80447729d1edeffedd70dc4a7ac91e76ce/guava/src/com/google/common/collect/Multimaps.java#L268).

[Source file](https://github.com/typetools/checker-framework/files/4010635/Sub.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/4010636/err.txt) attached.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #3022 and Fixes #2975

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 1]
```diff
@@ -1662,6 +1663,20 @@ protected AnnotatedDeclaredType getImplicitReceiverType(ExpressionTree tree) {
                             "AnnotatedTypeFactory.getImplicitReceiver: enclosingClass()==null for element: "
                                     + element);
                 }
+                if (tree.getKind() == Kind.NEW_CLASS) {
+                    if (typeElt.getEnclosingElement() != null) {
+                        typeElt = ElementUtils.enclosingClass(typeElt.getEnclosingElement());
+                        if (typeElt == null) {
+                            // If the typeElt does not have an enclosing class, then the
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java]: The comment here and below is the same, which was a bit surprising. Would the logic be easier to understand as:

```java
if (typeElt.getEnclosingElement() == null || ElementUtils.enclosingClass(typeElt.getEnclosingElement() == null) {
    // If the typeElt does not have an enclosing class, then the NewClassTree
    // does not have an implicit receiver.
    return null;
}
```

That doesn't perform the re-assignment of `typeElt` when it has an enclosing class, which is tricky to notice.
But is that re-assignment good, as `typeElt` is used in `getEnclosingType` below?
So I guess I'm asking for some more documentation what the cases are for.

File: framework/tests/all-systems/java8inference/Issue2975.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
+package sup;
```
Comment (wmdietl) [inline framework/tests/all-systems/java8inference/Issue2975.java]: Is the package here necessary? It doesn't seem to match the location of the file.
