### PR TITLE
Handle enclosing types correctly in SuperTypeVisitor.

### LINKED ISSUE #1442: AsSuperVisitor: type is not an erased subtype of supertype
This seems to affect Spring Security.

The crash-inducing calls are `.and().httpBasic()`.

I've uploaded a test case to https://github.com/entonio/AsSuperVisitor.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1442.

### CODE REVIEW

File: framework/src/org/checkerframework/framework/type/SupertypeFinder.java [hunk 1]
```diff
@@ -161,10 +161,17 @@
...
-                AnnotatedTypeMirror typArg = type.getTypeArguments().get(i);
-                TypeParameterElement ele = typeElement.getTypeParameters().get(i);
-                mapping.put(ele, typArg);
+            AnnotatedDeclaredType enclosing = type;
+            while (enclosing != null) {
+                TypeElement enclosingTypeElement =
+                        (TypeElement) enclosing.getUnderlyingType().asElement();
+                for (int i = 0; i < enclosing.getTypeArguments().size(); ++i) {
+                    AnnotatedTypeMirror typArg = enclosing.getTypeArguments().get(i);
+                    TypeParameterElement ele = enclosingTypeElement.getTypeParameters().get(i);
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/type/SupertypeFinder.java]: Note that `getTypeParameters` allocates a fresh list on every call. I would suggest putting both the type arguments and the type parameters into locals outside the loop.
