### PR TITLE
Correctly apply annotations in stub files to types of fields.

### LINKED ISSUE #1456: Error parsing a field with array of primitive types in a stub file
Consider following stub file:
`class Myclass {
    @MyAnnotation int[] field;
}
`

It is being parsed by the stubparser project successfully. However, it leads to the ClassCastException in the framework subproject of the Checker Framework.
`[java] error: SourceChecker.typeProcessingStart: unexpected Throwable (ClassCastException); message: com.github.javaparser.ast.type.PrimitiveType cannot be cast to com.github.javaparser.ast.type.ReferenceType; The Checker Framework crashed.  Please report the crash.  To see the full stack trace invoke the compiler with -AprintErrorStack`

Errored Travis job:
https://travis-ci.org/Bohdankm22/sparta/builds/264818673

I think the problem is somewhere in the StubParser.java in the framework subproject. It tries to cast the object to the ReferenceType.
The exception is probably thrown in https://github.com/typetools/checker-framework/blob/8997a341784732c42444ba5a0123e6c514348c0e/framework/src/org/checkerframework/framework/stub/StubParser.java#L763

Checked the ArrayType.java in the stubparser project and it extends ReferenceType. Hence it should be possible to cast ArrayType to the ReferenceType.

Also, need to mention that the issue happens only for the arrays of primitive types.

A possible reason could that it tries to cast to the ReferenceType underlying in the ArrayType type instead of casting the ArrayType itself.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #1456.

### CODE REVIEW

File: framework/src/org/checkerframework/framework/stub/StubParser.java [hunk 1]
```diff
@@ -858,7 +859,22 @@ private void parseField(
...
+            if (var.getName().toString().equals(elt.getSimpleName().toString())) {
+                fieldVarDecl = var;
+            }
+        }
+        assert fieldVarDecl != null;
+
+        annotate(fieldType, fieldVarDecl.getType());
+
+        if (fieldType.getKind() == TypeKind.ARRAY) {
+            annotate(((AnnotatedArrayType) fieldType).getComponentType(), decl.getAnnotations());
```
Comment (wmdietl) [inline framework/src/org/checkerframework/framework/stub/StubParser.java]: Shouldn't this go to the component type that is no longer an array?
I.e. in `@A int [] [] f` I think the current code attaches the annotation on the nested array, instead of on the actual component type. I would have expected a loop here (or maybe we already have a helper for this...).
If that happens in `annotate`, a comment would be helpful.

File: checker/jtreg/stubs/issue1456lib/Lib.java [hunk 2]
```diff
@@ -0,0 +1,8 @@
+package issue1456lib;
+
+public class Lib {
+    public Object object;
+    public byte[] byteArray;
+    public Object object1, object2;
+    public byte byte1, byteArray2[];
```
Comment (wmdietl) [inline checker/jtreg/stubs/issue1456lib/Lib.java]: To test whether my other comment is true, you could add a two-dimensional array.
As a tiny comment, keeping the order of the declaration and the stubfile in sync makes them easier to read.
