### PR TITLE
Make caches in AnnotationUtils thread safe

### LINKED ISSUE #1108: make caches in AnnotationUtils thread safe
It'd be great if the [static caches in `AnnotationUtils`](https://github.com/typetools/checker-framework/blob/b7f67fc1c973439e8c2644490ca1d94eafc19a06/javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java#L60) could be made into instance fields instead (there are already `TODO` comments in the code to this effect).  Beyond the issue of memory leaks (motivating the `AnnotationUtils.clear()` method), these caches are not thread safe.  I am using the Checker dataflow framework from within [Buck](https://buckbuild.com/), and Buck runs multiple javac instances concurrently within the same JVM.  I got lucky and observed a crash due to a data race on these fields, but the issue could have lurked for a long time.

I have a patch to at least make the caches thread safe, while leaving them as static fields (via locking).  Changing them to be instance fields required more pervasive code changes than I felt capable of.  If doing the proper instance field fix isn't something doable in the short term, I am willing to contribute a fix to at least make them thread safe.

Also, FWIW, I observed that the attempt to bound [the `annotationMirrorNames` cache](https://github.com/typetools/checker-framework/blob/b7f67fc1c973439e8c2644490ca1d94eafc19a06/javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java#L69) using an LRU cache wasn't working.  The cache was still growing without bound, so I had to insert `clear()` calls anyway.  Not sure what exactly was going on; maybe things break when the cache persists across multiple javac instances?

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1108 

Mostly this is a matter of using Collections.synchronizedMap().  We also use an explicit synchronized block for when a containsKey() operation is followed by a get(), since AnnotationUtils.clear() might be called in between.

### CODE REVIEW

**Comment by msridhar** [comment]
I ran out of time to do full benchmarking, unfortunately (it seems to take a while).  I wanted to get the PR up in case someone else has time.

File: javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java [hunk 1]
```diff
@@ -67,21 +67,27 @@ public static void clear() {
      * so they can be compared with ==.
      */
     private static final Map<AnnotationMirror, /*@Interned*/ String> annotationMirrorNames =
-            CollectionUtils.createLRUCache(ANNOTATION_CACHE_SIZE);
+            Collections.synchronizedMap(
```
Comment (wmdietl) [inline javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java]: Could you create a new `CollectionUtils.createSynchronizedLRUCache` instead of duplicating this logic multiple times?

File: javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java [hunk 2]
```diff
@@ -92,8 +98,10 @@ public static void clear() {
      * @return an {@link AnnotationMirror} of type {@code} name
      */
     public static AnnotationMirror fromName(Elements elements, CharSequence name) {
-        if (annotationsFromNames.containsKey(name)) {
-            return annotationsFromNames.get(name);
+        synchronized (annotationsFromNames) {
```
Comment (wmdietl) [inline javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java]: Would it be shorter and still thread safe to do:

```
AnnotationMirror res = annotationsFromNames.get(name);
if (res != null) {
  return res;
}
...
```

Instead of checking and then getting the value, why not just get the value and see whether we got something?

File: javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java (hunk 1 above)
Comment (msridhar) [inline javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java]: Are you sure?  It's only duplicated twice (the other two cases wrap a `HashMap` rather than an LRU cache).

Comment (wmdietl) [inline javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java]: Oh, sorry about that. Yes, not worth adding a new method.

**Comment by msridhar** [comment]
Addressed the second comment about just using `get()`; nice catch.

**Comment by mernst** [comment]
Thanks for this contribution, Manu!
